<a href="https://colab.research.google.com/github/karthikoo7/Machine_Learning-BDA-/blob/main/Basic_Classification_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/content/cleaned_76hd.csv')
df.shape

(282, 39)

In [3]:
df['V58'].unique()

array([0, 1])

In [4]:
X = df.drop(columns=['V58'])
Y = df['V58']
X.shape,Y.shape

((282, 38), (282,))

In [5]:
from sklearn.model_selection import train_test_split

In [17]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3,random_state=7,stratify=Y)

X_train.shape,X_test.shape,Y_train.shape,Y_test.shape

((197, 38), (85, 38), (197,), (85,))

what does stratify=y do? Answer below

In [18]:
Y.value_counts(normalize=True)

V58
0    0.546099
1    0.453901
Name: proportion, dtype: float64

In [19]:
Y_train.value_counts(normalize=True) ## we get same distribution in both the original and training data

V58
0    0.548223
1    0.451777
Name: proportion, dtype: float64

In [20]:
Y_test.value_counts(normalize=True) # ratio of distribution of data remains same as in roginal data

V58
0    0.541176
1    0.458824
Name: proportion, dtype: float64

Important to standardize data for SVM, Optional for Logistic but preferred.

In [21]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)

In [23]:
X_train_sc.mean(),X_test_sc.mean() # close to 0

(np.float64(-4.0220743291256e-17), np.float64(0.00744590513160098))

In [26]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

Apply ML Models

In [29]:
lr = LogisticRegression(class_weight='balanced',random_state=7)
lr.fit(X_train_sc,Y_train)
Y_pred = lr.predict(X_test_sc)

In [30]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,Y_pred))

              precision    recall  f1-score   support

           0       0.82      0.80      0.81        46
           1       0.78      0.79      0.78        39

    accuracy                           0.80        85
   macro avg       0.80      0.80      0.80        85
weighted avg       0.80      0.80      0.80        85

Naive B

In [34]:
gnb = GaussianNB()
gnb.fit(X_train_sc,Y_train)
Y_pred = gnb.predict(X_test_sc)
print(classification_report(Y_test,Y_pred))

              precision    recall  f1-score   support

           0       0.63      1.00      0.77        46
           1       1.00      0.31      0.47        39

    accuracy                           0.68        85
   macro avg       0.82      0.65      0.62        85
weighted avg       0.80      0.68      0.63        85

In [35]:
bnb = BernoulliNB()
bnb.fit(X_train_sc,Y_train)
Y_pred = bnb.predict(X_test_sc)

print(classification_report(Y_test,Y_pred))

              precision    recall  f1-score   support

           0       0.80      0.87      0.83        46
           1       0.83      0.74      0.78        39

    accuracy                           0.81        85
   macro avg       0.81      0.81      0.81        85
weighted avg       0.81      0.81      0.81        85

SVM

In [36]:
svm = SVC(class_weight='balanced')
svm.fit(X_train_sc,Y_train)
Y_pred = svm.predict(X_test_sc)

print(classification_report(Y_test,Y_pred))

              precision    recall  f1-score   support

           0       0.78      0.85      0.81        46
           1       0.80      0.72      0.76        39

    accuracy                           0.79        85
   macro avg       0.79      0.78      0.78        85
weighted avg       0.79      0.79      0.79        85

KNN Classifier

In [37]:
knnc = KNeighborsClassifier()
knnc.fit(X_train_sc,Y_train)
Y_pred = knnc.predict(X_test_sc)

print(classification_report(Y_test,Y_pred))

              precision    recall  f1-score   support

           0       0.78      0.87      0.82        46
           1       0.82      0.72      0.77        39

    accuracy                           0.80        85
   macro avg       0.80      0.79      0.80        85
weighted avg       0.80      0.80      0.80        85

Decision Tree Classifier

In [39]:
dt = DecisionTreeClassifier(criterion='gini')
dt.fit(X_train_sc,Y_train)
Y_pred = dt.predict(X_test_sc)

print(classification_report(Y_test,Y_pred))

              precision    recall  f1-score   support

           0       0.78      0.67      0.72        46
           1       0.67      0.77      0.71        39

    accuracy                           0.72        85
   macro avg       0.72      0.72      0.72        85
weighted avg       0.73      0.72      0.72        85