<a href="https://colab.research.google.com/github/karthikoo7/Machine_Learning-BDA-/blob/main/Casestudy123.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
df = pd.read_csv("early_wakeup_health_dataset.csv")
df.shape

(10000, 64)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 64 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Person_ID                       10000 non-null  object
 1   Age                             10000 non-null  int64
 2   Gender                          10000 non-null  object
 3   Height_cm                       10000 non-null  float64
 4   Weight_kg                       10000 non-null  float64
 5   BMI                             10000 non-null  float64
 6   Country                         10000 non-null  object
 7   Occupation                      10000 non-null  object
 8   Marital_Status                  10000 non-null  object
 9   Wake_Up_Time                    10000 non-null  object
 10  Sleep_Time                      10000 non-null  object
 11  Sleep_Duration_Hours            10000 non-null  float64
 12  Sleep_Quality_Score             10000 non-null  float64
 13  Number_of_Night_Awakenings      10000 non-null  int64
 14  Weekend_Sleep_Difference_Hours  10000 non-null  float64
 15  Nap_Frequency_Per_Week          10000 non-null  int64
 16  Screen_Time_Before_Bed_Hours    10000 non-null  float64
 17  Exercise_Frequency_Per_Week     10000 non-null  int64
 18  Exercise_Duration_Minutes       10000 non-null  int64
 19  Exercise_Type                   9176 non-null   object
 20  Daily_Steps                     10000 non-null  int64
 21  Morning_Workout                 10000 non-null  object
 22  Workout_Intensity               9176 non-null   object
 23  Gym_Member                      10000 non-null  object
 24  Daily_Calorie_Intake            10000 non-null  int64
 25  Water_Intake_Liters             10000 non-null  float64
 26  Fruit_Intake_Per_Day            10000 non-null  int64
 27  Vegetable_Intake_Per_Day        10000 non-null  int64
 28  Protein_Intake_Grams            10000 non-null  float64
 29  Sugary_Drinks_Per_Week          10000 non-null  int64
 30  Fast_Food_Meals_Per_Week        10000 non-null  int64
 31  Breakfast_Regularity_Score      10000 non-null  float64
 32  Smoking_Status                  10000 non-null  object
 33  Alcohol_Consumption             6986 non-null   object
 34  Stress_Level                    10000 non-null  float64
 35  Working_Hours_Per_Day           10000 non-null  float64
 36  Sitting_Hours_Per_Day           10000 non-null  float64
 37  Outdoor_Time_Hours              10000 non-null  float64
 38  Social_Interaction_Score        10000 non-null  float64
 39  Meditation_Practice             10000 non-null  object
 40  Resting_Heart_Rate              10000 non-null  int64
 41  Systolic_BP                     10000 non-null  int64
 42  Diastolic_BP                    10000 non-null  int64
 43  Cholesterol_Level               10000 non-null  float64
 44  Blood_Sugar_Level               10000 non-null  float64
 45  Energy_Level_Score              10000 non-null  float64
 46  Fatigue_Level_Score             10000 non-null  float64
 47  Immune_Health_Score             10000 non-null  float64
 48  Mood_Score                      10000 non-null  float64
 49  Anxiety_Score                   10000 non-null  float64
 50  Depression_Risk_Score           10000 non-null  float64
 51  Productivity_Score              10000 non-null  float64
 52  Focus_Concentration_Score       10000 non-null  float64
 53  Life_Satisfaction_Score         10000 non-null  float64
 54  Obesity_Risk                    10000 non-null  object
 55  Hypertension_Risk               10000 non-null  object
 56  Diabetes_Risk                   10000 non-null  object
 57  Cardiovascular_Risk             10000 non-null  object
 58  Sleep_Disorder_Risk             10000 non-null  object
 59  Health_Score                    10000 non-null  float64
 60  Fitness_Level                   10000 non-null  object
 61  Healthy_Aging_Score             10000 non-null  float64
 62  Wellness_Category               10000 non-null  object
 63  Early_Waker                     10000 non-null  object
dtypes: float64(28), int64(14), object(22)
memory usage: 4.9+ MB

# Drop Columns

( irrelevent & possible target)

In [4]:
df.drop(columns=['Obesity_Risk'	,
'Hypertension_Risk'	,
'Diabetes_Risk'	,
'Cardiovascular_Risk'	,
'Sleep_Disorder_Risk'	,
'Health_Score'	,
'Healthy_Aging_Score'	,
'Wellness_Category'	,
'Early_Waker',
'Depression_Risk_Score',
'Gym_Member',
'Height_cm',
'Weight_kg',
'Person_ID',],inplace=True)
df.shape

(10000, 50)

# Convert date time to category

In [5]:
df['Wake_Up_Time'] = pd.to_datetime( df['Wake_Up_Time'])
df['Sleep_Time'] = pd.to_datetime( df['Sleep_Time'])

/tmp/ipykernel_3289/2732240999.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Wake_Up_Time'] = pd.to_datetime( df['Wake_Up_Time'])
/tmp/ipykernel_3289/2732240999.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Sleep_Time'] = pd.to_datetime( df['Sleep_Time'])

In [6]:
sorted(df['Sleep_Time'].unique())

[Timestamp('2026-06-28 00:00:00'),
 Timestamp('2026-06-28 00:01:00'),
 Timestamp('2026-06-28 00:02:00'),
 Timestamp('2026-06-28 00:03:00'),
 Timestamp('2026-06-28 00:04:00'),
 Timestamp('2026-06-28 00:05:00'),
 Timestamp('2026-06-28 00:06:00'),
 Timestamp('2026-06-28 00:07:00'),
 Timestamp('2026-06-28 00:08:00'),
 Timestamp('2026-06-28 00:09:00'),
 Timestamp('2026-06-28 00:10:00'),
 Timestamp('2026-06-28 00:11:00'),
 Timestamp('2026-06-28 00:12:00'),
 Timestamp('2026-06-28 00:13:00'),
 Timestamp('2026-06-28 00:14:00'),
 Timestamp('2026-06-28 00:15:00'),
 Timestamp('2026-06-28 00:16:00'),
 Timestamp('2026-06-28 00:17:00'),
 Timestamp('2026-06-28 00:18:00'),
 Timestamp('2026-06-28 00:19:00'),
 Timestamp('2026-06-28 00:20:00'),
 Timestamp('2026-06-28 00:21:00'),
 Timestamp('2026-06-28 00:22:00'),
 Timestamp('2026-06-28 00:23:00'),
 Timestamp('2026-06-28 00:24:00'),
 Timestamp('2026-06-28 00:25:00'),
 Timestamp('2026-06-28 00:26:00'),
 Timestamp('2026-06-28 00:27:00'),
 Timestamp('2026-06-28 00:28:00'),
 Timestamp('2026-06-28 00:29:00'),
 Timestamp('2026-06-28 00:30:00'),
 Timestamp('2026-06-28 00:31:00'),
 Timestamp('2026-06-28 00:32:00'),
 Timestamp('2026-06-28 00:33:00'),
 Timestamp('2026-06-28 00:34:00'),
 Timestamp('2026-06-28 00:35:00'),
 Timestamp('2026-06-28 00:36:00'),
 Timestamp('2026-06-28 00:37:00'),
 Timestamp('2026-06-28 00:38:00'),
 Timestamp('2026-06-28 00:39:00'),
 Timestamp('2026-06-28 00:40:00'),
 Timestamp('2026-06-28 00:41:00'),
 Timestamp('2026-06-28 00:42:00'),
 Timestamp('2026-06-28 00:43:00'),
 Timestamp('2026-06-28 00:44:00'),
 Timestamp('2026-06-28 00:45:00'),
 Timestamp('2026-06-28 00:46:00'),
 Timestamp('2026-06-28 00:47:00'),
 Timestamp('2026-06-28 00:48:00'),
 Timestamp('2026-06-28 00:49:00'),
 Timestamp('2026-06-28 00:50:00'),
 Timestamp('2026-06-28 00:51:00'),
 Timestamp('2026-06-28 00:52:00'),
 Timestamp('2026-06-28 00:53:00'),
 Timestamp('2026-06-28 00:54:00'),
 Timestamp('2026-06-28 00:55:00'),
 Timestamp('2026-06-28 00:56:00'),
 Timestamp('2026-06-28 00:57:00'),
 Timestamp('2026-06-28 00:58:00'),
 Timestamp('2026-06-28 00:59:00'),
 Timestamp('2026-06-28 01:00:00'),
 Timestamp('2026-06-28 01:01:00'),
 Timestamp('2026-06-28 01:02:00'),
 Timestamp('2026-06-28 01:03:00'),
 Timestamp('2026-06-28 01:04:00'),
 Timestamp('2026-06-28 01:05:00'),
 Timestamp('2026-06-28 01:06:00'),
 Timestamp('2026-06-28 01:07:00'),
 Timestamp('2026-06-28 01:08:00'),
 Timestamp('2026-06-28 01:09:00'),
 Timestamp('2026-06-28 01:10:00'),
 Timestamp('2026-06-28 01:11:00'),
 Timestamp('2026-06-28 01:12:00'),
 Timestamp('2026-06-28 01:13:00'),
 Timestamp('2026-06-28 01:14:00'),
 Timestamp('2026-06-28 01:15:00'),
 Timestamp('2026-06-28 01:16:00'),
 Timestamp('2026-06-28 01:17:00'),
 Timestamp('2026-06-28 01:18:00'),
 Timestamp('2026-06-28 01:19:00'),
 Timestamp('2026-06-28 01:20:00'),
 Timestamp('2026-06-28 01:21:00'),
 Timestamp('2026-06-28 01:22:00'),
 Timestamp('2026-06-28 01:23:00'),
 Timestamp('2026-06-28 01:24:00'),
 Timestamp('2026-06-28 01:25:00'),
 Timestamp('2026-06-28 01:26:00'),
 Timestamp('2026-06-28 01:27:00'),
 Timestamp('2026-06-28 01:28:00'),
 Timestamp('2026-06-28 01:29:00'),
 Timestamp('2026-06-28 01:30:00'),
 Timestamp('2026-06-28 01:31:00'),
 Timestamp('2026-06-28 01:32:00'),
 Timestamp('2026-06-28 01:33:00'),
 Timestamp('2026-06-28 01:34:00'),
 Timestamp('2026-06-28 01:35:00'),
 Timestamp('2026-06-28 01:36:00'),
 Timestamp('2026-06-28 01:37:00'),
 Timestamp('2026-06-28 01:38:00'),
 Timestamp('2026-06-28 01:39:00'),
 Timestamp('2026-06-28 01:40:00'),
 Timestamp('2026-06-28 01:41:00'),
 Timestamp('2026-06-28 01:42:00'),
 Timestamp('2026-06-28 01:43:00'),
 Timestamp('2026-06-28 01:44:00'),
 Timestamp('2026-06-28 01:45:00'),
 Timestamp('2026-06-28 01:46:00'),
 Timestamp('2026-06-28 01:47:00'),
 Timestamp('2026-06-28 01:48:00'),
 Timestamp('2026-06-28 01:49:00'),
 Timestamp('2026-06-28 01:50:00'),
 Timestamp('2026-06-28 01:51:00'),
 Timestamp('2026-06-28 01:52:00'),
 Timestamp('2026-06-28 01:53:00'),
 Timestamp('2026-06-28 01:54:00'),
 Timestamp('2026-06-28 01:55:00'),
 Timestamp('2026-06-28 01:56:00'),
 Timestamp('2026-06-28 01:57:00'),
 Timestamp('2026-06-28 01:58:00'),
 Timestamp('2026-06-28 01:59:00'),
 Timestamp('2026-06-28 02:00:00'),
 Timestamp('2026-06-28 02:01:00'),
 Timestamp('2026-06-28 02:02:00'),
 Timestamp('2026-06-28 02:03:00'),
 Timestamp('2026-06-28 02:04:00'),
 Timestamp('2026-06-28 02:05:00'),
 Timestamp('2026-06-28 02:06:00'),
 Timestamp('2026-06-28 02:07:00'),
 Timestamp('2026-06-28 02:08:00'),
 Timestamp('2026-06-28 02:09:00'),
 Timestamp('2026-06-28 02:10:00'),
 Timestamp('2026-06-28 02:11:00'),
 Timestamp('2026-06-28 02:12:00'),
 Timestamp('2026-06-28 02:13:00'),
 Timestamp('2026-06-28 02:14:00'),
 Timestamp('2026-06-28 02:15:00'),
 Timestamp('2026-06-28 02:16:00'),
 Timestamp('2026-06-28 02:17:00'),
 Timestamp('2026-06-28 02:18:00'),
 Timestamp('2026-06-28 02:19:00'),
 Timestamp('2026-06-28 02:20:00'),
 Timestamp('2026-06-28 02:21:00'),
 Timestamp('2026-06-28 02:22:00'),
 Timestamp('2026-06-28 02:23:00'),
 Timestamp('2026-06-28 02:24:00'),
 Timestamp('2026-06-28 02:25:00'),
 Timestamp('2026-06-28 02:26:00'),
 Timestamp('2026-06-28 02:27:00'),
 Timestamp('2026-06-28 02:28:00'),
 Timestamp('2026-06-28 02:29:00'),
 Timestamp('2026-06-28 02:30:00'),
 Timestamp('2026-06-28 02:31:00'),
 Timestamp('2026-06-28 02:32:00'),
 Timestamp('2026-06-28 02:33:00'),
 Timestamp('2026-06-28 02:34:00'),
 Timestamp('2026-06-28 02:35:00'),
 Timestamp('2026-06-28 02:36:00'),
 Timestamp('2026-06-28 02:37:00'),
 Timestamp('2026-06-28 02:38:00'),
 Timestamp('2026-06-28 02:39:00'),
 Timestamp('2026-06-28 02:40:00'),
 Timestamp('2026-06-28 02:41:00'),
 Timestamp('2026-06-28 02:42:00'),
 Timestamp('2026-06-28 02:43:00'),
 Timestamp('2026-06-28 02:44:00'),
 Timestamp('2026-06-28 02:45:00'),
 Timestamp('2026-06-28 02:46:00'),
 Timestamp('2026-06-28 02:47:00'),
 Timestamp('2026-06-28 02:48:00'),
 Timestamp('2026-06-28 02:49:00'),
 Timestamp('2026-06-28 02:50:00'),
 Timestamp('2026-06-28 02:51:00'),
 Timestamp('2026-06-28 02:52:00'),
 Timestamp('2026-06-28 02:53:00'),
 Timestamp('2026-06-28 02:54:00'),
 Timestamp('2026-06-28 02:55:00'),
 Timestamp('2026-06-28 02:56:00'),
 Timestamp('2026-06-28 02:57:00'),
 Timestamp('2026-06-28 02:58:00'),
 Timestamp('2026-06-28 02:59:00'),
 Timestamp('2026-06-28 03:00:00'),
 Timestamp('2026-06-28 03:01:00'),
 Timestamp('2026-06-28 03:02:00'),
 Timestamp('2026-06-28 03:03:00'),
 Timestamp('2026-06-28 03:04:00'),
 Timestamp('2026-06-28 03:05:00'),
 Timestamp('2026-06-28 03:06:00'),
 Timestamp('2026-06-28 03:07:00'),
 Timestamp('2026-06-28 03:08:00'),
 Timestamp('2026-06-28 03:09:00'),
 Timestamp('2026-06-28 03:10:00'),
 Timestamp('2026-06-28 03:11:00'),
 Timestamp('2026-06-28 03:12:00'),
 Timestamp('2026-06-28 03:13:00'),
 Timestamp('2026-06-28 03:14:00'),
 Timestamp('2026-06-28 03:15:00'),
 Timestamp('2026-06-28 03:16:00'),
 Timestamp('2026-06-28 03:17:00'),
 Timestamp('2026-06-28 03:18:00'),
 Timestamp('2026-06-28 03:19:00'),
 Timestamp('2026-06-28 03:20:00'),
 Timestamp('2026-06-28 03:21:00'),
 Timestamp('2026-06-28 03:22:00'),
 Timestamp('2026-06-28 03:23:00'),
 Timestamp('2026-06-28 03:24:00'),
 Timestamp('2026-06-28 03:25:00'),
 Timestamp('2026-06-28 03:26:00'),
 Timestamp('2026-06-28 03:27:00'),
 Timestamp('2026-06-28 03:28:00'),
 Timestamp('2026-06-28 03:29:00'),
 Timestamp('2026-06-28 03:30:00'),
 Timestamp('2026-06-28 03:31:00'),
 Timestamp('2026-06-28 03:32:00'),
 Timestamp('2026-06-28 03:33:00'),
 Timestamp('2026-06-28 03:34:00'),
 Timestamp('2026-06-28 03:35:00'),
 Timestamp('2026-06-28 03:36:00'),
 Timestamp('2026-06-28 03:37:00'),
 Timestamp('2026-06-28 03:38:00'),
 Timestamp('2026-06-28 03:39:00'),
 Timestamp('2026-06-28 03:40:00'),
 Timestamp('2026-06-28 03:41:00'),
 Timestamp('2026-06-28 03:42:00'),
 Timestamp('2026-06-28 03:43:00'),
 Timestamp('2026-06-28 03:44:00'),
 Timestamp('2026-06-28 03:45:00'),
 Timestamp('2026-06-28 03:47:00'),
 Timestamp('2026-06-28 03:48:00'),
 Timestamp('2026-06-28 03:49:00'),
 Timestamp('2026-06-28 03:50:00'),
 Timestamp('2026-06-28 03:51:00'),
 Timestamp('2026-06-28 03:52:00'),
 Timestamp('2026-06-28 03:53:00'),
 Timestamp('2026-06-28 03:55:00'),
 Timestamp('2026-06-28 03:56:00'),
 Timestamp('2026-06-28 03:57:00'),
 Timestamp('2026-06-28 04:00:00'),
 Timestamp('2026-06-28 04:01:00'),
 Timestamp('2026-06-28 04:02:00'),
 Timestamp('2026-06-28 04:04:00'),
 Timestamp('2026-06-28 04:05:00'),
 Timestamp('2026-06-28 04:06:00'),
 Timestamp('2026-06-28 04:08:00'),
 Timestamp('2026-06-28 04:11:00'),
 Timestamp('2026-06-28 04:13:00'),
 Timestamp('2026-06-28 04:14:00'),
 Timestamp('2026-06-28 04:15:00'),
 Timestamp('2026-06-28 04:16:00'),
 Timestamp('2026-06-28 04:17:00'),
 Timestamp('2026-06-28 04:18:00'),
 Timestamp('2026-06-28 04:19:00'),
 Timestamp('2026-06-28 04:21:00'),
 Timestamp('2026-06-28 04:23:00'),
 Timestamp('2026-06-28 04:24:00'),
 Timestamp('2026-06-28 04:25:00'),
 Timestamp('2026-06-28 04:27:00'),
 Timestamp('2026-06-28 04:28:00'),
 Timestamp('2026-06-28 04:29:00'),
 Timestamp('2026-06-28 04:31:00'),
 Timestamp('2026-06-28 04:33:00'),
 Timestamp('2026-06-28 04:35:00'),
 Timestamp('2026-06-28 04:38:00'),
 Timestamp('2026-06-28 04:39:00'),
 Timestamp('2026-06-28 04:42:00'),
 Timestamp('2026-06-28 04:45:00'),
 Timestamp('2026-06-28 04:47:00'),
 Timestamp('2026-06-28 04:57:00'),
 Timestamp('2026-06-28 04:59:00'),
 Timestamp('2026-06-28 05:02:00'),
 Timestamp('2026-06-28 05:03:00'),
 Timestamp('2026-06-28 05:08:00'),
 Timestamp('2026-06-28 05:18:00'),
 Timestamp('2026-06-28 05:22:00'),
 Timestamp('2026-06-28 05:23:00'),
 Timestamp('2026-06-28 05:25:00'),
 Timestamp('2026-06-28 05:30:00'),
 Timestamp('2026-06-28 05:31:00'),
 Timestamp('2026-06-28 05:43:00'),
 Timestamp('2026-06-28 05:47:00'),
 Timestamp('2026-06-28 05:51:00'),
 Timestamp('2026-06-28 06:28:00'),
 Timestamp('2026-06-28 18:00:00'),
 Timestamp('2026-06-28 18:12:00'),
 Timestamp('2026-06-28 18:19:00'),
 Timestamp('2026-06-28 18:25:00'),
 Timestamp('2026-06-28 18:27:00'),
 Timestamp('2026-06-28 18:30:00'),
 Timestamp('2026-06-28 18:35:00'),
 Timestamp('2026-06-28 18:36:00'),
 Timestamp('2026-06-28 18:41:00'),
 Timestamp('2026-06-28 18:42:00'),
 Timestamp('2026-06-28 18:44:00'),
 Timestamp('2026-06-28 18:46:00'),
 Timestamp('2026-06-28 18:48:00'),
 Timestamp('2026-06-28 18:49:00'),
 Timestamp('2026-06-28 18:50:00'),
 Timestamp('2026-06-28 18:53:00'),
 Timestamp('2026-06-28 18:54:00'),
 Timestamp('2026-06-28 18:56:00'),
 Timestamp('2026-06-28 18:57:00'),
 Timestamp('2026-06-28 18:59:00'),
 Timestamp('2026-06-28 19:03:00'),
 Timestamp('2026-06-28 19:04:00'),
 Timestamp('2026-06-28 19:07:00'),
 Timestamp('2026-06-28 19:08:00'),
 Timestamp('2026-06-28 19:09:00'),
 Timestamp('2026-06-28 19:10:00'),
 Timestamp('2026-06-28 19:11:00'),
 Timestamp('2026-06-28 19:12:00'),
 Timestamp('2026-06-28 19:13:00'),
 Timestamp('2026-06-28 19:14:00'),
 Timestamp('2026-06-28 19:15:00'),
 Timestamp('2026-06-28 19:16:00'),
 Timestamp('2026-06-28 19:17:00'),
 Timestamp('2026-06-28 19:18:00'),
 Timestamp('2026-06-28 19:20:00'),
 Timestamp('2026-06-28 19:21:00'),
 Timestamp('2026-06-28 19:22:00'),
 Timestamp('2026-06-28 19:23:00'),
 Timestamp('2026-06-28 19:24:00'),
 Timestamp('2026-06-28 19:25:00'),
 Timestamp('2026-06-28 19:26:00'),
 Timestamp('2026-06-28 19:27:00'),
 Timestamp('2026-06-28 19:28:00'),
 Timestamp('2026-06-28 19:29:00'),
 Timestamp('2026-06-28 19:30:00'),
 Timestamp('2026-06-28 19:31:00'),
 Timestamp('2026-06-28 19:32:00'),
 Timestamp('2026-06-28 19:33:00'),
 Timestamp('2026-06-28 19:34:00'),
 Timestamp('2026-06-28 19:36:00'),
 Timestamp('2026-06-28 19:37:00'),
 Timestamp('2026-06-28 19:38:00'),
 Timestamp('2026-06-28 19:39:00'),
 Timestamp('2026-06-28 19:40:00'),
 Timestamp('2026-06-28 19:41:00'),
 Timestamp('2026-06-28 19:43:00'),
 Timestamp('2026-06-28 19:44:00'),
 Timestamp('2026-06-28 19:45:00'),
 Timestamp('2026-06-28 19:46:00'),
 Timestamp('2026-06-28 19:47:00'),
 Timestamp('2026-06-28 19:48:00'),
 Timestamp('2026-06-28 19:49:00'),
 Timestamp('2026-06-28 19:50:00'),
 Timestamp('2026-06-28 19:51:00'),
 Timestamp('2026-06-28 19:52:00'),
 Timestamp('2026-06-28 19:53:00'),
 Timestamp('2026-06-28 19:54:00'),
 Timestamp('2026-06-28 19:55:00'),
 Timestamp('2026-06-28 19:56:00'),
 Timestamp('2026-06-28 19:57:00'),
 Timestamp('2026-06-28 19:58:00'),
 Timestamp('2026-06-28 19:59:00'),
 Timestamp('2026-06-28 20:00:00'),
 Timestamp('2026-06-28 20:01:00'),
 Timestamp('2026-06-28 20:02:00'),
 Timestamp('2026-06-28 20:03:00'),
 Timestamp('2026-06-28 20:04:00'),
 Timestamp('2026-06-28 20:05:00'),
 Timestamp('2026-06-28 20:06:00'),
 Timestamp('2026-06-28 20:07:00'),
 Timestamp('2026-06-28 20:08:00'),
 Timestamp('2026-06-28 20:09:00'),
 Timestamp('2026-06-28 20:10:00'),
 Timestamp('2026-06-28 20:11:00'),
 Timestamp('2026-06-28 20:12:00'),
 Timestamp('2026-06-28 20:13:00'),
 Timestamp('2026-06-28 20:14:00'),
 Timestamp('2026-06-28 20:15:00'),
 Timestamp('2026-06-28 20:16:00'),
 Timestamp('2026-06-28 20:17:00'),
 Timestamp('2026-06-28 20:18:00'),
 Timestamp('2026-06-28 20:19:00'),
 Timestamp('2026-06-28 20:20:00'),
 Timestamp('2026-06-28 20:21:00'),
 Timestamp('2026-06-28 20:22:00'),
 Timestamp('2026-06-28 20:23:00'),
 Timestamp('2026-06-28 20:24:00'),
 Timestamp('2026-06-28 20:25:00'),
 Timestamp('2026-06-28 20:26:00'),
 Timestamp('2026-06-28 20:27:00'),
 Timestamp('2026-06-28 20:28:00'),
 Timestamp('2026-06-28 20:29:00'),
 Timestamp('2026-06-28 20:30:00'),
 Timestamp('2026-06-28 20:31:00'),
 Timestamp('2026-06-28 20:32:00'),
 Timestamp('2026-06-28 20:33:00'),
 Timestamp('2026-06-28 20:34:00'),
 Timestamp('2026-06-28 20:35:00'),
 Timestamp('2026-06-28 20:36:00'),
 Timestamp('2026-06-28 20:37:00'),
 Timestamp('2026-06-28 20:38:00'),
 Timestamp('2026-06-28 20:39:00'),
 Timestamp('2026-06-28 20:40:00'),
 Timestamp('2026-06-28 20:41:00'),
 Timestamp('2026-06-28 20:42:00'),
 Timestamp('2026-06-28 20:43:00'),
 Timestamp('2026-06-28 20:44:00'),
 Timestamp('2026-06-28 20:45:00'),
 Timestamp('2026-06-28 20:46:00'),
 Timestamp('2026-06-28 20:47:00'),
 Timestamp('2026-06-28 20:48:00'),
 Timestamp('2026-06-28 20:49:00'),
 Timestamp('2026-06-28 20:50:00'),
 Timestamp('2026-06-28 20:51:00'),
 Timestamp('2026-06-28 20:52:00'),
 Timestamp('2026-06-28 20:53:00'),
 Timestamp('2026-06-28 20:54:00'),
 Timestamp('2026-06-28 20:55:00'),
 Timestamp('2026-06-28 20:56:00'),
 Timestamp('2026-06-28 20:57:00'),
 Timestamp('2026-06-28 20:58:00'),
 Timestamp('2026-06-28 20:59:00'),
 Timestamp('2026-06-28 21:00:00'),
 Timestamp('2026-06-28 21:01:00'),
 Timestamp('2026-06-28 21:02:00'),
 Timestamp('2026-06-28 21:03:00'),
 Timestamp('2026-06-28 21:04:00'),
 Timestamp('2026-06-28 21:05:00'),
 Timestamp('2026-06-28 21:06:00'),
 Timestamp('2026-06-28 21:07:00'),
 Timestamp('2026-06-28 21:08:00'),
 Timestamp('2026-06-28 21:09:00'),
 Timestamp('2026-06-28 21:10:00'),
 Timestamp('2026-06-28 21:11:00'),
 Timestamp('2026-06-28 21:12:00'),
 Timestamp('2026-06-28 21:13:00'),
 Timestamp('2026-06-28 21:14:00'),
 Timestamp('2026-06-28 21:15:00'),
 Timestamp('2026-06-28 21:16:00'),
 Timestamp('2026-06-28 21:17:00'),
 Timestamp('2026-06-28 21:18:00'),
 Timestamp('2026-06-28 21:19:00'),
 Timestamp('2026-06-28 21:20:00'),
 Timestamp('2026-06-28 21:21:00'),
 Timestamp('2026-06-28 21:22:00'),
 Timestamp('2026-06-28 21:23:00'),
 Timestamp('2026-06-28 21:24:00'),
 Timestamp('2026-06-28 21:25:00'),
 Timestamp('2026-06-28 21:26:00'),
 Timestamp('2026-06-28 21:27:00'),
 Timestamp('2026-06-28 21:28:00'),
 Timestamp('2026-06-28 21:29:00'),
 Timestamp('2026-06-28 21:30:00'),
 Timestamp('2026-06-28 21:31:00'),
 Timestamp('2026-06-28 21:32:00'),
 Timestamp('2026-06-28 21:33:00'),
 Timestamp('2026-06-28 21:34:00'),
 Timestamp('2026-06-28 21:35:00'),
 Timestamp('2026-06-28 21:36:00'),
 Timestamp('2026-06-28 21:37:00'),
 Timestamp('2026-06-28 21:38:00'),
 Timestamp('2026-06-28 21:39:00'),
 Timestamp('2026-06-28 21:40:00'),
 Timestamp('2026-06-28 21:41:00'),
 Timestamp('2026-06-28 21:42:00'),
 Timestamp('2026-06-28 21:43:00'),
 Timestamp('2026-06-28 21:44:00'),
 Timestamp('2026-06-28 21:45:00'),
 Timestamp('2026-06-28 21:46:00'),
 Timestamp('2026-06-28 21:47:00'),
 Timestamp('2026-06-28 21:48:00'),
 Timestamp('2026-06-28 21:49:00'),
 Timestamp('2026-06-28 21:50:00'),
 Timestamp('2026-06-28 21:51:00'),
 Timestamp('2026-06-28 21:52:00'),
 Timestamp('2026-06-28 21:53:00'),
 Timestamp('2026-06-28 21:54:00'),
 Timestamp('2026-06-28 21:55:00'),
 Timestamp('2026-06-28 21:56:00'),
 Timestamp('2026-06-28 21:57:00'),
 Timestamp('2026-06-28 21:58:00'),
 Timestamp('2026-06-28 21:59:00'),
 Timestamp('2026-06-28 22:00:00'),
 Timestamp('2026-06-28 22:01:00'),
 Timestamp('2026-06-28 22:02:00'),
 Timestamp('2026-06-28 22:03:00'),
 Timestamp('2026-06-28 22:04:00'),
 Timestamp('2026-06-28 22:05:00'),
 Timestamp('2026-06-28 22:06:00'),
 Timestamp('2026-06-28 22:07:00'),
 Timestamp('2026-06-28 22:08:00'),
 Timestamp('2026-06-28 22:09:00'),
 Timestamp('2026-06-28 22:10:00'),
 Timestamp('2026-06-28 22:11:00'),
 Timestamp('2026-06-28 22:12:00'),
 Timestamp('2026-06-28 22:13:00'),
 Timestamp('2026-06-28 22:14:00'),
 Timestamp('2026-06-28 22:15:00'),
 Timestamp('2026-06-28 22:16:00'),
 Timestamp('2026-06-28 22:17:00'),
 Timestamp('2026-06-28 22:18:00'),
 Timestamp('2026-06-28 22:19:00'),
 Timestamp('2026-06-28 22:20:00'),
 Timestamp('2026-06-28 22:21:00'),
 Timestamp('2026-06-28 22:22:00'),
 Timestamp('2026-06-28 22:23:00'),
 Timestamp('2026-06-28 22:24:00'),
 Timestamp('2026-06-28 22:25:00'),
 Timestamp('2026-06-28 22:26:00'),
 Timestamp('2026-06-28 22:27:00'),
 Timestamp('2026-06-28 22:28:00'),
 Timestamp('2026-06-28 22:29:00'),
 Timestamp('2026-06-28 22:30:00'),
 Timestamp('2026-06-28 22:31:00'),
 Timestamp('2026-06-28 22:32:00'),
 Timestamp('2026-06-28 22:33:00'),
 Timestamp('2026-06-28 22:34:00'),
 Timestamp('2026-06-28 22:35:00'),
 Timestamp('2026-06-28 22:36:00'),
 Timestamp('2026-06-28 22:37:00'),
 Timestamp('2026-06-28 22:38:00'),
 Timestamp('2026-06-28 22:39:00'),
 Timestamp('2026-06-28 22:40:00'),
 Timestamp('2026-06-28 22:41:00'),
 Timestamp('2026-06-28 22:42:00'),
 Timestamp('2026-06-28 22:43:00'),
 Timestamp('2026-06-28 22:44:00'),
 Timestamp('2026-06-28 22:45:00'),
 Timestamp('2026-06-28 22:46:00'),
 Timestamp('2026-06-28 22:47:00'),
 Timestamp('2026-06-28 22:48:00'),
 Timestamp('2026-06-28 22:49:00'),
 Timestamp('2026-06-28 22:50:00'),
 Timestamp('2026-06-28 22:51:00'),
 Timestamp('2026-06-28 22:52:00'),
 Timestamp('2026-06-28 22:53:00'),
 Timestamp('2026-06-28 22:54:00'),
 Timestamp('2026-06-28 22:55:00'),
 Timestamp('2026-06-28 22:56:00'),
 Timestamp('2026-06-28 22:57:00'),
 Timestamp('2026-06-28 22:58:00'),
 Timestamp('2026-06-28 22:59:00'),
 Timestamp('2026-06-28 23:00:00'),
 Timestamp('2026-06-28 23:01:00'),
 Timestamp('2026-06-28 23:02:00'),
 Timestamp('2026-06-28 23:03:00'),
 Timestamp('2026-06-28 23:04:00'),
 Timestamp('2026-06-28 23:05:00'),
 Timestamp('2026-06-28 23:06:00'),
 Timestamp('2026-06-28 23:07:00'),
 Timestamp('2026-06-28 23:08:00'),
 Timestamp('2026-06-28 23:09:00'),
 Timestamp('2026-06-28 23:10:00'),
 Timestamp('2026-06-28 23:11:00'),
 Timestamp('2026-06-28 23:12:00'),
 Timestamp('2026-06-28 23:13:00'),
 Timestamp('2026-06-28 23:14:00'),
 Timestamp('2026-06-28 23:15:00'),
 Timestamp('2026-06-28 23:16:00'),
 Timestamp('2026-06-28 23:17:00'),
 Timestamp('2026-06-28 23:18:00'),
 Timestamp('2026-06-28 23:19:00'),
 Timestamp('2026-06-28 23:20:00'),
 Timestamp('2026-06-28 23:21:00'),
 Timestamp('2026-06-28 23:22:00'),
 Timestamp('2026-06-28 23:23:00'),
 Timestamp('2026-06-28 23:24:00'),
 Timestamp('2026-06-28 23:25:00'),
 Timestamp('2026-06-28 23:26:00'),
 Timestamp('2026-06-28 23:27:00'),
 Timestamp('2026-06-28 23:28:00'),
 Timestamp('2026-06-28 23:29:00'),
 Timestamp('2026-06-28 23:30:00'),
 Timestamp('2026-06-28 23:31:00'),
 Timestamp('2026-06-28 23:32:00'),
 Timestamp('2026-06-28 23:33:00'),
 Timestamp('2026-06-28 23:34:00'),
 Timestamp('2026-06-28 23:35:00'),
 Timestamp('2026-06-28 23:36:00'),
 Timestamp('2026-06-28 23:37:00'),

In [7]:
df['WT_cat'] = 0

In [8]:
df.loc[(df['Wake_Up_Time'] >= "2026-06-27 04:00:00") &
       (df['Wake_Up_Time'] < "2026-06-27 06:00:00"), "WT_cat"]=0
df.loc[(df['Wake_Up_Time'] >= "2026-06-27 06:00:00") &
       (df['Wake_Up_Time'] < "2026-06-27 08:00:00"), "WT_cat"]=1
df.loc[(df['Wake_Up_Time'] >= "2026-06-27 08:00:00") &
       (df['Wake_Up_Time'] < "2026-06-27 10:00:00"), "WT_cat"]=2
df.loc[(df['Wake_Up_Time'] >= "2026-06-27 10:00:00") &
       (df['Wake_Up_Time'] <= "2026-06-27 11:00:00"), "WT_cat"]=3

In [9]:
df['WT_cat'].unique()

array([0])

In [10]:
df['ST_cat'] = 0

In [11]:
df.loc[(df['Sleep_Time'] >= "2026-06-27 20:00:00") &
       (df['Sleep_Time'] < "2026-06-27 22:00:00"), "ST_cat"]=0
df.loc[(df['Sleep_Time'] >= "2026-06-27 22:00:00") &
       (df['Sleep_Time'] <= "2026-06-27 23:59:00"), "ST_cat"]=1
df.loc[(df['Sleep_Time'] >= "2026-06-27 00:00:00") &
       (df['Sleep_Time'] < "2026-06-27 03:00:00"), "ST_cat"]=2
df.loc[(df['Sleep_Time'] >= "2026-06-27 03:00:00") &
       (df['Sleep_Time'] < "2026-06-27 07:00:00"), "ST_cat"]=3
df.loc[(df['Sleep_Time'] >= "2026-06-27 18:00:00") &
       (df['Sleep_Time'] < "2026-06-27 20:00:00"), "ST_cat"]=4

In [12]:
df['ST_cat'].unique()

array([0])

In [13]:
df.drop(columns=['Wake_Up_Time',
                 'Sleep_Time'],inplace=True)

In [14]:
df.shape

(10000, 50)

In [15]:
df.columns

Index(['Age', 'Gender', 'BMI', 'Country', 'Occupation', 'Marital_Status',
       'Sleep_Duration_Hours', 'Sleep_Quality_Score',
       'Number_of_Night_Awakenings', 'Weekend_Sleep_Difference_Hours',
       'Nap_Frequency_Per_Week', 'Screen_Time_Before_Bed_Hours',
       'Exercise_Frequency_Per_Week', 'Exercise_Duration_Minutes',
       'Exercise_Type', 'Daily_Steps', 'Morning_Workout', 'Workout_Intensity',
       'Daily_Calorie_Intake', 'Water_Intake_Liters', 'Fruit_Intake_Per_Day',
       'Vegetable_Intake_Per_Day', 'Protein_Intake_Grams',
       'Sugary_Drinks_Per_Week', 'Fast_Food_Meals_Per_Week',
       'Breakfast_Regularity_Score', 'Smoking_Status', 'Alcohol_Consumption',
       'Stress_Level', 'Working_Hours_Per_Day', 'Sitting_Hours_Per_Day',
       'Outdoor_Time_Hours', 'Social_Interaction_Score', 'Meditation_Practice',
       'Resting_Heart_Rate', 'Systolic_BP', 'Diastolic_BP',
       'Cholesterol_Level', 'Blood_Sugar_Level', 'Energy_Level_Score',
       'Fatigue_Level_Score', 'Immune_Health_Score', 'Mood_Score',
       'Anxiety_Score', 'Productivity_Score', 'Focus_Concentration_Score',
       'Life_Satisfaction_Score', 'Fitness_Level', 'WT_cat', 'ST_cat'],
      dtype='object')

# Fill missing values

In [16]:
df.isnull().sum()#

Age                                  0
Gender                               0
BMI                                  0
Country                              0
Occupation                           0
Marital_Status                       0
Sleep_Duration_Hours                 0
Sleep_Quality_Score                  0
Number_of_Night_Awakenings           0
Weekend_Sleep_Difference_Hours       0
Nap_Frequency_Per_Week               0
Screen_Time_Before_Bed_Hours         0
Exercise_Frequency_Per_Week          0
Exercise_Duration_Minutes            0
Exercise_Type                      824
Daily_Steps                          0
Morning_Workout                      0
Workout_Intensity                  824
Daily_Calorie_Intake                 0
Water_Intake_Liters                  0
Fruit_Intake_Per_Day                 0
Vegetable_Intake_Per_Day             0
Protein_Intake_Grams                 0
Sugary_Drinks_Per_Week               0
Fast_Food_Meals_Per_Week             0
Breakfast_Regularity_Score           0
Smoking_Status                       0
Alcohol_Consumption               3014
Stress_Level                         0
Working_Hours_Per_Day                0
Sitting_Hours_Per_Day                0
Outdoor_Time_Hours                   0
Social_Interaction_Score             0
Meditation_Practice                  0
Resting_Heart_Rate                   0
Systolic_BP                          0
Diastolic_BP                         0
Cholesterol_Level                    0
Blood_Sugar_Level                    0
Energy_Level_Score                   0
Fatigue_Level_Score                  0
Immune_Health_Score                  0
Mood_Score                           0
Anxiety_Score                        0
Productivity_Score                   0
Focus_Concentration_Score            0
Life_Satisfaction_Score              0
Fitness_Level                        0
WT_cat                               0
ST_cat                               0
dtype: int64

In [17]:
df.loc[df['Alcohol_Consumption'].isna() == True,
       'Alcohol_Consumption'] = 0

In [18]:
df[['Exercise_Type','Workout_Intensity']].mode().iloc[0]

Exercise_Type        Weight Training
Workout_Intensity           Moderate
Name: 0, dtype: object

In [19]:
fill_value = df.mode().iloc[0]
df.fillna(fill_value,inplace=True)

In [20]:

df.isnull().sum().sum()

np.int64(0)

# Handle ordinal columns

label encoding

In [21]:
df['Workout_Intensity'].unique()

array(['Low', 'Moderate', 'High'], dtype=object)

In [22]:
df['Smoking_Status'].unique()

array(['Former', 'Current', 'Never'], dtype=object)

In [23]:
df['Alcohol_Consumption'].unique()

array(['Moderate', 0, 'Light', 'Heavy'], dtype=object)

In [24]:
label_map={'Workout_Intensity':{'Low':0, 'Moderate':1, 'High':2},
  'Smoking_Status':{'Former':1, 'Current':2, 'Never':0},
  'Alcohol_Consumption':{'Moderate':2, 'Light':1, 'Heavy':3}
}

In [25]:
df.replace(label_map,inplace=True)

/tmp/ipykernel_3289/1715271054.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(label_map,inplace=True)

In [26]:
df['Alcohol_Consumption'].unique()

array([2, 0, 1, 3])

In [27]:
df['Smoking_Status'].unique()

array([1, 2, 0])

In [28]:
df['Workout_Intensity'].unique()

array([0, 1, 2])

# Check

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 50 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Age                             10000 non-null  int64
 1   Gender                          10000 non-null  object
 2   BMI                             10000 non-null  float64
 3   Country                         10000 non-null  object
 4   Occupation                      10000 non-null  object
 5   Marital_Status                  10000 non-null  object
 6   Sleep_Duration_Hours            10000 non-null  float64
 7   Sleep_Quality_Score             10000 non-null  float64
 8   Number_of_Night_Awakenings      10000 non-null  int64
 9   Weekend_Sleep_Difference_Hours  10000 non-null  float64
 10  Nap_Frequency_Per_Week          10000 non-null  int64
 11  Screen_Time_Before_Bed_Hours    10000 non-null  float64
 12  Exercise_Frequency_Per_Week     10000 non-null  int64
 13  Exercise_Duration_Minutes       10000 non-null  int64
 14  Exercise_Type                   10000 non-null  object
 15  Daily_Steps                     10000 non-null  int64
 16  Morning_Workout                 10000 non-null  object
 17  Workout_Intensity               10000 non-null  int64
 18  Daily_Calorie_Intake            10000 non-null  int64
 19  Water_Intake_Liters             10000 non-null  float64
 20  Fruit_Intake_Per_Day            10000 non-null  int64
 21  Vegetable_Intake_Per_Day        10000 non-null  int64
 22  Protein_Intake_Grams            10000 non-null  float64
 23  Sugary_Drinks_Per_Week          10000 non-null  int64
 24  Fast_Food_Meals_Per_Week        10000 non-null  int64
 25  Breakfast_Regularity_Score      10000 non-null  float64
 26  Smoking_Status                  10000 non-null  int64
 27  Alcohol_Consumption             10000 non-null  int64
 28  Stress_Level                    10000 non-null  float64
 29  Working_Hours_Per_Day           10000 non-null  float64
 30  Sitting_Hours_Per_Day           10000 non-null  float64
 31  Outdoor_Time_Hours              10000 non-null  float64
 32  Social_Interaction_Score        10000 non-null  float64
 33  Meditation_Practice             10000 non-null  object
 34  Resting_Heart_Rate              10000 non-null  int64
 35  Systolic_BP                     10000 non-null  int64
 36  Diastolic_BP                    10000 non-null  int64
 37  Cholesterol_Level               10000 non-null  float64
 38  Blood_Sugar_Level               10000 non-null  float64
 39  Energy_Level_Score              10000 non-null  float64
 40  Fatigue_Level_Score             10000 non-null  float64
 41  Immune_Health_Score             10000 non-null  float64
 42  Mood_Score                      10000 non-null  float64
 43  Anxiety_Score                   10000 non-null  float64
 44  Productivity_Score              10000 non-null  float64
 45  Focus_Concentration_Score       10000 non-null  float64
 46  Life_Satisfaction_Score         10000 non-null  float64
 47  Fitness_Level                   10000 non-null  object
 48  WT_cat                          10000 non-null  int64
 49  ST_cat                          10000 non-null  int64
dtypes: float64(23), int64(19), object(8)
memory usage: 3.8+ MB

# X & Y split

target : fitness level

In [30]:
X = df.drop(columns=['Fitness_Level'])
Y = df['Fitness_Level']
X.shape,Y.shape

((10000, 49), (10000,))

In [31]:
Y.unique()

array(['Excellent', 'Good', 'Average', 'Poor'], dtype=object)

In [32]:
label_map = {'Excellent':3, 'Good':2, 'Average':1, 'Poor':0}
Y.replace(label_map,inplace=True)

/tmp/ipykernel_3289/1394058508.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  Y.replace(label_map,inplace=True)

In [33]:
Y.unique()

array([3, 2, 1, 0])

In [34]:
X_ohe = pd.get_dummies(X)
X_ohe.shape

(10000, 91)

In [35]:
X_ohe.columns

Index(['Age', 'BMI', 'Sleep_Duration_Hours', 'Sleep_Quality_Score',
       'Number_of_Night_Awakenings', 'Weekend_Sleep_Difference_Hours',
       'Nap_Frequency_Per_Week', 'Screen_Time_Before_Bed_Hours',
       'Exercise_Frequency_Per_Week', 'Exercise_Duration_Minutes',
       'Daily_Steps', 'Workout_Intensity', 'Daily_Calorie_Intake',
       'Water_Intake_Liters', 'Fruit_Intake_Per_Day',
       'Vegetable_Intake_Per_Day', 'Protein_Intake_Grams',
       'Sugary_Drinks_Per_Week', 'Fast_Food_Meals_Per_Week',
       'Breakfast_Regularity_Score', 'Smoking_Status', 'Alcohol_Consumption',
       'Stress_Level', 'Working_Hours_Per_Day', 'Sitting_Hours_Per_Day',
       'Outdoor_Time_Hours', 'Social_Interaction_Score', 'Resting_Heart_Rate',
       'Systolic_BP', 'Diastolic_BP', 'Cholesterol_Level', 'Blood_Sugar_Level',
       'Energy_Level_Score', 'Fatigue_Level_Score', 'Immune_Health_Score',
       'Mood_Score', 'Anxiety_Score', 'Productivity_Score',
       'Focus_Concentration_Score', 'Life_Satisfaction_Score', 'WT_cat',
       'ST_cat', 'Gender_Female', 'Gender_Male', 'Gender_Non-binary',
       'Country_Australia', 'Country_Brazil', 'Country_Canada',
       'Country_France', 'Country_Germany', 'Country_India', 'Country_Italy',
       'Country_Japan', 'Country_Mexico', 'Country_Nigeria',
       'Country_Pakistan', 'Country_South Korea', 'Country_Spain',
       'Country_UK', 'Country_USA', 'Occupation_Accountant',
       'Occupation_Artist', 'Occupation_Athlete', 'Occupation_Chef',
       'Occupation_Doctor', 'Occupation_Entrepreneur', 'Occupation_Freelancer',
       'Occupation_Laborer', 'Occupation_Lawyer', 'Occupation_Manager',
       'Occupation_Nurse', 'Occupation_Retired',
       'Occupation_Software Engineer', 'Occupation_Student',
       'Occupation_Teacher', 'Marital_Status_Divorced',
       'Marital_Status_Married', 'Marital_Status_Single',
       'Marital_Status_Widowed', 'Exercise_Type_Cycling', 'Exercise_Type_HIIT',
       'Exercise_Type_Running', 'Exercise_Type_Sports',
       'Exercise_Type_Swimming', 'Exercise_Type_Walking',
       'Exercise_Type_Weight Training', 'Exercise_Type_Yoga',
       'Morning_Workout_No', 'Morning_Workout_Yes', 'Meditation_Practice_No',
       'Meditation_Practice_Yes'],
      dtype='object')

In [36]:
cat_col = X_ohe.columns[X_ohe.nunique() <= 15]
cat_col.shape

(61,)

In [37]:
cont_col = X_ohe.columns[X_ohe.nunique() > 15]
cont_col.shape

(30,)

# Train test split

In [38]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X_ohe,Y,
                                                 test_size=0.3,
                                                 random_state=7,
                                                 stratify=Y)
X_train.shape,X_test.shape,Y_train.shape,Y_test.shape

((7000, 91), (3000, 91), (7000,), (3000,))

In [39]:
from sklearn.preprocessing import RobustScaler
rc= RobustScaler()
X_train[cont_col] = rc.fit_transform(X_train[cont_col])
X_test[cont_col] = rc.transform(X_test[cont_col])

# Outlier imputation using IQR method

In [40]:
def outlier_imputation_iqr(df,col):
  df1 = df.copy()
  q1,q3 = df1[col].quantile([0.25,0.75])
  iqr = q3-q1
  LB = q1 - 1.5*iqr
  UB = q3 + 1.5*iqr
  print("Column -->",col)
  df1.loc[(df1[col]<LB),col] = LB
  df1.loc[(df1[col]>UB),col] = UB
  print(LB,UB, df1[col].min(),df1[col].max())
  return df1

In [41]:
X_train_io = X_train.copy()
for col in cont_col:
  X_train_io = outlier_imputation_iqr(X_train_io,col)

Column --> Age
-1.9642857142857144 2.0357142857142856 -0.8928571428571429 1.3214285714285714
Column --> BMI
-2.0089153046062407 1.9910846953937595 -1.4257057949479945 1.9910846953937595
Column --> Sleep_Duration_Hours
-2.0033557046979866 1.9966442953020134 -2.0033557046979866 1.8523489932885902
Column --> Sleep_Quality_Score
-2.0 2.0 -2.0 1.7272727272727282
Column --> Weekend_Sleep_Difference_Hours
-2.0092592592592595 1.9907407407407407 -1.8888888888888888 1.9907407407407407
Column --> Screen_Time_Before_Bed_Hours
-1.8664122137404582 2.133587786259542 -0.618320610687023 2.133587786259542
Column --> Exercise_Duration_Minutes
-2.0 2.0 -1.6071428571428572 2.0
Column --> Daily_Steps
-2.025921583952065 1.9740784160479354 -1.9954409274456169 1.9740784160479354
Column --> Daily_Calorie_Intake
-1.9973230220107079 2.0026769779892923 -1.9973230220107079 2.0026769779892923
Column --> Water_Intake_Liters
-1.9999999999999996 2.0000000000000004 -1.9999999999999996 2.0000000000000004
Column --> Protein_Intake_Grams
-2.0116959064327484 1.9883040935672516 -1.97953216374269 1.9883040935672516
Column --> Breakfast_Regularity_Score
-2.0000000000000004 1.9999999999999996 -2.0000000000000004 1.0
Column --> Stress_Level
-2.0 2.0 -1.2499999999999998 1.9642857142857142
Column --> Working_Hours_Per_Day
-2.0 2.0 -2.0 2.0
Column --> Sitting_Hours_Per_Day
-1.9999999999999998 2.0 -1.9999999999999998 2.0
Column --> Outdoor_Time_Hours
-1.939153439153439 2.060846560846561 -1.3544973544973544 2.060846560846561
Column --> Social_Interaction_Score
-2.0 2.0 -1.7083333333333333 2.0
Column --> Resting_Heart_Rate
-2.0 2.0 -2.0 2.0
Column --> Systolic_BP
-2.0 2.0 -2.0 2.0
Column --> Diastolic_BP
-2.0 2.0 -2.0 2.0
Column --> Cholesterol_Level
-1.9952076677316297 2.0047923322683703 -1.9952076677316297 2.0047923322683703
Column --> Blood_Sugar_Level
-1.9976452119309256 2.0023547880690726 -1.9976452119309256 2.0023547880690726
Column --> Energy_Level_Score
-2.0 1.9999999999999998 -2.0 1.277777777777778
Column --> Fatigue_Level_Score
-1.9615384615384617 2.0384615384615383 -0.7307692307692308 2.0384615384615383
Column --> Immune_Health_Score
-1.9999999999999996 2.0000000000000004 -1.9999999999999996 2.0000000000000004
Column --> Mood_Score
-2.0294117647058822 1.9705882352941178 -2.0294117647058822 1.8823529411764715
Column --> Anxiety_Score
-2.0238095238095237 1.976190476190476 -1.9999999999999996 1.976190476190476
Column --> Productivity_Score
-1.9666666666666668 2.033333333333333 -1.9666666666666668 2.0
Column --> Focus_Concentration_Score
-2.0384615384615388 1.9615384615384612 -2.0384615384615388 1.9615384615384612
Column --> Life_Satisfaction_Score
-1.966666666666667 2.033333333333333 -1.966666666666667 1.733333333333334

# Feature Selection

## PCA

In [42]:
from sklearn.decomposition import PCA
pca = PCA(n_components=0.95,random_state=7)
X_train_pca = pca.fit_transform(X_train)
X_test_pca = pca.transform(X_test)
X_train_pca.shape, X_test_pca.shape

((7000, 43), (3000, 43))

In [43]:
pca = PCA(n_components=0.95,random_state=7)
X_train_io_pca = pca.fit_transform(X_train_io)
X_test_io_pca = pca.transform(X_test)
X_train_io_pca.shape, X_test_io_pca.shape

((7000, 43), (3000, 43))

## KERNEL PCA

In [44]:
from sklearn.decomposition import KernelPCA
kpca = KernelPCA(kernel='rbf',random_state=7)
X_train_kpca = kpca.fit_transform(X_train)
X_test_kpca = kpca.transform(X_test)
X_train_kpca.shape, X_test_kpca.shape

((7000, 6999), (3000, 6999))

In [45]:
kpca = KernelPCA(kernel='rbf',random_state=7)
X_train_io_kpca = kpca.fit_transform(X_train_io)
X_test_io_kpca = kpca.transform(X_test)
X_train_io_kpca.shape, X_test_io_kpca.shape

((7000, 6999), (3000, 6999))

## RFE

In [46]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
rfe = RFE(LogisticRegression(random_state=7,
                             class_weight="balanced"),
          verbose=2)
rfe.fit(X_train,Y_train)
rfe.ranking_

Fitting estimator with 91 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 90 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 89 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 88 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 87 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 86 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 85 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 84 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 83 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 82 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 81 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 80 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 79 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 78 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 77 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 76 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 75 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 74 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 73 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 72 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 71 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 70 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 69 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 68 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 67 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 66 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 65 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 64 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 63 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 62 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 61 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 60 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 59 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 58 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 57 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 56 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 55 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 54 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 53 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 52 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 51 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 50 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 49 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 48 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 47 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 46 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

array([ 1,  1, 37,  1, 42, 31, 32, 43,  1, 21,  1, 44,  1,  1, 24,  1, 13,
       45,  1, 38,  1,  8,  1, 27, 39, 41,  5, 28, 25, 26, 19, 10, 20, 36,
        1,  1, 11, 29, 40,  1, 47, 46,  1,  1,  1,  1, 18, 15, 17,  1,  1,
        1, 16, 30,  1,  1,  1, 23,  1,  1,  1,  1, 34,  3,  4,  1,  2,  1,
        6,  1,  1,  1,  1, 35,  9,  1, 12,  1, 14,  1,  1,  7, 33, 22,  1,
        1,  1,  1,  1,  1,  1])

In [47]:
selected_col = X_train.columns[rfe.ranking_ == 1]
selected_col.shape

(45,)

In [48]:
X_train_rfe = X_train.loc[:,selected_col]
X_test_rfe = X_test.loc[:,selected_col]

In [49]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
rfe = RFE(LogisticRegression(random_state=7,
                             class_weight="balanced"),
          verbose=2)
rfe.fit(X_train_io,Y_train)
rfe.ranking_

Fitting estimator with 91 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 90 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 89 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 88 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 87 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 86 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 85 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 84 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 83 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 82 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 81 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 80 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 79 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 78 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 77 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 76 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 75 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 74 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 73 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 72 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 71 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 70 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 69 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 68 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 67 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 66 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 65 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 64 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 63 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 62 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 61 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 60 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 59 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 58 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 57 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 56 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 55 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 54 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 53 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 52 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 51 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 50 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 49 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 48 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 47 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 46 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

array([ 1,  1, 37,  1, 43, 35, 36, 44,  1, 25,  1, 42,  1,  1, 28,  1,  9,
       45,  1, 38,  1,  8,  1, 22, 41, 33,  3, 31, 23, 24, 18, 10, 17, 32,
        1,  1, 15, 30, 40,  1, 47, 46,  1,  1,  4,  1, 27, 20, 16,  1,  1,
        1, 13, 34,  1,  1,  1, 26,  1, 11,  1,  1, 21,  1,  7,  1, 12,  1,
        6,  1,  1,  1,  1, 39, 14,  1,  1,  1,  1,  2,  1,  5, 29, 19,  1,
        1,  1,  1,  1,  1,  1])

In [50]:
selected_col = X_train_io.columns[rfe.ranking_ == 1]
selected_col.shape

(45,)

In [51]:
X_train_io_rfe = X_train_io.loc[:,selected_col]
X_test_io_rfe = X_test.loc[:,selected_col]

## Decision Tree

In [52]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(class_weight="balanced",
                            random_state=7)
dt.fit(X_train,Y_train)

DecisionTreeClassifier(class_weight='balanced', random_state=7)

In [53]:
selected_col = X_train.columns[dt.feature_importances_ >
                               dt.feature_importances_.mean()]
selected_col.shape

(20,)

In [54]:
X_train_dt = X_train.loc[:,selected_col]
X_test_dt = X_test.loc[:,selected_col]

In [55]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(class_weight="balanced",
                            random_state=7)
dt.fit(X_train_io,Y_train)

DecisionTreeClassifier(class_weight='balanced', random_state=7)

In [56]:
selected_col = X_train_io.columns[dt.feature_importances_ >
                               dt.feature_importances_.mean()]
selected_col.shape

(21,)

In [57]:
X_train_io_dt = X_train_io.loc[:,selected_col]
X_test_io_dt = X_test.loc[:,selected_col]

# Apply Models for Multi - Class Classification

 --> TO get the best model for your data and get the best prediction =
 models to select:
atleast 3
1) basic learning -- Like Logistic
--> Random Forest
1 out of XGBoost, CatBoost, Or LGBoost

best performing of the three is selected

# Apply models for multi class classification

Logistic Regression

---

CatBoost

---

RandomForest

---

LightGBM

--
apply on all datasets -- generate 40 different classification report fo each

# # Steps to be done:
1. take the model
2. train the model
3. get the predictions Y_predict and Y_pred_prob
4. Classification Report
5. log loss

# automation:
create a function that will take model,Xtrain,Ytrain,Ytest as a parameter and in turn return precision,recall,f1score log loss, average precision score.

run this function on diff datasets and models and store the list of lists

convert it to a dataframe

compare the results in the dataframe

PLot the results if possible!

In [58]:
data_list = [(X_train,X_test),(X_train_io,X_test),(X_train_pca,X_test_pca),(X_train_io_pca,X_test_io_pca),(X_train_kpca,X_test_kpca),
             (X_train_io_kpca,X_test_io_kpca),(X_train_rfe,X_test_rfe),(X_train_io_rfe,X_test_io_rfe),(X_train_dt,X_test_dt),(X_train_io_dt,X_test_io_dt)]
# All required training datasets for different feature selections

In [59]:
from sklearn.metrics import classification_report
c = 0
for XTrain,XTest in data_list:
  c += 1
  lr = LogisticRegression(random_state=7,class_weight='balanced')
  lr.fit(XTrain,Y_train)
  y_pred = lr.predict(XTest)
  print(f'Classification Report : {c} - {classification_report(Y_test,y_pred)}')

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Classification Report : 1 -               precision    recall  f1-score   support

           0       0.54      0.79      0.64        34
           1       0.80      0.83      0.81       641
           2       0.84      0.79      0.81      1329
           3       0.85      0.88      0.86       996

    accuracy                           0.83      3000
   macro avg       0.76      0.82      0.78      3000
weighted avg       0.83      0.83      0.83      3000

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Classification Report : 2 -               precision    recall  f1-score   support

           0       0.50      0.82      0.62        34
           1       0.80      0.83      0.81       641
           2       0.84      0.79      0.82      1329
           3       0.85      0.89      0.87       996

    accuracy                           0.83      3000
   macro avg       0.75      0.83      0.78      3000
weighted avg       0.83      0.83      0.83      3000

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Classification Report : 3 -               precision    recall  f1-score   support

           0       0.43      0.79      0.56        34
           1       0.79      0.81      0.80       641
           2       0.83      0.77      0.80      1329
           3       0.84      0.88      0.86       996

    accuracy                           0.82      3000
   macro avg       0.72      0.81      0.75      3000
weighted avg       0.82      0.82      0.82      3000

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Classification Report : 4 -               precision    recall  f1-score   support

           0       0.42      0.79      0.55        34
           1       0.79      0.81      0.80       641
           2       0.84      0.77      0.80      1329
           3       0.84      0.88      0.86       996

    accuracy                           0.82      3000
   macro avg       0.72      0.81      0.75      3000
weighted avg       0.82      0.82      0.82      3000

Classification Report : 5 -               precision    recall  f1-score   support

           0       0.50      0.76      0.60        34
           1       0.73      0.77      0.75       641
           2       0.79      0.72      0.75      1329
           3       0.81      0.86      0.84       996

    accuracy                           0.78      3000
   macro avg       0.71      0.78      0.74      3000
weighted avg       0.78      0.78      0.78      3000

Classification Report : 6 -               precision    recall  f1-score   support

           0       0.51      0.76      0.61        34
           1       0.73      0.77      0.75       641
           2       0.79      0.72      0.75      1329
           3       0.81      0.87      0.84       996

    accuracy                           0.78      3000
   macro avg       0.71      0.78      0.74      3000
weighted avg       0.78      0.78      0.78      3000

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Classification Report : 7 -               precision    recall  f1-score   support

           0       0.51      0.88      0.65        34
           1       0.80      0.83      0.82       641
           2       0.84      0.78      0.81      1329
           3       0.85      0.88      0.87       996

    accuracy                           0.83      3000
   macro avg       0.75      0.85      0.79      3000
weighted avg       0.83      0.83      0.83      3000

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Classification Report : 8 -               precision    recall  f1-score   support

           0       0.48      0.88      0.62        34
           1       0.80      0.83      0.81       641
           2       0.84      0.78      0.81      1329
           3       0.85      0.88      0.86       996

    accuracy                           0.83      3000
   macro avg       0.74      0.84      0.78      3000
weighted avg       0.83      0.83      0.83      3000

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Classification Report : 9 -               precision    recall  f1-score   support

           0       0.38      0.88      0.54        34
           1       0.76      0.79      0.77       641
           2       0.82      0.75      0.78      1329
           3       0.83      0.87      0.85       996

    accuracy                           0.80      3000
   macro avg       0.70      0.82      0.74      3000
weighted avg       0.81      0.80      0.80      3000

Classification Report : 10 -               precision    recall  f1-score   support

           0       0.40      0.85      0.54        34
           1       0.75      0.79      0.77       641
           2       0.82      0.75      0.78      1329
           3       0.83      0.87      0.85       996

    accuracy                           0.80      3000
   macro avg       0.70      0.82      0.74      3000
weighted avg       0.81      0.80      0.80      3000

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

For Random Forest Classifier

In [60]:
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestClassifier
c = 0
for XTrain,XTest in data_list:
  c += 1
  rf = RandomForestClassifier(class_weight='balanced',random_state=7,n_estimators=100)
  rf.fit(XTrain,Y_train)
  y_pred = rf.predict(XTest)
  print(f'Classification Report : {c} - {classification_report(Y_test,y_pred)}')

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Classification Report : 1 -               precision    recall  f1-score   support

           0       0.00      0.00      0.00        34
           1       0.81      0.55      0.65       641
           2       0.68      0.87      0.76      1329
           3       0.85      0.76      0.80       996

    accuracy                           0.75      3000
   macro avg       0.59      0.54      0.55      3000
weighted avg       0.76      0.75      0.74      3000

Classification Report : 2 -               precision    recall  f1-score   support

           0       1.00      0.03      0.06        34
           1       0.80      0.56      0.66       641
           2       0.69      0.86      0.77      1329
           3       0.86      0.76      0.81       996

    accuracy                           0.76      3000
   macro avg       0.84      0.55      0.57      3000
weighted avg       0.77      0.76      0.75      3000

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Classification Report : 3 -               precision    recall  f1-score   support

           0       0.00      0.00      0.00        34
           1       0.79      0.44      0.56       641
           2       0.65      0.87      0.75      1329
           3       0.85      0.73      0.79       996

    accuracy                           0.72      3000
   macro avg       0.57      0.51      0.52      3000
weighted avg       0.74      0.72      0.71      3000

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Classification Report : 4 -               precision    recall  f1-score   support

           0       0.00      0.00      0.00        34
           1       0.80      0.46      0.58       641
           2       0.65      0.88      0.75      1329
           3       0.86      0.71      0.78       996

    accuracy                           0.72      3000
   macro avg       0.58      0.51      0.53      3000
weighted avg       0.74      0.72      0.71      3000

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Classification Report : 5 -               precision    recall  f1-score   support

           0       0.00      0.00      0.00        34
           1       0.75      0.01      0.03       641
           2       0.50      0.87      0.63      1329
           3       0.68      0.46      0.55       996

    accuracy                           0.54      3000
   macro avg       0.48      0.34      0.30      3000
weighted avg       0.61      0.54      0.47      3000

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Classification Report : 6 -               precision    recall  f1-score   support

           0       0.00      0.00      0.00        34
           1       0.64      0.01      0.02       641
           2       0.50      0.87      0.64      1329
           3       0.71      0.49      0.58       996

    accuracy                           0.55      3000
   macro avg       0.46      0.34      0.31      3000
weighted avg       0.59      0.55      0.48      3000

Classification Report : 7 -               precision    recall  f1-score   support

           0       1.00      0.03      0.06        34
           1       0.81      0.62      0.70       641
           2       0.71      0.86      0.78      1329
           3       0.87      0.78      0.82       996

    accuracy                           0.78      3000
   macro avg       0.85      0.57      0.59      3000
weighted avg       0.79      0.78      0.77      3000

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Classification Report : 8 -               precision    recall  f1-score   support

           0       0.00      0.00      0.00        34
           1       0.83      0.60      0.70       641
           2       0.71      0.87      0.78      1329
           3       0.86      0.78      0.82       996

    accuracy                           0.77      3000
   macro avg       0.60      0.56      0.57      3000
weighted avg       0.78      0.77      0.77      3000

Classification Report : 9 -               precision    recall  f1-score   support

           0       0.83      0.15      0.25        34
           1       0.81      0.63      0.71       641
           2       0.72      0.85      0.78      1329
           3       0.85      0.79      0.82       996

    accuracy                           0.78      3000
   macro avg       0.80      0.61      0.64      3000
weighted avg       0.78      0.78      0.77      3000

Classification Report : 10 -               precision    recall  f1-score   support

           0       0.75      0.09      0.16        34
           1       0.80      0.62      0.70       641
           2       0.72      0.84      0.77      1329
           3       0.85      0.80      0.82       996

    accuracy                           0.77      3000
   macro avg       0.78      0.59      0.61      3000
weighted avg       0.78      0.77      0.77      3000

In [62]:
!pip install catboost

Collecting catboost
  Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.4)
Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl (97.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 6.7 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.10

In [63]:
from catboost import CatBoostClassifier

In [64]:
c = 0
for XTrain,XTest in data_list:
  c += 1
  cbc = CatBoostClassifier(iterations=50,learning_rate=0.5,depth=5,cat_features=None,loss_function='MultiClass',random_state=7)
  cbc.fit(XTrain,Y_train)
  y_pred = cbc.predict(XTest)
  print(f'Classification Report : {c} - {classification_report(Y_test,y_pred)}')

0:	learn: 1.0051672	total: 81.4ms	remaining: 3.99s
1:	learn: 0.8253709	total: 109ms	remaining: 2.61s
2:	learn: 0.7218339	total: 140ms	remaining: 2.19s
3:	learn: 0.6667324	total: 167ms	remaining: 1.93s
4:	learn: 0.6197175	total: 196ms	remaining: 1.76s
5:	learn: 0.5881995	total: 218ms	remaining: 1.6s
6:	learn: 0.5586230	total: 238ms	remaining: 1.46s
7:	learn: 0.5357815	total: 258ms	remaining: 1.35s
8:	learn: 0.5179448	total: 278ms	remaining: 1.26s
9:	learn: 0.5006852	total: 307ms	remaining: 1.23s
10:	learn: 0.4856634	total: 336ms	remaining: 1.19s
11:	learn: 0.4711568	total: 361ms	remaining: 1.14s
12:	learn: 0.4612380	total: 387ms	remaining: 1.1s
13:	learn: 0.4497093	total: 411ms	remaining: 1.06s
14:	learn: 0.4447636	total: 437ms	remaining: 1.02s
15:	learn: 0.4391059	total: 460ms	remaining: 978ms
16:	learn: 0.4286773	total: 484ms	remaining: 939ms
17:	learn: 0.4202179	total: 505ms	remaining: 898ms
18:	learn: 0.4161895	total: 531ms	remaining: 866ms
19:	learn: 0.4083983	total: 556ms	remaining: 835ms
20:	learn: 0.4012450	total: 583ms	remaining: 805ms
21:	learn: 0.3949017	total: 607ms	remaining: 772ms
22:	learn: 0.3912334	total: 633ms	remaining: 743ms
23:	learn: 0.3883198	total: 654ms	remaining: 709ms
24:	learn: 0.3853988	total: 673ms	remaining: 673ms
25:	learn: 0.3790754	total: 698ms	remaining: 644ms
26:	learn: 0.3757149	total: 721ms	remaining: 615ms
27:	learn: 0.3741139	total: 747ms	remaining: 587ms
28:	learn: 0.3722006	total: 768ms	remaining: 556ms
29:	learn: 0.3684897	total: 786ms	remaining: 524ms
30:	learn: 0.3651095	total: 805ms	remaining: 493ms
31:	learn: 0.3623981	total: 829ms	remaining: 466ms
32:	learn: 0.3604765	total: 856ms	remaining: 441ms
33:	learn: 0.3554702	total: 882ms	remaining: 415ms
34:	learn: 0.3535221	total: 905ms	remaining: 388ms
35:	learn: 0.3509360	total: 930ms	remaining: 362ms
36:	learn: 0.3474186	total: 958ms	remaining: 337ms
37:	learn: 0.3447399	total: 982ms	remaining: 310ms
38:	learn: 0.3393704	total: 1s	remaining: 283ms
39:	learn: 0.3362683	total: 1.02s	remaining: 255ms
40:	learn: 0.3335561	total: 1.04s	remaining: 228ms
41:	learn: 0.3299319	total: 1.06s	remaining: 203ms
42:	learn: 0.3274535	total: 1.09s	remaining: 178ms
43:	learn: 0.3236713	total: 1.11s	remaining: 152ms
44:	learn: 0.3200475	total: 1.13s	remaining: 126ms
45:	learn: 0.3187555	total: 1.16s	remaining: 101ms
46:	learn: 0.3167088	total: 1.18s	remaining: 75.3ms
47:	learn: 0.3148177	total: 1.2s	remaining: 50ms
48:	learn: 0.3127660	total: 1.23s	remaining: 25ms
49:	learn: 0.3108849	total: 1.25s	remaining: 0us
Classification Report : 1 -               precision    recall  f1-score   support

           0       0.75      0.44      0.56        34
           1       0.84      0.73      0.78       641
           2       0.77      0.84      0.81      1329
           3       0.86      0.84      0.85       996

    accuracy                           0.81      3000
   macro avg       0.81      0.71      0.75      3000
weighted avg       0.82      0.81      0.81      3000

0:	learn: 0.9695349	total: 31.2ms	remaining: 1.53s
1:	learn: 0.8091429	total: 57.6ms	remaining: 1.38s
2:	learn: 0.7217409	total: 85.8ms	remaining: 1.34s
3:	learn: 0.6694048	total: 114ms	remaining: 1.31s
4:	learn: 0.6150100	total: 144ms	remaining: 1.29s
5:	learn: 0.5840039	total: 167ms	remaining: 1.23s
6:	learn: 0.5616409	total: 193ms	remaining: 1.19s
7:	learn: 0.5436933	total: 218ms	remaining: 1.15s
8:	learn: 0.5227740	total: 241ms	remaining: 1.1s
9:	learn: 0.5072591	total: 268ms	remaining: 1.07s
10:	learn: 0.5005302	total: 293ms	remaining: 1.04s
11:	learn: 0.4910888	total: 317ms	remaining: 1s
12:	learn: 0.4772280	total: 342ms	remaining: 975ms
13:	learn: 0.4626064	total: 367ms	remaining: 944ms
14:	learn: 0.4559127	total: 391ms	remaining: 913ms
15:	learn: 0.4461254	total: 417ms	remaining: 886ms
16:	learn: 0.4380715	total: 444ms	remaining: 862ms
17:	learn: 0.4292411	total: 467ms	remaining: 831ms
18:	learn: 0.4267545	total: 495ms	remaining: 807ms
19:	learn: 0.4221647	total: 518ms	remaining: 778ms
20:	learn: 0.4163682	total: 543ms	remaining: 750ms
21:	learn: 0.4074425	total: 570ms	remaining: 725ms
22:	learn: 0.4022574	total: 595ms	remaining: 698ms
23:	learn: 0.3942043	total: 627ms	remaining: 680ms
24:	learn: 0.3886675	total: 667ms	remaining: 667ms
25:	learn: 0.3851167	total: 691ms	remaining: 638ms
26:	learn: 0.3805236	total: 715ms	remaining: 609ms
27:	learn: 0.3772654	total: 737ms	remaining: 579ms
28:	learn: 0.3718274	total: 763ms	remaining: 553ms
29:	learn: 0.3669291	total: 787ms	remaining: 525ms
30:	learn: 0.3636192	total: 812ms	remaining: 498ms
31:	learn: 0.3609986	total: 835ms	remaining: 470ms
32:	learn: 0.3558702	total: 862ms	remaining: 444ms
33:	learn: 0.3509778	total: 889ms	remaining: 418ms
34:	learn: 0.3486511	total: 910ms	remaining: 390ms
35:	learn: 0.3452515	total: 929ms	remaining: 361ms
36:	learn: 0.3418764	total: 952ms	remaining: 335ms
37:	learn: 0.3390632	total: 973ms	remaining: 307ms
38:	learn: 0.3352683	total: 993ms	remaining: 280ms
39:	learn: 0.3323194	total: 1.02s	remaining: 255ms
40:	learn: 0.3305552	total: 1.04s	remaining: 229ms
41:	learn: 0.3282913	total: 1.07s	remaining: 203ms
42:	learn: 0.3259003	total: 1.09s	remaining: 177ms
43:	learn: 0.3229242	total: 1.12s	remaining: 152ms
44:	learn: 0.3182336	total: 1.14s	remaining: 127ms
45:	learn: 0.3149837	total: 1.17s	remaining: 102ms
46:	learn: 0.3133293	total: 1.19s	remaining: 76.1ms
47:	learn: 0.3093893	total: 1.22s	remaining: 50.7ms
48:	learn: 0.3063135	total: 1.24s	remaining: 25.3ms
49:	learn: 0.3046478	total: 1.26s	remaining: 0us
Classification Report : 2 -               precision    recall  f1-score   support

           0       0.72      0.38      0.50        34
           1       0.84      0.72      0.78       641
           2       0.78      0.85      0.81      1329
           3       0.87      0.84      0.85       996

    accuracy                           0.82      3000
   macro avg       0.80      0.70      0.74      3000
weighted avg       0.82      0.82      0.81      3000

0:	learn: 1.0228323	total: 56.4ms	remaining: 2.77s
1:	learn: 0.8564022	total: 90.2ms	remaining: 2.16s
2:	learn: 0.7845008	total: 122ms	remaining: 1.91s
3:	learn: 0.7284731	total: 168ms	remaining: 1.93s
4:	learn: 0.6901190	total: 211ms	remaining: 1.9s
5:	learn: 0.6534004	total: 254ms	remaining: 1.86s
6:	learn: 0.6271477	total: 295ms	remaining: 1.81s
7:	learn: 0.6080839	total: 337ms	remaining: 1.77s
8:	learn: 0.5962262	total: 379ms	remaining: 1.73s
9:	learn: 0.5835529	total: 426ms	remaining: 1.7s
10:	learn: 0.5706479	total: 463ms	remaining: 1.64s
11:	learn: 0.5611924	total: 499ms	remaining: 1.58s
12:	learn: 0.5524762	total: 538ms	remaining: 1.53s
13:	learn: 0.5426713	total: 583ms	remaining: 1.5s
14:	learn: 0.5367195	total: 628ms	remaining: 1.46s
15:	learn: 0.5240606	total: 671ms	remaining: 1.43s
16:	learn: 0.5115557	total: 704ms	remaining: 1.37s
17:	learn: 0.5059325	total: 738ms	remaining: 1.31s
18:	learn: 0.5010567	total: 781ms	remaining: 1.27s
19:	learn: 0.4959920	total: 831ms	remaining: 1.25s
20:	learn: 0.4904952	total: 874ms	remaining: 1.21s
21:	learn: 0.4847406	total: 911ms	remaining: 1.16s
22:	learn: 0.4766647	total: 940ms	remaining: 1.1s
23:	learn: 0.4674877	total: 975ms	remaining: 1.06s
24:	learn: 0.4617776	total: 1.02s	remaining: 1.02s
25:	learn: 0.4547255	total: 1.05s	remaining: 971ms
26:	learn: 0.4501083	total: 1.09s	remaining: 928ms
27:	learn: 0.4466277	total: 1.13s	remaining: 891ms
28:	learn: 0.4429123	total: 1.17s	remaining: 851ms
29:	learn: 0.4357482	total: 1.22s	remaining: 815ms
30:	learn: 0.4329576	total: 1.27s	remaining: 780ms
31:	learn: 0.4294494	total: 1.31s	remaining: 740ms
32:	learn: 0.4248715	total: 1.36s	remaining: 700ms
33:	learn: 0.4186088	total: 1.4s	remaining: 659ms
34:	learn: 0.4163697	total: 1.44s	remaining: 618ms
35:	learn: 0.4124175	total: 1.48s	remaining: 577ms
36:	learn: 0.4039708	total: 1.53s	remaining: 537ms
37:	learn: 0.4006472	total: 1.57s	remaining: 495ms
38:	learn: 0.3956202	total: 1.61s	remaining: 453ms
39:	learn: 0.3938433	total: 1.65s	remaining: 412ms
40:	learn: 0.3921493	total: 1.69s	remaining: 372ms
41:	learn: 0.3898754	total: 1.74s	remaining: 331ms
42:	learn: 0.3871673	total: 1.78s	remaining: 290ms
43:	learn: 0.3845442	total: 1.82s	remaining: 249ms
44:	learn: 0.3828192	total: 1.85s	remaining: 206ms
45:	learn: 0.3798883	total: 1.9s	remaining: 165ms
46:	learn: 0.3766677	total: 1.94s	remaining: 124ms
47:	learn: 0.3730254	total: 1.98s	remaining: 82.6ms
48:	learn: 0.3699259	total: 2.02s	remaining: 41.3ms
49:	learn: 0.3669140	total: 2.07s	remaining: 0us
Classification Report : 3 -               precision    recall  f1-score   support

           0       0.88      0.21      0.33        34
           1       0.79      0.67      0.72       641
           2       0.73      0.82      0.77      1329
           3       0.84      0.81      0.82       996

    accuracy                           0.78      3000
   macro avg       0.81      0.62      0.66      3000
weighted avg       0.78      0.78      0.77      3000

0:	learn: 1.0255488	total: 56.8ms	remaining: 2.78s
1:	learn: 0.8708196	total: 102ms	remaining: 2.46s
2:	learn: 0.7858731	total: 150ms	remaining: 2.36s
3:	learn: 0.7324741	total: 197ms	remaining: 2.26s
4:	learn: 0.7010302	total: 241ms	remaining: 2.17s
5:	learn: 0.6724306	total: 276ms	remaining: 2.02s
6:	learn: 0.6439947	total: 309ms	remaining: 1.9s
7:	learn: 0.6287539	total: 341ms	remaining: 1.79s
8:	learn: 0.6203229	total: 375ms	remaining: 1.71s
9:	learn: 0.6023707	total: 422ms	remaining: 1.69s
10:	learn: 0.5919034	total: 457ms	remaining: 1.62s
11:	learn: 0.5787866	total: 490ms	remaining: 1.55s
12:	learn: 0.5651050	total: 534ms	remaining: 1.52s
13:	learn: 0.5561996	total: 573ms	remaining: 1.47s
14:	learn: 0.5488863	total: 607ms	remaining: 1.42s
15:	learn: 0.5346906	total: 652ms	remaining: 1.39s
16:	learn: 0.5257837	total: 692ms	remaining: 1.34s
17:	learn: 0.5196244	total: 732ms	remaining: 1.3s
18:	learn: 0.5140187	total: 775ms	remaining: 1.26s
19:	learn: 0.5046833	total: 819ms	remaining: 1.23s
20:	learn: 0.4925778	total: 858ms	remaining: 1.18s
21:	learn: 0.4847849	total: 892ms	remaining: 1.14s
22:	learn: 0.4786167	total: 933ms	remaining: 1.09s
23:	learn: 0.4741139	total: 972ms	remaining: 1.05s
24:	learn: 0.4674363	total: 1.01s	remaining: 1.01s
25:	learn: 0.4624981	total: 1.05s	remaining: 969ms
26:	learn: 0.4561756	total: 1.09s	remaining: 932ms
27:	learn: 0.4514365	total: 1.15s	remaining: 902ms
28:	learn: 0.4460834	total: 1.19s	remaining: 864ms
29:	learn: 0.4418681	total: 1.24s	remaining: 823ms
30:	learn: 0.4390847	total: 1.28s	remaining: 782ms
31:	learn: 0.4345081	total: 1.32s	remaining: 743ms
32:	learn: 0.4327574	total: 1.36s	remaining: 702ms
33:	learn: 0.4280265	total: 1.41s	remaining: 662ms
34:	learn: 0.4258739	total: 1.45s	remaining: 621ms
35:	learn: 0.4215938	total: 1.49s	remaining: 580ms
36:	learn: 0.4167766	total: 1.52s	remaining: 536ms
37:	learn: 0.4102277	total: 1.56s	remaining: 493ms
38:	learn: 0.4040797	total: 1.61s	remaining: 454ms
39:	learn: 0.4012542	total: 1.66s	remaining: 416ms
40:	learn: 0.3992261	total: 1.72s	remaining: 377ms
41:	learn: 0.3951288	total: 1.78s	remaining: 338ms
42:	learn: 0.3909831	total: 1.84s	remaining: 299ms
43:	learn: 0.3873263	total: 1.91s	remaining: 260ms
44:	learn: 0.3827507	total: 1.97s	remaining: 219ms
45:	learn: 0.3812878	total: 2.04s	remaining: 177ms
46:	learn: 0.3767411	total: 2.11s	remaining: 135ms
47:	learn: 0.3744409	total: 2.18s	remaining: 91ms
48:	learn: 0.3705075	total: 2.26s	remaining: 46.1ms
49:	learn: 0.3677768	total: 2.3s	remaining: 0us
Classification Report : 4 -               precision    recall  f1-score   support

           0       0.86      0.18      0.29        34
           1       0.80      0.67      0.73       641
           2       0.73      0.83      0.78      1329
           3       0.85      0.80      0.82       996

    accuracy                           0.78      3000
   macro avg       0.81      0.62      0.66      3000
weighted avg       0.79      0.78      0.78      3000

0:	learn: 1.0937864	total: 9.67s	remaining: 7m 53s
1:	learn: 0.9427206	total: 14.6s	remaining: 5m 50s
2:	learn: 0.8626954	total: 22.1s	remaining: 5m 46s
3:	learn: 0.8209730	total: 27.7s	remaining: 5m 18s
4:	learn: 0.8009413	total: 34.1s	remaining: 5m 7s
5:	learn: 0.7931767	total: 40.7s	remaining: 4m 58s
6:	learn: 0.7750668	total: 48.1s	remaining: 4m 55s
7:	learn: 0.7585076	total: 53.8s	remaining: 4m 42s
8:	learn: 0.7328433	total: 1m	remaining: 4m 36s
9:	learn: 0.7181069	total: 1m 4s	remaining: 4m 19s
10:	learn: 0.7076877	total: 1m 8s	remaining: 4m 1s
11:	learn: 0.6984515	total: 1m 12s	remaining: 3m 49s
12:	learn: 0.6885589	total: 1m 16s	remaining: 3m 36s
13:	learn: 0.6815486	total: 1m 19s	remaining: 3m 24s
14:	learn: 0.6729603	total: 1m 22s	remaining: 3m 13s
15:	learn: 0.6635136	total: 1m 27s	remaining: 3m 5s
16:	learn: 0.6573861	total: 1m 30s	remaining: 2m 56s
17:	learn: 0.6485499	total: 1m 34s	remaining: 2m 47s
18:	learn: 0.6298409	total: 1m 37s	remaining: 2m 39s
19:	learn: 0.6234418	total: 1m 41s	remaining: 2m 32s
20:	learn: 0.6114626	total: 1m 45s	remaining: 2m 25s
21:	learn: 0.6003911	total: 1m 48s	remaining: 2m 17s
22:	learn: 0.5885224	total: 1m 52s	remaining: 2m 12s
23:	learn: 0.5784150	total: 1m 56s	remaining: 2m 5s
24:	learn: 0.5653208	total: 1m 59s	remaining: 1m 59s
25:	learn: 0.5606316	total: 2m 2s	remaining: 1m 53s
26:	learn: 0.5565924	total: 2m 7s	remaining: 1m 48s
27:	learn: 0.5510673	total: 2m 11s	remaining: 1m 43s
28:	learn: 0.5451740	total: 2m 14s	remaining: 1m 37s
29:	learn: 0.5380524	total: 2m 18s	remaining: 1m 32s
30:	learn: 0.5338369	total: 2m 22s	remaining: 1m 27s
31:	learn: 0.5289307	total: 2m 25s	remaining: 1m 21s
32:	learn: 0.5231480	total: 2m 28s	remaining: 1m 16s
33:	learn: 0.5192581	total: 2m 34s	remaining: 1m 12s
34:	learn: 0.5142598	total: 2m 37s	remaining: 1m 7s
35:	learn: 0.5077216	total: 2m 41s	remaining: 1m 2s
36:	learn: 0.4996107	total: 2m 45s	remaining: 58.1s
37:	learn: 0.4940746	total: 2m 48s	remaining: 53.2s
38:	learn: 0.4879597	total: 2m 51s	remaining: 48.5s
39:	learn: 0.4848372	total: 2m 54s	remaining: 43.7s
40:	learn: 0.4808409	total: 2m 59s	remaining: 39.3s
41:	learn: 0.4757818	total: 3m 2s	remaining: 34.7s
42:	learn: 0.4715099	total: 3m 5s	remaining: 30.2s
43:	learn: 0.4658088	total: 3m 8s	remaining: 25.7s
44:	learn: 0.4621203	total: 3m 12s	remaining: 21.4s
45:	learn: 0.4582897	total: 3m 16s	remaining: 17.1s
46:	learn: 0.4539275	total: 3m 19s	remaining: 12.7s
47:	learn: 0.4509437	total: 3m 23s	remaining: 8.47s
48:	learn: 0.4462933	total: 3m 27s	remaining: 4.23s
49:	learn: 0.4416139	total: 3m 30s	remaining: 0us

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Classification Report : 5 -               precision    recall  f1-score   support

           0       0.00      0.00      0.00        34
           1       0.71      0.51      0.59       641
           2       0.65      0.78      0.71      1329
           3       0.79      0.75      0.77       996

    accuracy                           0.70      3000
   macro avg       0.54      0.51      0.52      3000
weighted avg       0.70      0.70      0.70      3000

0:	learn: 1.0928155	total: 4.99s	remaining: 4m 4s
1:	learn: 0.9430689	total: 8.16s	remaining: 3m 15s
2:	learn: 0.8767858	total: 11.8s	remaining: 3m 5s
3:	learn: 0.8320909	total: 18.3s	remaining: 3m 30s
4:	learn: 0.8116582	total: 21.7s	remaining: 3m 15s
5:	learn: 0.7886050	total: 25s	remaining: 3m 3s
6:	learn: 0.7615140	total: 29.8s	remaining: 3m 3s
7:	learn: 0.7448127	total: 33.1s	remaining: 2m 53s
8:	learn: 0.7353753	total: 36.3s	remaining: 2m 45s
9:	learn: 0.7209116	total: 39.6s	remaining: 2m 38s
10:	learn: 0.7098034	total: 44.1s	remaining: 2m 36s
11:	learn: 0.6916082	total: 47.4s	remaining: 2m 29s
12:	learn: 0.6745314	total: 50.7s	remaining: 2m 24s
13:	learn: 0.6703503	total: 55.1s	remaining: 2m 21s
14:	learn: 0.6593171	total: 58.6s	remaining: 2m 16s
15:	learn: 0.6522151	total: 1m 1s	remaining: 2m 11s
16:	learn: 0.6390367	total: 1m 4s	remaining: 2m 5s
17:	learn: 0.6296306	total: 1m 9s	remaining: 2m 3s
18:	learn: 0.6240676	total: 1m 12s	remaining: 1m 58s
19:	learn: 0.6128827	total: 1m 15s	remaining: 1m 53s
20:	learn: 0.5999795	total: 1m 19s	remaining: 1m 49s
21:	learn: 0.5903895	total: 1m 23s	remaining: 1m 46s
22:	learn: 0.5837824	total: 1m 26s	remaining: 1m 41s
23:	learn: 0.5787614	total: 1m 30s	remaining: 1m 37s
24:	learn: 0.5689193	total: 1m 34s	remaining: 1m 34s
25:	learn: 0.5633964	total: 1m 37s	remaining: 1m 30s
26:	learn: 0.5576229	total: 1m 41s	remaining: 1m 26s
27:	learn: 0.5523174	total: 1m 44s	remaining: 1m 22s
28:	learn: 0.5486936	total: 1m 48s	remaining: 1m 18s
29:	learn: 0.5437380	total: 1m 52s	remaining: 1m 14s
30:	learn: 0.5379514	total: 1m 55s	remaining: 1m 10s
31:	learn: 0.5290652	total: 1m 58s	remaining: 1m 6s
32:	learn: 0.5216397	total: 2m 3s	remaining: 1m 3s
33:	learn: 0.5175224	total: 2m 7s	remaining: 59.8s
34:	learn: 0.5110080	total: 2m 10s	remaining: 55.8s
35:	learn: 0.5052529	total: 2m 14s	remaining: 52.4s
36:	learn: 0.5020123	total: 2m 17s	remaining: 48.5s
37:	learn: 0.4987873	total: 2m 21s	remaining: 44.6s
38:	learn: 0.4946818	total: 2m 24s	remaining: 40.7s
39:	learn: 0.4894879	total: 2m 28s	remaining: 37.2s
40:	learn: 0.4842691	total: 2m 31s	remaining: 33.4s
41:	learn: 0.4761728	total: 2m 35s	remaining: 29.6s
42:	learn: 0.4718588	total: 2m 39s	remaining: 25.9s
43:	learn: 0.4691772	total: 2m 43s	remaining: 22.2s
44:	learn: 0.4628675	total: 2m 46s	remaining: 18.5s
45:	learn: 0.4590986	total: 2m 49s	remaining: 14.8s
46:	learn: 0.4557581	total: 2m 53s	remaining: 11.1s
47:	learn: 0.4536068	total: 2m 57s	remaining: 7.39s
48:	learn: 0.4504637	total: 3m	remaining: 3.68s
49:	learn: 0.4464299	total: 3m 3s	remaining: 0us

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Classification Report : 6 -               precision    recall  f1-score   support

           0       0.00      0.00      0.00        34
           1       0.75      0.51      0.60       641
           2       0.65      0.77      0.71      1329
           3       0.77      0.76      0.76       996

    accuracy                           0.70      3000
   macro avg       0.54      0.51      0.52      3000
weighted avg       0.70      0.70      0.70      3000

0:	learn: 0.9841530	total: 15.2ms	remaining: 744ms
1:	learn: 0.8246204	total: 28.6ms	remaining: 686ms
2:	learn: 0.7207496	total: 40.2ms	remaining: 630ms
3:	learn: 0.6506405	total: 51.6ms	remaining: 594ms
4:	learn: 0.6136226	total: 60.6ms	remaining: 546ms
5:	learn: 0.5763721	total: 71.3ms	remaining: 523ms
6:	learn: 0.5448228	total: 83.9ms	remaining: 515ms
7:	learn: 0.5228705	total: 96.9ms	remaining: 509ms
8:	learn: 0.5020794	total: 109ms	remaining: 496ms
9:	learn: 0.4921313	total: 121ms	remaining: 482ms
10:	learn: 0.4795856	total: 133ms	remaining: 472ms
11:	learn: 0.4685550	total: 147ms	remaining: 466ms
12:	learn: 0.4578565	total: 160ms	remaining: 454ms
13:	learn: 0.4506205	total: 173ms	remaining: 445ms
14:	learn: 0.4407366	total: 186ms	remaining: 434ms
15:	learn: 0.4325904	total: 200ms	remaining: 424ms
16:	learn: 0.4257006	total: 212ms	remaining: 412ms
17:	learn: 0.4181660	total: 224ms	remaining: 398ms
18:	learn: 0.4115925	total: 238ms	remaining: 388ms
19:	learn: 0.4034216	total: 251ms	remaining: 376ms
20:	learn: 0.3988615	total: 263ms	remaining: 363ms
21:	learn: 0.3956638	total: 275ms	remaining: 350ms
22:	learn: 0.3915452	total: 288ms	remaining: 338ms
23:	learn: 0.3874216	total: 300ms	remaining: 325ms
24:	learn: 0.3820306	total: 313ms	remaining: 313ms
25:	learn: 0.3784584	total: 325ms	remaining: 300ms
26:	learn: 0.3731022	total: 338ms	remaining: 288ms
27:	learn: 0.3697151	total: 351ms	remaining: 276ms
28:	learn: 0.3646641	total: 363ms	remaining: 263ms
29:	learn: 0.3621888	total: 375ms	remaining: 250ms
30:	learn: 0.3594667	total: 388ms	remaining: 238ms
31:	learn: 0.3566907	total: 400ms	remaining: 225ms
32:	learn: 0.3530295	total: 414ms	remaining: 213ms
33:	learn: 0.3494831	total: 426ms	remaining: 200ms
34:	learn: 0.3475139	total: 439ms	remaining: 188ms
35:	learn: 0.3448307	total: 454ms	remaining: 177ms
36:	learn: 0.3423476	total: 470ms	remaining: 165ms
37:	learn: 0.3380350	total: 483ms	remaining: 152ms
38:	learn: 0.3360070	total: 495ms	remaining: 140ms
39:	learn: 0.3330211	total: 508ms	remaining: 127ms
40:	learn: 0.3296313	total: 521ms	remaining: 114ms
41:	learn: 0.3287887	total: 532ms	remaining: 101ms
42:	learn: 0.3265915	total: 547ms	remaining: 89.1ms
43:	learn: 0.3246235	total: 559ms	remaining: 76.3ms
44:	learn: 0.3227654	total: 572ms	remaining: 63.5ms
45:	learn: 0.3203614	total: 584ms	remaining: 50.8ms
46:	learn: 0.3185201	total: 597ms	remaining: 38.1ms
47:	learn: 0.3172043	total: 610ms	remaining: 25.4ms
48:	learn: 0.3158344	total: 622ms	remaining: 12.7ms
49:	learn: 0.3138938	total: 634ms	remaining: 0us
Classification Report : 7 -               precision    recall  f1-score   support

           0       0.89      0.50      0.64        34
           1       0.86      0.77      0.81       641
           2       0.80      0.87      0.83      1329
           3       0.89      0.85      0.87       996

    accuracy                           0.84      3000
   macro avg       0.86      0.75      0.79      3000
weighted avg       0.84      0.84      0.84      3000

0:	learn: 0.9836710	total: 13.6ms	remaining: 668ms
1:	learn: 0.8215234	total: 26ms	remaining: 624ms
2:	learn: 0.7187157	total: 38.1ms	remaining: 597ms
3:	learn: 0.6549186	total: 50.3ms	remaining: 578ms
4:	learn: 0.6080541	total: 62.6ms	remaining: 563ms
5:	learn: 0.5755532	total: 73.8ms	remaining: 541ms
6:	learn: 0.5488049	total: 86.7ms	remaining: 533ms
7:	learn: 0.5253983	total: 98.3ms	remaining: 516ms
8:	learn: 0.5129579	total: 110ms	remaining: 499ms
9:	learn: 0.4975046	total: 122ms	remaining: 487ms
10:	learn: 0.4840079	total: 133ms	remaining: 472ms
11:	learn: 0.4711185	total: 145ms	remaining: 459ms
12:	learn: 0.4630928	total: 156ms	remaining: 445ms
13:	learn: 0.4562767	total: 168ms	remaining: 432ms
14:	learn: 0.4474046	total: 179ms	remaining: 418ms
15:	learn: 0.4380650	total: 191ms	remaining: 406ms
16:	learn: 0.4300774	total: 203ms	remaining: 393ms
17:	learn: 0.4224206	total: 213ms	remaining: 380ms
18:	learn: 0.4145005	total: 225ms	remaining: 368ms
19:	learn: 0.4069614	total: 237ms	remaining: 356ms
20:	learn: 0.4045442	total: 248ms	remaining: 343ms
21:	learn: 0.3971351	total: 259ms	remaining: 330ms
22:	learn: 0.3909706	total: 271ms	remaining: 318ms
23:	learn: 0.3882183	total: 282ms	remaining: 305ms
24:	learn: 0.3834508	total: 295ms	remaining: 295ms
25:	learn: 0.3777933	total: 305ms	remaining: 282ms
26:	learn: 0.3731228	total: 316ms	remaining: 270ms
27:	learn: 0.3658803	total: 328ms	remaining: 258ms
28:	learn: 0.3633475	total: 340ms	remaining: 246ms
29:	learn: 0.3604389	total: 352ms	remaining: 234ms
30:	learn: 0.3572204	total: 363ms	remaining: 223ms
31:	learn: 0.3533746	total: 375ms	remaining: 211ms
32:	learn: 0.3491771	total: 386ms	remaining: 199ms
33:	learn: 0.3476260	total: 396ms	remaining: 186ms
34:	learn: 0.3456542	total: 408ms	remaining: 175ms
35:	learn: 0.3434416	total: 417ms	remaining: 162ms
36:	learn: 0.3396225	total: 426ms	remaining: 150ms
37:	learn: 0.3367236	total: 439ms	remaining: 139ms
38:	learn: 0.3339774	total: 450ms	remaining: 127ms
39:	learn: 0.3306156	total: 464ms	remaining: 116ms
40:	learn: 0.3262447	total: 476ms	remaining: 105ms
41:	learn: 0.3248246	total: 487ms	remaining: 92.7ms
42:	learn: 0.3234291	total: 497ms	remaining: 80.9ms
43:	learn: 0.3211237	total: 508ms	remaining: 69.3ms
44:	learn: 0.3198020	total: 519ms	remaining: 57.7ms
45:	learn: 0.3173700	total: 529ms	remaining: 46ms
46:	learn: 0.3144673	total: 541ms	remaining: 34.5ms
47:	learn: 0.3126265	total: 552ms	remaining: 23ms
48:	learn: 0.3108027	total: 563ms	remaining: 11.5ms
49:	learn: 0.3084329	total: 574ms	remaining: 0us
Classification Report : 8 -               precision    recall  f1-score   support

           0       0.74      0.41      0.53        34
           1       0.85      0.75      0.80       641
           2       0.79      0.87      0.83      1329
           3       0.89      0.85      0.87       996

    accuracy                           0.83      3000
   macro avg       0.82      0.72      0.76      3000
weighted avg       0.83      0.83      0.83      3000

0:	learn: 1.0176030	total: 19.6ms	remaining: 960ms
1:	learn: 0.8427780	total: 39.4ms	remaining: 946ms
2:	learn: 0.7390701	total: 56.2ms	remaining: 881ms
3:	learn: 0.6847932	total: 71.4ms	remaining: 822ms
4:	learn: 0.6277152	total: 86.4ms	remaining: 777ms
5:	learn: 0.5922636	total: 99.8ms	remaining: 732ms
6:	learn: 0.5649044	total: 115ms	remaining: 708ms
7:	learn: 0.5480439	total: 129ms	remaining: 675ms
8:	learn: 0.5245159	total: 142ms	remaining: 648ms
9:	learn: 0.5092747	total: 155ms	remaining: 621ms
10:	learn: 0.4981609	total: 169ms	remaining: 599ms
11:	learn: 0.4836342	total: 184ms	remaining: 581ms
12:	learn: 0.4727395	total: 199ms	remaining: 567ms
13:	learn: 0.4631681	total: 213ms	remaining: 547ms
14:	learn: 0.4534214	total: 234ms	remaining: 546ms
15:	learn: 0.4440710	total: 260ms	remaining: 553ms
16:	learn: 0.4375503	total: 281ms	remaining: 545ms
17:	learn: 0.4335434	total: 303ms	remaining: 538ms
18:	learn: 0.4277222	total: 318ms	remaining: 519ms
19:	learn: 0.4224092	total: 332ms	remaining: 498ms
20:	learn: 0.4191809	total: 345ms	remaining: 477ms
21:	learn: 0.4144280	total: 359ms	remaining: 457ms
22:	learn: 0.4101682	total: 373ms	remaining: 438ms
23:	learn: 0.4057785	total: 386ms	remaining: 418ms
24:	learn: 0.4021120	total: 400ms	remaining: 400ms
25:	learn: 0.3995573	total: 414ms	remaining: 382ms
26:	learn: 0.3980580	total: 427ms	remaining: 364ms
27:	learn: 0.3948193	total: 442ms	remaining: 348ms
28:	learn: 0.3923287	total: 458ms	remaining: 332ms
29:	learn: 0.3878095	total: 472ms	remaining: 314ms
30:	learn: 0.3844973	total: 486ms	remaining: 298ms
31:	learn: 0.3807570	total: 500ms	remaining: 281ms
32:	learn: 0.3780286	total: 514ms	remaining: 265ms
33:	learn: 0.3745254	total: 531ms	remaining: 250ms
34:	learn: 0.3717249	total: 545ms	remaining: 233ms
35:	learn: 0.3670521	total: 559ms	remaining: 217ms
36:	learn: 0.3648393	total: 572ms	remaining: 201ms
37:	learn: 0.3609612	total: 588ms	remaining: 186ms
38:	learn: 0.3595696	total: 603ms	remaining: 170ms
39:	learn: 0.3575988	total: 617ms	remaining: 154ms
40:	learn: 0.3555692	total: 631ms	remaining: 138ms
41:	learn: 0.3528571	total: 650ms	remaining: 124ms
42:	learn: 0.3509662	total: 665ms	remaining: 108ms
43:	learn: 0.3489587	total: 677ms	remaining: 92.3ms
44:	learn: 0.3465403	total: 688ms	remaining: 76.5ms
45:	learn: 0.3453670	total: 699ms	remaining: 60.8ms
46:	learn: 0.3439448	total: 712ms	remaining: 45.4ms
47:	learn: 0.3410048	total: 724ms	remaining: 30.2ms
48:	learn: 0.3383805	total: 737ms	remaining: 15ms
49:	learn: 0.3356111	total: 752ms	remaining: 0us
Classification Report : 9 -               precision    recall  f1-score   support

           0       0.65      0.44      0.53        34
           1       0.81      0.72      0.76       641
           2       0.76      0.83      0.80      1329
           3       0.86      0.83      0.85       996

    accuracy                           0.80      3000
   macro avg       0.77      0.71      0.73      3000
weighted avg       0.81      0.80      0.80      3000

0:	learn: 0.9996582	total: 20.1ms	remaining: 985ms
1:	learn: 0.8270622	total: 34.4ms	remaining: 826ms
2:	learn: 0.7339636	total: 47.7ms	remaining: 748ms
3:	learn: 0.6666304	total: 64.2ms	remaining: 738ms
4:	learn: 0.6248511	total: 78.1ms	remaining: 703ms
5:	learn: 0.5999845	total: 92.6ms	remaining: 679ms
6:	learn: 0.5657771	total: 107ms	remaining: 659ms
7:	learn: 0.5484115	total: 122ms	remaining: 643ms
8:	learn: 0.5308128	total: 136ms	remaining: 621ms
9:	learn: 0.5090171	total: 151ms	remaining: 606ms
10:	learn: 0.4896816	total: 163ms	remaining: 578ms
11:	learn: 0.4863120	total: 176ms	remaining: 557ms
12:	learn: 0.4783059	total: 192ms	remaining: 546ms
13:	learn: 0.4688715	total: 205ms	remaining: 528ms
14:	learn: 0.4600691	total: 221ms	remaining: 516ms
15:	learn: 0.4502895	total: 239ms	remaining: 507ms
16:	learn: 0.4430489	total: 255ms	remaining: 494ms
17:	learn: 0.4360861	total: 270ms	remaining: 479ms
18:	learn: 0.4320006	total: 284ms	remaining: 463ms
19:	learn: 0.4259069	total: 299ms	remaining: 448ms
20:	learn: 0.4213915	total: 313ms	remaining: 432ms
21:	learn: 0.4158746	total: 328ms	remaining: 418ms
22:	learn: 0.4086956	total: 343ms	remaining: 403ms
23:	learn: 0.4049246	total: 358ms	remaining: 388ms
24:	learn: 0.4008003	total: 373ms	remaining: 373ms
25:	learn: 0.3964282	total: 388ms	remaining: 358ms
26:	learn: 0.3917488	total: 403ms	remaining: 343ms
27:	learn: 0.3874543	total: 418ms	remaining: 328ms
28:	learn: 0.3847182	total: 432ms	remaining: 313ms
29:	learn: 0.3829429	total: 448ms	remaining: 298ms
30:	learn: 0.3795390	total: 463ms	remaining: 284ms
31:	learn: 0.3774687	total: 477ms	remaining: 268ms
32:	learn: 0.3754323	total: 491ms	remaining: 253ms
33:	learn: 0.3726128	total: 507ms	remaining: 239ms
34:	learn: 0.3700483	total: 522ms	remaining: 224ms
35:	learn: 0.3676331	total: 539ms	remaining: 210ms
36:	learn: 0.3656697	total: 554ms	remaining: 194ms
37:	learn: 0.3635997	total: 568ms	remaining: 179ms
38:	learn: 0.3605372	total: 583ms	remaining: 164ms
39:	learn: 0.3582814	total: 597ms	remaining: 149ms
40:	learn: 0.3552965	total: 609ms	remaining: 134ms
41:	learn: 0.3533883	total: 616ms	remaining: 117ms
42:	learn: 0.3515812	total: 624ms	remaining: 102ms
43:	learn: 0.3497529	total: 632ms	remaining: 86.2ms
44:	learn: 0.3471691	total: 640ms	remaining: 71.1ms
45:	learn: 0.3454641	total: 648ms	remaining: 56.4ms
46:	learn: 0.3434441	total: 658ms	remaining: 42ms
47:	learn: 0.3416445	total: 667ms	remaining: 27.8ms
48:	learn: 0.3397104	total: 675ms	remaining: 13.8ms
49:	learn: 0.3380106	total: 682ms	remaining: 0us
Classification Report : 10 -               precision    recall  f1-score   support

           0       0.88      0.44      0.59        34
           1       0.82      0.75      0.78       641
           2       0.77      0.83      0.80      1329
           3       0.85      0.84      0.85       996

    accuracy                           0.81      3000
   macro avg       0.83      0.71      0.75      3000
weighted avg       0.81      0.81      0.81      3000

In [65]:
import lightgbm as lgb

In [66]:
c = 0
for XTrain,XTest in data_list:
  c += 1
  lgbm = lgb.LGBMClassifier(learning_rate=0.5,n_estimators=50,subsample=0.8,colsample_bytree=0.8,max_depth=5,random_state=7)
  lgbm.fit(XTrain,Y_train)
  y_pred = lgbm.predict(XTest)
  print(f'Classification Report : {c} - {classification_report(Y_test,y_pred)}')

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.004457 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4491
[LightGBM] [Info] Number of data points in the train set: 7000, number of used features: 89
[LightGBM] [Info] Start training from score -4.471639
[LightGBM] [Info] Start training from score -1.543115
[LightGBM] [Info] Start training from score -0.814508
[LightGBM] [Info] Start training from score -1.102620
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Classification Report : 1 -               precision    recall  f1-score   support

           0       0.26      0.38      0.31        34
           1       0.77      0.63      0.69       641
           2       0.73      0.81      0.77      1329
           3       0.84      0.81      0.83       996

    accuracy                           0.77      3000
   macro avg       0.65      0.66      0.65      3000
weighted avg       0.77      0.77      0.77      3000

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.007004 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 4378
[LightGBM] [Info] Number of data points in the train set: 7000, number of used features: 89
[LightGBM] [Info] Start training from score -4.471639
[LightGBM] [Info] Start training from score -1.543115
[LightGBM] [Info] Start training from score -0.814508
[LightGBM] [Info] Start training from score -1.102620
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

Classification Report : 3 -               precision    recall  f1-score   support

           0       0.10      0.12      0.11        34
           1       0.64      0.58      0.61       641
           2       0.68      0.71      0.70      1329
           3       0.78      0.76      0.77       996

    accuracy                           0.69      3000
   macro avg       0.55      0.54      0.54      3000
weighted avg       0.70      0.69      0.69      3000

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.006318 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 10965
[LightGBM] [Info] Number of data points in the train set: 7000, number of used features: 43
[LightGBM] [Info] Start training from score -4.471639
[LightGBM] [Info] Start training from score -1.543115
[LightGBM] [Info] Start training from score -0.814508
[LightGBM] [Info] Start training from score -1.102620
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Classification Report : 4 -               precision    recall  f1-score   support

           0       0.07      0.12      0.08        34
           1       0.76      0.62      0.68       641
           2       0.72      0.79      0.75      1329
           3       0.82      0.79      0.81       996

    accuracy                           0.75      3000
   macro avg       0.59      0.58      0.58      3000
weighted avg       0.76      0.75      0.75      3000

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 2.317421 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1784745
[LightGBM] [Info] Number of data points in the train set: 7000, number of used features: 6999
[LightGBM] [Info] Start training from score -4.471639
[LightGBM] [Info] Start training from score -1.543115
[LightGBM] [Info] Start training from score -0.814508
[LightGBM] [Info] Start training from score -1.102620
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Classification Report : 5 -               precision    recall  f1-score   support

           0       0.02      0.03      0.03        34
           1       0.61      0.46      0.53       641
           2       0.63      0.71      0.67      1329
           3       0.74      0.72      0.73       996

    accuracy                           0.65      3000
   macro avg       0.50      0.48      0.49      3000
weighted avg       0.66      0.65      0.65      3000

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 2.285433 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1784745
[LightGBM] [Info] Number of data points in the train set: 7000, number of used features: 6999
[LightGBM] [Info] Start training from score -4.471639
[LightGBM] [Info] Start training from score -1.543115
[LightGBM] [Info] Start training from score -0.814508
[LightGBM] [Info] Start training from score -1.102620
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

Classification Report : 6 -               precision    recall  f1-score   support

           0       0.05      0.12      0.07        34
           1       0.64      0.44      0.52       641
           2       0.63      0.69      0.66      1329
           3       0.71      0.72      0.72       996

    accuracy                           0.64      3000
   macro avg       0.51      0.49      0.49      3000
weighted avg       0.65      0.64      0.64      3000

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000925 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1542
[LightGBM] [Info] Number of data points in the train set: 7000, number of used features: 45
[LightGBM] [Info] Start training from score -4.471639
[LightGBM] [Info] Start training from score -1.543115
[LightGBM] [Info] Start training from score -0.814508
[LightGBM] [Info] Start training from score -1.102620
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
Classification Report : 7 -               precision    recall  f1-score   support

           0       0.02      0.06      0.03        34
           1       0.56      0.53      0.55       641
           2       0.62      0.59      0.60      1329
           3       0.74      0.76      0.75       996

    accuracy                           0.63      3000
   macro avg       0.48      0.48      0.48      3000
weighted avg       0.64      0.63      0.63      3000

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002056 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1511
[LightGBM] [Info] Number of data points in the train set: 7000, number of used features: 45
[LightGBM] [Info] Start training from score -4.471639
[LightGBM] [Info] Start training from score -1.543115
[LightGBM] [Info] Start training from score -0.814508
[LightGBM] [Info] Start training from score -1.102620
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

Write automation code i.e fn --> takes model,X_train,X_test,Y_train,Y_test as parameters and automate further