<a href="https://colab.research.google.com/github/karthikoo7/Machine_Learning-BDA-/blob/main/Case_Study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Case Study : on dataset -- https://www.kaggle.com/datasets/nalisha/early-wakeup-health-and-lifestyle-dataset

In [80]:
import pandas as pd

In [81]:
df = pd.read_csv('/content/early_wakeup_health_dataset.csv')

In [82]:
print(df.shape)
print(df.columns)

(10000, 64)
Index(['Person_ID', 'Age', 'Gender', 'Height_cm', 'Weight_kg', 'BMI',
       'Country', 'Occupation', 'Marital_Status', 'Wake_Up_Time', 'Sleep_Time',
       'Sleep_Duration_Hours', 'Sleep_Quality_Score',
       'Number_of_Night_Awakenings', 'Weekend_Sleep_Difference_Hours',
       'Nap_Frequency_Per_Week', 'Screen_Time_Before_Bed_Hours',
       'Exercise_Frequency_Per_Week', 'Exercise_Duration_Minutes',
       'Exercise_Type', 'Daily_Steps', 'Morning_Workout', 'Workout_Intensity',
       'Gym_Member', 'Daily_Calorie_Intake', 'Water_Intake_Liters',
       'Fruit_Intake_Per_Day', 'Vegetable_Intake_Per_Day',
       'Protein_Intake_Grams', 'Sugary_Drinks_Per_Week',
       'Fast_Food_Meals_Per_Week', 'Breakfast_Regularity_Score',
       'Smoking_Status', 'Alcohol_Consumption', 'Stress_Level',
       'Working_Hours_Per_Day', 'Sitting_Hours_Per_Day', 'Outdoor_Time_Hours',
       'Social_Interaction_Score', 'Meditation_Practice', 'Resting_Heart_Rate',
       'Systolic_BP', 'Diastolic_BP', 'Cholesterol_Level', 'Blood_Sugar_Level',
       'Energy_Level_Score', 'Fatigue_Level_Score', 'Immune_Health_Score',
       'Mood_Score', 'Anxiety_Score', 'Depression_Risk_Score',
       'Productivity_Score', 'Focus_Concentration_Score',
       'Life_Satisfaction_Score', 'Obesity_Risk', 'Hypertension_Risk',
       'Diabetes_Risk', 'Cardiovascular_Risk', 'Sleep_Disorder_Risk',
       'Health_Score', 'Fitness_Level', 'Healthy_Aging_Score',
       'Wellness_Category', 'Early_Waker'],
      dtype='object')

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 64 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Person_ID                       10000 non-null  object
 1   Age                             10000 non-null  int64
 2   Gender                          10000 non-null  object
 3   Height_cm                       10000 non-null  float64
 4   Weight_kg                       10000 non-null  float64
 5   BMI                             10000 non-null  float64
 6   Country                         10000 non-null  object
 7   Occupation                      10000 non-null  object
 8   Marital_Status                  10000 non-null  object
 9   Wake_Up_Time                    10000 non-null  object
 10  Sleep_Time                      10000 non-null  object
 11  Sleep_Duration_Hours            10000 non-null  float64
 12  Sleep_Quality_Score             10000 non-null  float64
 13  Number_of_Night_Awakenings      10000 non-null  int64
 14  Weekend_Sleep_Difference_Hours  10000 non-null  float64
 15  Nap_Frequency_Per_Week          10000 non-null  int64
 16  Screen_Time_Before_Bed_Hours    10000 non-null  float64
 17  Exercise_Frequency_Per_Week     10000 non-null  int64
 18  Exercise_Duration_Minutes       10000 non-null  int64
 19  Exercise_Type                   9176 non-null   object
 20  Daily_Steps                     10000 non-null  int64
 21  Morning_Workout                 10000 non-null  object
 22  Workout_Intensity               9176 non-null   object
 23  Gym_Member                      10000 non-null  object
 24  Daily_Calorie_Intake            10000 non-null  int64
 25  Water_Intake_Liters             10000 non-null  float64
 26  Fruit_Intake_Per_Day            10000 non-null  int64
 27  Vegetable_Intake_Per_Day        10000 non-null  int64
 28  Protein_Intake_Grams            10000 non-null  float64
 29  Sugary_Drinks_Per_Week          10000 non-null  int64
 30  Fast_Food_Meals_Per_Week        10000 non-null  int64
 31  Breakfast_Regularity_Score      10000 non-null  float64
 32  Smoking_Status                  10000 non-null  object
 33  Alcohol_Consumption             6986 non-null   object
 34  Stress_Level                    10000 non-null  float64
 35  Working_Hours_Per_Day           10000 non-null  float64
 36  Sitting_Hours_Per_Day           10000 non-null  float64
 37  Outdoor_Time_Hours              10000 non-null  float64
 38  Social_Interaction_Score        10000 non-null  float64
 39  Meditation_Practice             10000 non-null  object
 40  Resting_Heart_Rate              10000 non-null  int64
 41  Systolic_BP                     10000 non-null  int64
 42  Diastolic_BP                    10000 non-null  int64
 43  Cholesterol_Level               10000 non-null  float64
 44  Blood_Sugar_Level               10000 non-null  float64
 45  Energy_Level_Score              10000 non-null  float64
 46  Fatigue_Level_Score             10000 non-null  float64
 47  Immune_Health_Score             10000 non-null  float64
 48  Mood_Score                      10000 non-null  float64
 49  Anxiety_Score                   10000 non-null  float64
 50  Depression_Risk_Score           10000 non-null  float64
 51  Productivity_Score              10000 non-null  float64
 52  Focus_Concentration_Score       10000 non-null  float64
 53  Life_Satisfaction_Score         10000 non-null  float64
 54  Obesity_Risk                    10000 non-null  object
 55  Hypertension_Risk               10000 non-null  object
 56  Diabetes_Risk                   10000 non-null  object
 57  Cardiovascular_Risk             10000 non-null  object
 58  Sleep_Disorder_Risk             10000 non-null  object
 59  Health_Score                    10000 non-null  float64
 60  Fitness_Level                   10000 non-null  object
 61  Healthy_Aging_Score             10000 non-null  float64
 62  Wellness_Category               10000 non-null  object
 63  Early_Waker                     10000 non-null  object
dtypes: float64(28), int64(14), object(22)
memory usage: 4.9+ MB

In [84]:
df.head()

,Person_ID,Age,Gender,Height_cm,Weight_kg,BMI,Country,Occupation,Marital_Status,Wake_Up_Time,...,Obesity_Risk,Hypertension_Risk,Diabetes_Risk,Cardiovascular_Risk,Sleep_Disorder_Risk,Health_Score,Fitness_Level,Healthy_Aging_Score,Wellness_Category,Early_Waker
0,P00001,76,Female,158.8,62.1,24.63,Italy,Entrepreneur,Widowed,08:59,...,Low,High,Medium,Medium,Low,87.3,Excellent,81.8,Excellent,No
1,P00002,49,Female,160.9,68.5,26.45,USA,Freelancer,Single,06:35,...,Medium,Medium,Medium,Low,Medium,72.0,Good,75.2,Good,No
2,P00003,51,Female,151.9,54.8,23.77,Mexico,Nurse,Single,07:31,...,Low,Medium,Medium,Low,Low,75.2,Good,77.1,Good,No
3,P00004,48,Male,167.6,81.3,28.93,Australia,Laborer,Single,08:36,...,Medium,Medium,Low,Low,Medium,82.7,Excellent,87.1,Excellent,No
4,P00005,68,Female,171.9,75.4,25.51,USA,Software Engineer,Married,07:07,...,Medium,High,Medium,Medium,Low,62.7,Average,58.1,Average,No

# Problem Statement:

---
Target : Fitness_Level (Multi class classification)

Drop Columns : ( irrelevent & possible target)
Obesity_Risk
Hypertension_Risk
Diabetes_Risk
Cardiovascular_Risk
Sleep_Disorder_Risk
Health_Score
Healthy_Aging_Score
Wellness_Category
Early_Waker
Depression_Risk_Score
Gym_Member
Height_cm
Weight_kg
Person_ID


Preprocessing :
Wake_Up_Time -->convert to categorical
Sleep_Time -->convert to categorical
Country --> check distribution --> NO NEED OF REMOVAL OF ANY Country -->DONE
Productivity --> to be discussed


Ordinal:
Workout_Intensity
Smoking_Status
Alcohol_Consumption







---

In [85]:
# Drop columns
df.drop(
    columns=[
        "Obesity_Risk",
        "Hypertension_Risk",
        "Diabetes_Risk",
        "Cardiovascular_Risk",
        "Sleep_Disorder_Risk",
        "Health_Score",
        "Healthy_Aging_Score",
        "Wellness_Category",
        "Early_Waker",
        "Depression_Risk_Score",
        "Gym_Member",
        "Height_cm",
        "Weight_kg",
        "Person_ID",
    ],inplace=True

)

df.shape

(10000, 50)

In [86]:
# Converting continous to categorical -- fn= toDateTime

In [87]:
df['Wake_Up_Time'] = pd.to_datetime(df['Wake_Up_Time'])
df['Sleep_Time'] = pd.to_datetime(df['Sleep_Time'])

/tmp/ipykernel_68500/214474565.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Wake_Up_Time'] = pd.to_datetime(df['Wake_Up_Time'])
/tmp/ipykernel_68500/214474565.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Sleep_Time'] = pd.to_datetime(df['Sleep_Time'])

In [88]:
df['Wake_Up_Time'].head()

0   2026-06-27 08:59:00
1   2026-06-27 06:35:00
2   2026-06-27 07:31:00
3   2026-06-27 08:36:00
4   2026-06-27 07:07:00
Name: Wake_Up_Time, dtype: datetime64[ns]

In [89]:
df.loc[(df['Wake_Up_Time'] >= '2026-06-27 04:00:00') &
       (df['Wake_Up_Time'] < '2026-06-27 06:00:00'),"WT_cat"] = 0

df.loc[(df['Wake_Up_Time'] >= '2026-06-27 06:00:00') &
       (df['Wake_Up_Time'] < '2026-06-27 08:00:00'),"WT_cat"] = 1


df.loc[(df['Wake_Up_Time'] >= '2026-06-27 08:00:00') &
       (df['Wake_Up_Time'] < '2026-06-27 10:00:00'),"WT_cat"] = 2


df.loc[(df['Wake_Up_Time'] >= '2026-06-27 10:00:00') &
       (df['Wake_Up_Time'] <= '2026-06-27 11:00:00'),"WT_cat"] = 3

In [90]:
df['WT_cat'].unique()

array([2., 1., 0., 3.])

In [91]:
df.loc[(df['Sleep_Time'] >= '2026-06-27 20:00:00') &
       (df['Sleep_Time'] < '2026-06-27 22:00:00'),"ST_cat"] = 0

df.loc[(df['Sleep_Time'] >= '2026-06-27 22:00:00') &
       (df['Sleep_Time'] <= '2026-06-27 23:59:00'),"ST_cat"] = 1


df.loc[(df['Sleep_Time'] >= '2026-06-27 00:00:00') &
       (df['Sleep_Time'] < '2026-06-27 03:00:00'),"ST_cat"] = 2


df.loc[(df['Sleep_Time'] >= '2026-06-27 03:00:00') &
       (df['Sleep_Time'] < '2026-06-27 07:00:00'),"ST_cat"] = 3


df.loc[(df['Sleep_Time'] >= '2026-06-27 18:00:00') &
       (df['Sleep_Time'] <= '2026-06-27 20:00:00'),"ST_cat"] = 4

In [92]:
df['ST_cat'].unique()

array([2., 1., 0., 4., 3.])

In [93]:
df.drop(columns=['Wake_Up_Time','Sleep_Time'],inplace=True)

In [94]:
df.shape

(10000, 50)

In [95]:
df.columns

Index(['Age', 'Gender', 'BMI', 'Country', 'Occupation', 'Marital_Status',
       'Sleep_Duration_Hours', 'Sleep_Quality_Score',
       'Number_of_Night_Awakenings', 'Weekend_Sleep_Difference_Hours',
       'Nap_Frequency_Per_Week', 'Screen_Time_Before_Bed_Hours',
       'Exercise_Frequency_Per_Week', 'Exercise_Duration_Minutes',
       'Exercise_Type', 'Daily_Steps', 'Morning_Workout', 'Workout_Intensity',
       'Daily_Calorie_Intake', 'Water_Intake_Liters', 'Fruit_Intake_Per_Day',
       'Vegetable_Intake_Per_Day', 'Protein_Intake_Grams',
       'Sugary_Drinks_Per_Week', 'Fast_Food_Meals_Per_Week',
       'Breakfast_Regularity_Score', 'Smoking_Status', 'Alcohol_Consumption',
       'Stress_Level', 'Working_Hours_Per_Day', 'Sitting_Hours_Per_Day',
       'Outdoor_Time_Hours', 'Social_Interaction_Score', 'Meditation_Practice',
       'Resting_Heart_Rate', 'Systolic_BP', 'Diastolic_BP',
       'Cholesterol_Level', 'Blood_Sugar_Level', 'Energy_Level_Score',
       'Fatigue_Level_Score', 'Immune_Health_Score', 'Mood_Score',
       'Anxiety_Score', 'Productivity_Score', 'Focus_Concentration_Score',
       'Life_Satisfaction_Score', 'Fitness_Level', 'WT_cat', 'ST_cat'],
      dtype='object')

In [96]:
df.isna().sum()

Age                                  0
Gender                               0
BMI                                  0
Country                              0
Occupation                           0
Marital_Status                       0
Sleep_Duration_Hours                 0
Sleep_Quality_Score                  0
Number_of_Night_Awakenings           0
Weekend_Sleep_Difference_Hours       0
Nap_Frequency_Per_Week               0
Screen_Time_Before_Bed_Hours         0
Exercise_Frequency_Per_Week          0
Exercise_Duration_Minutes            0
Exercise_Type                      824
Daily_Steps                          0
Morning_Workout                      0
Workout_Intensity                  824
Daily_Calorie_Intake                 0
Water_Intake_Liters                  0
Fruit_Intake_Per_Day                 0
Vegetable_Intake_Per_Day             0
Protein_Intake_Grams                 0
Sugary_Drinks_Per_Week               0
Fast_Food_Meals_Per_Week             0
Breakfast_Regularity_Score           0
Smoking_Status                       0
Alcohol_Consumption               3014
Stress_Level                         0
Working_Hours_Per_Day                0
Sitting_Hours_Per_Day                0
Outdoor_Time_Hours                   0
Social_Interaction_Score             0
Meditation_Practice                  0
Resting_Heart_Rate                   0
Systolic_BP                          0
Diastolic_BP                         0
Cholesterol_Level                    0
Blood_Sugar_Level                    0
Energy_Level_Score                   0
Fatigue_Level_Score                  0
Immune_Health_Score                  0
Mood_Score                           0
Anxiety_Score                        0
Productivity_Score                   0
Focus_Concentration_Score            0
Life_Satisfaction_Score              0
Fitness_Level                        0
WT_cat                               0
ST_cat                               0
dtype: int64

Be carfeul while using mode fn -- when in case of multimodal distribution -- it returns all the modes values -- hence we use -- .iloc[0] to only return to us a single value of mode

In [97]:
#df[['Exercise_Type','Workout_Intensity','Alcohol_Consumption']].mode().iloc[0]

In [98]:
#fill_value = df[['Exercise_Type','Workout_Intensity','Alcohol_Consumption']].mode().iloc[0]

#df[['Exercise_Type','Workout_Intensity','Alcohol_Consumption']].fillna(fill_value,inplace=True)

In [99]:

df.isnull().sum().sum()

np.int64(4662)

In [100]:
df.loc[df['Alcohol_Consumption'].isna() == True,'Alcohol_Consumption'] = 0

In [101]:
fill_value = df.mode().iloc[0]
df.fillna(fill_value,inplace=True)

In [102]:
df.isnull().sum().sum()

np.int64(0)

# Handle Ordinal Columns by Label Encoding

In [103]:
df['Workout_Intensity'].unique()

array(['Low', 'Moderate', 'High'], dtype=object)

In [104]:
df['Smoking_Status'].unique()

array(['Former', 'Current', 'Never'], dtype=object)

In [105]:
df['Alcohol_Consumption'].unique()

array(['Moderate', 0, 'Light', 'Heavy'], dtype=object)

In [106]:
label_map = {
    'Workout_Intensity':{'Low':0, 'Moderate':1, 'High':2},
    'Smoking_Status':{'Former':0, 'Current':1, 'Never':2},
    'Alcohol_Consumption':{'Moderate':1, 'Light':2, 'Heavy':3}
}

In [107]:
df.replace(label_map,inplace=True)

/tmp/ipykernel_68500/1715271054.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(label_map,inplace=True)

In [108]:
print(df['Workout_Intensity'].unique())
print(df['Smoking_Status'].unique())
print(df['Alcohol_Consumption'].unique())

[0 1 2]
[0 1 2]
[1 0 2 3]

In [109]:
df.columns[df.nunique() > 20] # columns --> continous values

Index(['Age', 'BMI', 'Sleep_Duration_Hours', 'Sleep_Quality_Score',
       'Weekend_Sleep_Difference_Hours', 'Screen_Time_Before_Bed_Hours',
       'Exercise_Duration_Minutes', 'Daily_Steps', 'Daily_Calorie_Intake',
       'Water_Intake_Liters', 'Protein_Intake_Grams',
       'Breakfast_Regularity_Score', 'Stress_Level', 'Working_Hours_Per_Day',
       'Sitting_Hours_Per_Day', 'Outdoor_Time_Hours',
       'Social_Interaction_Score', 'Resting_Heart_Rate', 'Systolic_BP',
       'Diastolic_BP', 'Cholesterol_Level', 'Blood_Sugar_Level',
       'Energy_Level_Score', 'Fatigue_Level_Score', 'Immune_Health_Score',
       'Mood_Score', 'Anxiety_Score', 'Productivity_Score',
       'Focus_Concentration_Score', 'Life_Satisfaction_Score'],
      dtype='object')

In [110]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 50 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Age                             10000 non-null  int64
 1   Gender                          10000 non-null  object
 2   BMI                             10000 non-null  float64
 3   Country                         10000 non-null  object
 4   Occupation                      10000 non-null  object
 5   Marital_Status                  10000 non-null  object
 6   Sleep_Duration_Hours            10000 non-null  float64
 7   Sleep_Quality_Score             10000 non-null  float64
 8   Number_of_Night_Awakenings      10000 non-null  int64
 9   Weekend_Sleep_Difference_Hours  10000 non-null  float64
 10  Nap_Frequency_Per_Week          10000 non-null  int64
 11  Screen_Time_Before_Bed_Hours    10000 non-null  float64
 12  Exercise_Frequency_Per_Week     10000 non-null  int64
 13  Exercise_Duration_Minutes       10000 non-null  int64
 14  Exercise_Type                   10000 non-null  object
 15  Daily_Steps                     10000 non-null  int64
 16  Morning_Workout                 10000 non-null  object
 17  Workout_Intensity               10000 non-null  int64
 18  Daily_Calorie_Intake            10000 non-null  int64
 19  Water_Intake_Liters             10000 non-null  float64
 20  Fruit_Intake_Per_Day            10000 non-null  int64
 21  Vegetable_Intake_Per_Day        10000 non-null  int64
 22  Protein_Intake_Grams            10000 non-null  float64
 23  Sugary_Drinks_Per_Week          10000 non-null  int64
 24  Fast_Food_Meals_Per_Week        10000 non-null  int64
 25  Breakfast_Regularity_Score      10000 non-null  float64
 26  Smoking_Status                  10000 non-null  int64
 27  Alcohol_Consumption             10000 non-null  int64
 28  Stress_Level                    10000 non-null  float64
 29  Working_Hours_Per_Day           10000 non-null  float64
 30  Sitting_Hours_Per_Day           10000 non-null  float64
 31  Outdoor_Time_Hours              10000 non-null  float64
 32  Social_Interaction_Score        10000 non-null  float64
 33  Meditation_Practice             10000 non-null  object
 34  Resting_Heart_Rate              10000 non-null  int64
 35  Systolic_BP                     10000 non-null  int64
 36  Diastolic_BP                    10000 non-null  int64
 37  Cholesterol_Level               10000 non-null  float64
 38  Blood_Sugar_Level               10000 non-null  float64
 39  Energy_Level_Score              10000 non-null  float64
 40  Fatigue_Level_Score             10000 non-null  float64
 41  Immune_Health_Score             10000 non-null  float64
 42  Mood_Score                      10000 non-null  float64
 43  Anxiety_Score                   10000 non-null  float64
 44  Productivity_Score              10000 non-null  float64
 45  Focus_Concentration_Score       10000 non-null  float64
 46  Life_Satisfaction_Score         10000 non-null  float64
 47  Fitness_Level                   10000 non-null  object
 48  WT_cat                          10000 non-null  float64
 49  ST_cat                          10000 non-null  float64
dtypes: float64(25), int64(17), object(8)
memory usage: 3.8+ MB

# X and Y Split
target = fitnss level

In [111]:
X = df.drop(columns=['Fitness_Level'])
Y = df['Fitness_Level']

X.shape,Y.shape

((10000, 49), (10000,))

In [112]:

Y.unique()

array(['Excellent', 'Good', 'Average', 'Poor'], dtype=object)

In [113]:
label_map = {'Excellent':3, 'Good':2, 'Average':1, 'Poor':0}

Y.replace(label_map,inplace=True)

/tmp/ipykernel_68500/1413044726.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  Y.replace(label_map,inplace=True)

In [114]:
Y.unique()

array([3, 2, 1, 0])

In [115]:
X_ohe = pd.get_dummies(X)
X_ohe.shape

(10000, 91)

In [116]:
cat_col = X_ohe.columns[X_ohe.nunique() <= 15]
cat_col.shape

(61,)

In [117]:
cont_col = X_ohe.columns[X_ohe.nunique() > 15]
cont_col.shape

(30,)

Train Test split

In [118]:
from sklearn.model_selection import train_test_split

In [119]:
X_train,X_test,Y_train,Y_test = train_test_split(X_ohe,Y,test_size=0.3,random_state=7,stratify=Y)

X_train.shape,X_test.shape,Y_train.shape,Y_test.shape

((7000, 91), (3000, 91), (7000,), (3000,))

applying standard scaler on continous & outlier detection

In [120]:
from sklearn.preprocessing import RobustScaler

In [121]:
rc = RobustScaler()
X_train[cont_col] = rc.fit_transform(X_train[cont_col])
X_test[cont_col] = rc.transform(X_test[cont_col])

Outlier Imputation

In [122]:
def outlier_imputation_iqr(df,col):
  df1 = df.copy()
  q1,q3 = df1[col].quantile([0.25,0.75])
  iqr = q3-q1
  LB = q1 - 1.5*iqr
  UB = q3 + 1.5*iqr
  print("Column -->",col)
  df1.loc[(df1[col]<LB),col] = LB
  df1.loc[(df1[col]>UB),col] = UB
  print(LB,UB, df1[col].min(),df1[col].max())
  return df1

In [123]:
X_train_io = X_train.copy()
for col in cont_col:
  X_train_io = outlier_imputation_iqr(X_train_io,col)

Column --> Age
-1.9642857142857144 2.0357142857142856 -0.8928571428571429 1.3214285714285714
Column --> BMI
-2.0089153046062407 1.9910846953937595 -1.4257057949479945 1.9910846953937595
Column --> Sleep_Duration_Hours
-2.0033557046979866 1.9966442953020134 -2.0033557046979866 1.8523489932885902
Column --> Sleep_Quality_Score
-2.0 2.0 -2.0 1.7272727272727282
Column --> Weekend_Sleep_Difference_Hours
-2.0092592592592595 1.9907407407407407 -1.8888888888888888 1.9907407407407407
Column --> Screen_Time_Before_Bed_Hours
-1.8664122137404582 2.133587786259542 -0.618320610687023 2.133587786259542
Column --> Exercise_Duration_Minutes
-2.0 2.0 -1.6071428571428572 2.0
Column --> Daily_Steps
-2.025921583952065 1.9740784160479354 -1.9954409274456169 1.9740784160479354
Column --> Daily_Calorie_Intake
-1.9973230220107079 2.0026769779892923 -1.9973230220107079 2.0026769779892923
Column --> Water_Intake_Liters
-1.9999999999999996 2.0000000000000004 -1.9999999999999996 2.0000000000000004
Column --> Protein_Intake_Grams
-2.0116959064327484 1.9883040935672516 -1.97953216374269 1.9883040935672516
Column --> Breakfast_Regularity_Score
-2.0000000000000004 1.9999999999999996 -2.0000000000000004 1.0
Column --> Stress_Level
-2.0 2.0 -1.2499999999999998 1.9642857142857142
Column --> Working_Hours_Per_Day
-2.0 2.0 -2.0 2.0
Column --> Sitting_Hours_Per_Day
-1.9999999999999998 2.0 -1.9999999999999998 2.0
Column --> Outdoor_Time_Hours
-1.939153439153439 2.060846560846561 -1.3544973544973544 2.060846560846561
Column --> Social_Interaction_Score
-2.0 2.0 -1.7083333333333333 2.0
Column --> Resting_Heart_Rate
-2.0 2.0 -2.0 2.0
Column --> Systolic_BP
-2.0 2.0 -2.0 2.0
Column --> Diastolic_BP
-2.0 2.0 -2.0 2.0
Column --> Cholesterol_Level
-1.9952076677316297 2.0047923322683703 -1.9952076677316297 2.0047923322683703
Column --> Blood_Sugar_Level
-1.9976452119309256 2.0023547880690726 -1.9976452119309256 2.0023547880690726
Column --> Energy_Level_Score
-2.0 1.9999999999999998 -2.0 1.277777777777778
Column --> Fatigue_Level_Score
-1.9615384615384617 2.0384615384615383 -0.7307692307692308 2.0384615384615383
Column --> Immune_Health_Score
-1.9999999999999996 2.0000000000000004 -1.9999999999999996 2.0000000000000004
Column --> Mood_Score
-2.0294117647058822 1.9705882352941178 -2.0294117647058822 1.8823529411764715
Column --> Anxiety_Score
-2.0238095238095237 1.976190476190476 -1.9999999999999996 1.976190476190476
Column --> Productivity_Score
-1.9666666666666668 2.033333333333333 -1.9666666666666668 2.0
Column --> Focus_Concentration_Score
-2.0384615384615388 1.9615384615384612 -2.0384615384615388 1.9615384615384612
Column --> Life_Satisfaction_Score
-1.966666666666667 2.033333333333333 -1.966666666666667 1.733333333333334

# Feature Selection

1) PCA
2) KPCA
3) RFE
4) DT

In [45]:
# pca
from sklearn.decomposition import PCA

In [46]:
pca = PCA(n_components=0.95,random_state=7)
X_train_pca = pca.fit_transform(X_train)
X_test_pca = pca.transform(X_test)
pca.explained_variance_ratio_

array([0.18185014, 0.16956939, 0.09886897, 0.06222916, 0.05291092,
       0.04259158, 0.03769127, 0.02346166, 0.01884357, 0.01769198,
       0.01729329, 0.01490091, 0.01323802, 0.01212114, 0.01126595,
       0.01051811, 0.01014061, 0.00932317, 0.00929714, 0.00914728,
       0.00826085, 0.0082202 , 0.00803999, 0.00783116, 0.00749436,
       0.00735107, 0.00708425, 0.0068438 , 0.00667913, 0.00631595,
       0.00621384, 0.00572855, 0.00531171, 0.00480223, 0.0046137 ,
       0.00384273, 0.00350683, 0.00337671, 0.00319122, 0.00296986,
       0.0028185 , 0.00254157, 0.0024838 , 0.00238007])

In [47]:
pca = PCA(n_components=0.95,random_state=7)
X_train_io_pca = pca.fit_transform(X_train_io)
X_test_io_pca = pca.transform(X_test)
pca.explained_variance_ratio_

array([0.18257326, 0.17026247, 0.09888618, 0.06248473, 0.05312013,
       0.04274708, 0.03767289, 0.02335887, 0.01889849, 0.01763723,
       0.01731545, 0.01494855, 0.01269897, 0.01214633, 0.01127735,
       0.01045927, 0.01003391, 0.00932675, 0.00919647, 0.00828767,
       0.00823154, 0.00805345, 0.00793747, 0.00777635, 0.00750363,
       0.00729191, 0.00709032, 0.00680522, 0.00669714, 0.00628243,
       0.00618478, 0.0056896 , 0.00528452, 0.00480326, 0.00459976,
       0.00383554, 0.0035022 , 0.00336163, 0.0032042 , 0.00298163,
       0.00282095, 0.00255162, 0.00248235, 0.00238853])

In [48]:

pca.feature_names_in_

array(['Age', 'BMI', 'Sleep_Duration_Hours', 'Sleep_Quality_Score',
       'Number_of_Night_Awakenings', 'Weekend_Sleep_Difference_Hours',
       'Nap_Frequency_Per_Week', 'Screen_Time_Before_Bed_Hours',
       'Exercise_Frequency_Per_Week', 'Exercise_Duration_Minutes',
       'Daily_Steps', 'Workout_Intensity', 'Daily_Calorie_Intake',
       'Water_Intake_Liters', 'Fruit_Intake_Per_Day',
       'Vegetable_Intake_Per_Day', 'Protein_Intake_Grams',
       'Sugary_Drinks_Per_Week', 'Fast_Food_Meals_Per_Week',
       'Breakfast_Regularity_Score', 'Smoking_Status',
       'Alcohol_Consumption', 'Stress_Level', 'Working_Hours_Per_Day',
       'Sitting_Hours_Per_Day', 'Outdoor_Time_Hours',
       'Social_Interaction_Score', 'Resting_Heart_Rate', 'Systolic_BP',
       'Diastolic_BP', 'Cholesterol_Level', 'Blood_Sugar_Level',
       'Energy_Level_Score', 'Fatigue_Level_Score', 'Immune_Health_Score',
       'Mood_Score', 'Anxiety_Score', 'Productivity_Score',
       'Focus_Concentration_Score', 'Life_Satisfaction_Score', 'WT_cat',
       'ST_cat', 'Gender_Female', 'Gender_Male', 'Gender_Non-binary',
       'Country_Australia', 'Country_Brazil', 'Country_Canada',
       'Country_France', 'Country_Germany', 'Country_India',
       'Country_Italy', 'Country_Japan', 'Country_Mexico',
       'Country_Nigeria', 'Country_Pakistan', 'Country_South Korea',
       'Country_Spain', 'Country_UK', 'Country_USA',
       'Occupation_Accountant', 'Occupation_Artist', 'Occupation_Athlete',
       'Occupation_Chef', 'Occupation_Doctor', 'Occupation_Entrepreneur',
       'Occupation_Freelancer', 'Occupation_Laborer', 'Occupation_Lawyer',
       'Occupation_Manager', 'Occupation_Nurse', 'Occupation_Retired',
       'Occupation_Software Engineer', 'Occupation_Student',
       'Occupation_Teacher', 'Marital_Status_Divorced',
       'Marital_Status_Married', 'Marital_Status_Single',
       'Marital_Status_Widowed', 'Exercise_Type_Cycling',
       'Exercise_Type_HIIT', 'Exercise_Type_Running',
       'Exercise_Type_Sports', 'Exercise_Type_Swimming',
       'Exercise_Type_Walking', 'Exercise_Type_Weight Training',
       'Exercise_Type_Yoga', 'Morning_Workout_No', 'Morning_Workout_Yes',
       'Meditation_Practice_No', 'Meditation_Practice_Yes'], dtype=object)

KernelPCA

In [49]:
from sklearn.decomposition import KernelPCA

In [50]:
kpca = KernelPCA(kernel='rbf',random_state=7)
X_train_kpca = kpca.fit_transform(X_train)
X_test_kpca = kpca.transform(X_test)

X_train_kpca.shape,X_test_kpca.shape

((7000, 6999), (3000, 6999))

In [51]:
kpca = KernelPCA(kernel='rbf',random_state=7)
X_train_io_kpca = kpca.fit_transform(X_train_io)
X_test_io_kpca = kpca.transform(X_test)

X_train_io_kpca.shape,X_test_io_kpca.shape

((7000, 6999), (3000, 6999))

RFE - Recursive Feature Selection

In [52]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [53]:
rfe = RFE(LogisticRegression(random_state=7),verbose=2)
rfe.fit(X_train,Y_train)


for col,rank in zip(X_train.columns,rfe.ranking_):
  print(col,rank)

Fitting estimator with 91 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 90 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 89 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 88 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 87 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 86 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 85 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 84 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 83 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 82 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 81 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 80 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 79 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 78 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 77 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 76 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 75 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 74 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 73 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 72 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 71 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 70 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 69 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 68 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 67 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 66 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 65 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 64 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 63 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 62 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 61 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 60 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 59 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 58 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 57 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 56 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 55 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 54 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 53 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 52 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 51 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 50 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 49 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 48 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 47 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 46 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Age 1
BMI 1
Sleep_Duration_Hours 1
Sleep_Quality_Score 1
Number_of_Night_Awakenings 42
Weekend_Sleep_Difference_Hours 27
Nap_Frequency_Per_Week 45
Screen_Time_Before_Bed_Hours 39
Exercise_Frequency_Per_Week 1
Exercise_Duration_Minutes 43
Daily_Steps 1
Workout_Intensity 38
Daily_Calorie_Intake 28
Water_Intake_Liters 1
Fruit_Intake_Per_Day 16
Vegetable_Intake_Per_Day 1
Protein_Intake_Grams 3
Sugary_Drinks_Per_Week 47
Fast_Food_Meals_Per_Week 1
Breakfast_Regularity_Score 33
Smoking_Status 1
Alcohol_Consumption 1
Stress_Level 1
Working_Hours_Per_Day 25
Sitting_Hours_Per_Day 46
Outdoor_Time_Hours 37
Social_Interaction_Score 18
Resting_Heart_Rate 1
Systolic_BP 1
Diastolic_BP 32
Cholesterol_Level 41
Blood_Sugar_Level 40
Energy_Level_Score 15
Fatigue_Level_Score 21
Immune_Health_Score 1
Mood_Score 1
Anxiety_Score 1
Productivity_Score 44
Focus_Concentration_Score 35
Life_Satisfaction_Score 1
WT_cat 1
ST_cat 1
Gender_Female 1
Gender_Male 1
Gender_Non-binary 11
Country_Australia 1
Country_Brazil 30
Country_Canada 34
Country_France 14
Country_Germany 1
Country_India 1
Country_Italy 1
Country_Japan 10
Country_Mexico 29
Country_Nigeria 36
Country_Pakistan 1
Country_South Korea 1
Country_Spain 13
Country_UK 4
Country_USA 9
Occupation_Accountant 23
Occupation_Artist 26
Occupation_Athlete 24
Occupation_Chef 1
Occupation_Doctor 7
Occupation_Entrepreneur 1
Occupation_Freelancer 5
Occupation_Laborer 1
Occupation_Lawyer 1
Occupation_Manager 8
Occupation_Nurse 6
Occupation_Retired 1
Occupation_Software Engineer 2
Occupation_Student 20
Occupation_Teacher 22
Marital_Status_Divorced 1
Marital_Status_Married 1
Marital_Status_Single 1
Marital_Status_Widowed 1
Exercise_Type_Cycling 1
Exercise_Type_HIIT 1
Exercise_Type_Running 19
Exercise_Type_Sports 31
Exercise_Type_Swimming 17
Exercise_Type_Walking 12
Exercise_Type_Weight Training 1
Exercise_Type_Yoga 1
Morning_Workout_No 1
Morning_Workout_Yes 1
Meditation_Practice_No 1
Meditation_Practice_Yes 1

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [54]:
selected_col = X_train.columns[rfe.ranking_ == 1]
selected_col.shape

(45,)

In [55]:
X_train_rfe = X_train.loc[:,selected_col]
X_test_rfe = X_test.loc[:,selected_col]

In [56]:
rfe = RFE(LogisticRegression(random_state=7),verbose=2)
rfe.fit(X_train_io,Y_train)


for col,rank in zip(X_train_io.columns,rfe.ranking_):
  print(col,rank)

Fitting estimator with 91 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 90 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 89 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 88 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 87 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 86 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 85 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 84 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 83 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 82 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 81 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 80 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 79 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 78 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 77 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 76 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 75 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 74 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 73 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 72 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 71 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 70 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 69 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 68 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 67 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 66 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 65 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 64 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 63 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 62 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 61 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 60 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 59 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 58 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 57 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 56 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 55 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 54 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 53 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 52 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 51 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 50 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 49 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 48 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 47 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 46 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Age 1
BMI 1
Sleep_Duration_Hours 1
Sleep_Quality_Score 1
Number_of_Night_Awakenings 40
Weekend_Sleep_Difference_Hours 36
Nap_Frequency_Per_Week 46
Screen_Time_Before_Bed_Hours 44
Exercise_Frequency_Per_Week 1
Exercise_Duration_Minutes 42
Daily_Steps 1
Workout_Intensity 37
Daily_Calorie_Intake 33
Water_Intake_Liters 1
Fruit_Intake_Per_Day 19
Vegetable_Intake_Per_Day 1
Protein_Intake_Grams 3
Sugary_Drinks_Per_Week 47
Fast_Food_Meals_Per_Week 1
Breakfast_Regularity_Score 35
Smoking_Status 1
Alcohol_Consumption 1
Stress_Level 1
Working_Hours_Per_Day 24
Sitting_Hours_Per_Day 45
Outdoor_Time_Hours 25
Social_Interaction_Score 22
Resting_Heart_Rate 1
Systolic_BP 1
Diastolic_BP 30
Cholesterol_Level 43
Blood_Sugar_Level 38
Energy_Level_Score 23
Fatigue_Level_Score 15
Immune_Health_Score 1
Mood_Score 1
Anxiety_Score 1
Productivity_Score 41
Focus_Concentration_Score 34
Life_Satisfaction_Score 1
WT_cat 1
ST_cat 1
Gender_Female 1
Gender_Male 1
Gender_Non-binary 13
Country_Australia 1
Country_Brazil 27
Country_Canada 39
Country_France 17
Country_Germany 1
Country_India 1
Country_Italy 6
Country_Japan 10
Country_Mexico 31
Country_Nigeria 32
Country_Pakistan 1
Country_South Korea 1
Country_Spain 14
Country_UK 5
Country_USA 11
Occupation_Accountant 21
Occupation_Artist 28
Occupation_Athlete 18
Occupation_Chef 1
Occupation_Doctor 1
Occupation_Entrepreneur 1
Occupation_Freelancer 1
Occupation_Laborer 1
Occupation_Lawyer 1
Occupation_Manager 12
Occupation_Nurse 4
Occupation_Retired 1
Occupation_Software Engineer 2
Occupation_Student 8
Occupation_Teacher 20
Marital_Status_Divorced 1
Marital_Status_Married 1
Marital_Status_Single 1
Marital_Status_Widowed 1
Exercise_Type_Cycling 7
Exercise_Type_HIIT 1
Exercise_Type_Running 16
Exercise_Type_Sports 29
Exercise_Type_Swimming 26
Exercise_Type_Walking 9
Exercise_Type_Weight Training 1
Exercise_Type_Yoga 1
Morning_Workout_No 1
Morning_Workout_Yes 1
Meditation_Practice_No 1
Meditation_Practice_Yes 1

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [57]:
selected_col = X_train_io.columns[rfe.ranking_ == 1]
selected_col.shape

(45,)

In [58]:
X_train_io_rfe = X_train_io.loc[:,selected_col]
X_test_io_rfe = X_test.loc[:,selected_col]

Decision Tree

In [124]:
from sklearn.tree import DecisionTreeClassifier

In [125]:
dt = DecisionTreeClassifier(criterion='gini',class_weight='balanced',random_state=7)
dt.fit(X_train,Y_train)

DecisionTreeClassifier(class_weight='balanced', random_state=7)

In [126]:
selected_col = X_train.columns[dt.feature_importances_ > dt.feature_importances_.mean()]
selected_col.shape

(21,)

In [127]:
print(selected_col)

Index(['Age', 'BMI', 'Sleep_Duration_Hours', 'Sleep_Quality_Score',
       'Exercise_Frequency_Per_Week', 'Daily_Steps', 'Water_Intake_Liters',
       'Protein_Intake_Grams', 'Fast_Food_Meals_Per_Week', 'Stress_Level',
       'Social_Interaction_Score', 'Resting_Heart_Rate', 'Systolic_BP',
       'Blood_Sugar_Level', 'Energy_Level_Score', 'Fatigue_Level_Score',
       'Immune_Health_Score', 'Mood_Score', 'Anxiety_Score',
       'Productivity_Score', 'Life_Satisfaction_Score'],
      dtype='object')

In [128]:
dt = DecisionTreeClassifier(criterion='gini',class_weight='balanced',random_state=7)
dt.fit(X_train_io,Y_train)

DecisionTreeClassifier(class_weight='balanced', random_state=7)

In [129]:
selected_col_io = X_train_io.columns[dt.feature_importances_ > dt.feature_importances_.mean()]
selected_col_io.shape

(17,)

In [130]:
X_train_io_dt = X_train_io.loc[:,selected_col]
X_test_io_dt = X_test.loc[:,selected_col]

In [71]:
# Apply models for multi class classification