<a href="https://colab.research.google.com/github/karthikoo7/Machine_Learning-BDA-/blob/main/Casestudy123.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [59]:
import pandas as pd
df = pd.read_csv("early_wakeup_health_dataset.csv")
df.shape

(10000, 64)

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 64 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Person_ID                       10000 non-null  object
 1   Age                             10000 non-null  int64
 2   Gender                          10000 non-null  object
 3   Height_cm                       10000 non-null  float64
 4   Weight_kg                       10000 non-null  float64
 5   BMI                             10000 non-null  float64
 6   Country                         10000 non-null  object
 7   Occupation                      10000 non-null  object
 8   Marital_Status                  10000 non-null  object
 9   Wake_Up_Time                    10000 non-null  object
 10  Sleep_Time                      10000 non-null  object
 11  Sleep_Duration_Hours            10000 non-null  float64
 12  Sleep_Quality_Score             10000 non-null  float64
 13  Number_of_Night_Awakenings      10000 non-null  int64
 14  Weekend_Sleep_Difference_Hours  10000 non-null  float64
 15  Nap_Frequency_Per_Week          10000 non-null  int64
 16  Screen_Time_Before_Bed_Hours    10000 non-null  float64
 17  Exercise_Frequency_Per_Week     10000 non-null  int64
 18  Exercise_Duration_Minutes       10000 non-null  int64
 19  Exercise_Type                   9176 non-null   object
 20  Daily_Steps                     10000 non-null  int64
 21  Morning_Workout                 10000 non-null  object
 22  Workout_Intensity               9176 non-null   object
 23  Gym_Member                      10000 non-null  object
 24  Daily_Calorie_Intake            10000 non-null  int64
 25  Water_Intake_Liters             10000 non-null  float64
 26  Fruit_Intake_Per_Day            10000 non-null  int64
 27  Vegetable_Intake_Per_Day        10000 non-null  int64
 28  Protein_Intake_Grams            10000 non-null  float64
 29  Sugary_Drinks_Per_Week          10000 non-null  int64
 30  Fast_Food_Meals_Per_Week        10000 non-null  int64
 31  Breakfast_Regularity_Score      10000 non-null  float64
 32  Smoking_Status                  10000 non-null  object
 33  Alcohol_Consumption             6986 non-null   object
 34  Stress_Level                    10000 non-null  float64
 35  Working_Hours_Per_Day           10000 non-null  float64
 36  Sitting_Hours_Per_Day           10000 non-null  float64
 37  Outdoor_Time_Hours              10000 non-null  float64
 38  Social_Interaction_Score        10000 non-null  float64
 39  Meditation_Practice             10000 non-null  object
 40  Resting_Heart_Rate              10000 non-null  int64
 41  Systolic_BP                     10000 non-null  int64
 42  Diastolic_BP                    10000 non-null  int64
 43  Cholesterol_Level               10000 non-null  float64
 44  Blood_Sugar_Level               10000 non-null  float64
 45  Energy_Level_Score              10000 non-null  float64
 46  Fatigue_Level_Score             10000 non-null  float64
 47  Immune_Health_Score             10000 non-null  float64
 48  Mood_Score                      10000 non-null  float64
 49  Anxiety_Score                   10000 non-null  float64
 50  Depression_Risk_Score           10000 non-null  float64
 51  Productivity_Score              10000 non-null  float64
 52  Focus_Concentration_Score       10000 non-null  float64
 53  Life_Satisfaction_Score         10000 non-null  float64
 54  Obesity_Risk                    10000 non-null  object
 55  Hypertension_Risk               10000 non-null  object
 56  Diabetes_Risk                   10000 non-null  object
 57  Cardiovascular_Risk             10000 non-null  object
 58  Sleep_Disorder_Risk             10000 non-null  object
 59  Health_Score                    10000 non-null  float64
 60  Fitness_Level                   10000 non-null  object
 61  Healthy_Aging_Score             10000 non-null  float64
 62  Wellness_Category               10000 non-null  object
 63  Early_Waker                     10000 non-null  object
dtypes: float64(28), int64(14), object(22)
memory usage: 4.9+ MB

# Drop Columns

( irrelevent & possible target)

In [61]:
df.drop(columns=['Obesity_Risk'	,
'Hypertension_Risk'	,
'Diabetes_Risk'	,
'Cardiovascular_Risk'	,
'Sleep_Disorder_Risk'	,
'Health_Score'	,
'Healthy_Aging_Score'	,
'Wellness_Category'	,
'Early_Waker',
'Depression_Risk_Score',
'Gym_Member',
'Height_cm',
'Weight_kg',
'Person_ID',],inplace=True)
df.shape

(10000, 50)

# Convert date time to category

In [62]:
df['Wake_Up_Time'] = pd.to_datetime( df['Wake_Up_Time'])
df['Sleep_Time'] = pd.to_datetime( df['Sleep_Time'])

/tmp/ipykernel_3928/2732240999.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Wake_Up_Time'] = pd.to_datetime( df['Wake_Up_Time'])
/tmp/ipykernel_3928/2732240999.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Sleep_Time'] = pd.to_datetime( df['Sleep_Time'])

In [63]:
sorted(df['Sleep_Time'].unique())

[Timestamp('2026-06-27 00:00:00'),
 Timestamp('2026-06-27 00:01:00'),
 Timestamp('2026-06-27 00:02:00'),
 Timestamp('2026-06-27 00:03:00'),
 Timestamp('2026-06-27 00:04:00'),
 Timestamp('2026-06-27 00:05:00'),
 Timestamp('2026-06-27 00:06:00'),
 Timestamp('2026-06-27 00:07:00'),
 Timestamp('2026-06-27 00:08:00'),
 Timestamp('2026-06-27 00:09:00'),
 Timestamp('2026-06-27 00:10:00'),
 Timestamp('2026-06-27 00:11:00'),
 Timestamp('2026-06-27 00:12:00'),
 Timestamp('2026-06-27 00:13:00'),
 Timestamp('2026-06-27 00:14:00'),
 Timestamp('2026-06-27 00:15:00'),
 Timestamp('2026-06-27 00:16:00'),
 Timestamp('2026-06-27 00:17:00'),
 Timestamp('2026-06-27 00:18:00'),
 Timestamp('2026-06-27 00:19:00'),
 Timestamp('2026-06-27 00:20:00'),
 Timestamp('2026-06-27 00:21:00'),
 Timestamp('2026-06-27 00:22:00'),
 Timestamp('2026-06-27 00:23:00'),
 Timestamp('2026-06-27 00:24:00'),
 Timestamp('2026-06-27 00:25:00'),
 Timestamp('2026-06-27 00:26:00'),
 Timestamp('2026-06-27 00:27:00'),
 Timestamp('2026-06-27 00:28:00'),
 Timestamp('2026-06-27 00:29:00'),
 Timestamp('2026-06-27 00:30:00'),
 Timestamp('2026-06-27 00:31:00'),
 Timestamp('2026-06-27 00:32:00'),
 Timestamp('2026-06-27 00:33:00'),
 Timestamp('2026-06-27 00:34:00'),
 Timestamp('2026-06-27 00:35:00'),
 Timestamp('2026-06-27 00:36:00'),
 Timestamp('2026-06-27 00:37:00'),
 Timestamp('2026-06-27 00:38:00'),
 Timestamp('2026-06-27 00:39:00'),
 Timestamp('2026-06-27 00:40:00'),
 Timestamp('2026-06-27 00:41:00'),
 Timestamp('2026-06-27 00:42:00'),
 Timestamp('2026-06-27 00:43:00'),
 Timestamp('2026-06-27 00:44:00'),
 Timestamp('2026-06-27 00:45:00'),
 Timestamp('2026-06-27 00:46:00'),
 Timestamp('2026-06-27 00:47:00'),
 Timestamp('2026-06-27 00:48:00'),
 Timestamp('2026-06-27 00:49:00'),
 Timestamp('2026-06-27 00:50:00'),
 Timestamp('2026-06-27 00:51:00'),
 Timestamp('2026-06-27 00:52:00'),
 Timestamp('2026-06-27 00:53:00'),
 Timestamp('2026-06-27 00:54:00'),
 Timestamp('2026-06-27 00:55:00'),
 Timestamp('2026-06-27 00:56:00'),
 Timestamp('2026-06-27 00:57:00'),
 Timestamp('2026-06-27 00:58:00'),
 Timestamp('2026-06-27 00:59:00'),
 Timestamp('2026-06-27 01:00:00'),
 Timestamp('2026-06-27 01:01:00'),
 Timestamp('2026-06-27 01:02:00'),
 Timestamp('2026-06-27 01:03:00'),
 Timestamp('2026-06-27 01:04:00'),
 Timestamp('2026-06-27 01:05:00'),
 Timestamp('2026-06-27 01:06:00'),
 Timestamp('2026-06-27 01:07:00'),
 Timestamp('2026-06-27 01:08:00'),
 Timestamp('2026-06-27 01:09:00'),
 Timestamp('2026-06-27 01:10:00'),
 Timestamp('2026-06-27 01:11:00'),
 Timestamp('2026-06-27 01:12:00'),
 Timestamp('2026-06-27 01:13:00'),
 Timestamp('2026-06-27 01:14:00'),
 Timestamp('2026-06-27 01:15:00'),
 Timestamp('2026-06-27 01:16:00'),
 Timestamp('2026-06-27 01:17:00'),
 Timestamp('2026-06-27 01:18:00'),
 Timestamp('2026-06-27 01:19:00'),
 Timestamp('2026-06-27 01:20:00'),
 Timestamp('2026-06-27 01:21:00'),
 Timestamp('2026-06-27 01:22:00'),
 Timestamp('2026-06-27 01:23:00'),
 Timestamp('2026-06-27 01:24:00'),
 Timestamp('2026-06-27 01:25:00'),
 Timestamp('2026-06-27 01:26:00'),
 Timestamp('2026-06-27 01:27:00'),
 Timestamp('2026-06-27 01:28:00'),
 Timestamp('2026-06-27 01:29:00'),
 Timestamp('2026-06-27 01:30:00'),
 Timestamp('2026-06-27 01:31:00'),
 Timestamp('2026-06-27 01:32:00'),
 Timestamp('2026-06-27 01:33:00'),
 Timestamp('2026-06-27 01:34:00'),
 Timestamp('2026-06-27 01:35:00'),
 Timestamp('2026-06-27 01:36:00'),
 Timestamp('2026-06-27 01:37:00'),
 Timestamp('2026-06-27 01:38:00'),
 Timestamp('2026-06-27 01:39:00'),
 Timestamp('2026-06-27 01:40:00'),
 Timestamp('2026-06-27 01:41:00'),
 Timestamp('2026-06-27 01:42:00'),
 Timestamp('2026-06-27 01:43:00'),
 Timestamp('2026-06-27 01:44:00'),
 Timestamp('2026-06-27 01:45:00'),
 Timestamp('2026-06-27 01:46:00'),
 Timestamp('2026-06-27 01:47:00'),
 Timestamp('2026-06-27 01:48:00'),
 Timestamp('2026-06-27 01:49:00'),
 Timestamp('2026-06-27 01:50:00'),
 Timestamp('2026-06-27 01:51:00'),
 Timestamp('2026-06-27 01:52:00'),
 Timestamp('2026-06-27 01:53:00'),
 Timestamp('2026-06-27 01:54:00'),
 Timestamp('2026-06-27 01:55:00'),
 Timestamp('2026-06-27 01:56:00'),
 Timestamp('2026-06-27 01:57:00'),
 Timestamp('2026-06-27 01:58:00'),
 Timestamp('2026-06-27 01:59:00'),
 Timestamp('2026-06-27 02:00:00'),
 Timestamp('2026-06-27 02:01:00'),
 Timestamp('2026-06-27 02:02:00'),
 Timestamp('2026-06-27 02:03:00'),
 Timestamp('2026-06-27 02:04:00'),
 Timestamp('2026-06-27 02:05:00'),
 Timestamp('2026-06-27 02:06:00'),
 Timestamp('2026-06-27 02:07:00'),
 Timestamp('2026-06-27 02:08:00'),
 Timestamp('2026-06-27 02:09:00'),
 Timestamp('2026-06-27 02:10:00'),
 Timestamp('2026-06-27 02:11:00'),
 Timestamp('2026-06-27 02:12:00'),
 Timestamp('2026-06-27 02:13:00'),
 Timestamp('2026-06-27 02:14:00'),
 Timestamp('2026-06-27 02:15:00'),
 Timestamp('2026-06-27 02:16:00'),
 Timestamp('2026-06-27 02:17:00'),
 Timestamp('2026-06-27 02:18:00'),
 Timestamp('2026-06-27 02:19:00'),
 Timestamp('2026-06-27 02:20:00'),
 Timestamp('2026-06-27 02:21:00'),
 Timestamp('2026-06-27 02:22:00'),
 Timestamp('2026-06-27 02:23:00'),
 Timestamp('2026-06-27 02:24:00'),
 Timestamp('2026-06-27 02:25:00'),
 Timestamp('2026-06-27 02:26:00'),
 Timestamp('2026-06-27 02:27:00'),
 Timestamp('2026-06-27 02:28:00'),
 Timestamp('2026-06-27 02:29:00'),
 Timestamp('2026-06-27 02:30:00'),
 Timestamp('2026-06-27 02:31:00'),
 Timestamp('2026-06-27 02:32:00'),
 Timestamp('2026-06-27 02:33:00'),
 Timestamp('2026-06-27 02:34:00'),
 Timestamp('2026-06-27 02:35:00'),
 Timestamp('2026-06-27 02:36:00'),
 Timestamp('2026-06-27 02:37:00'),
 Timestamp('2026-06-27 02:38:00'),
 Timestamp('2026-06-27 02:39:00'),
 Timestamp('2026-06-27 02:40:00'),
 Timestamp('2026-06-27 02:41:00'),
 Timestamp('2026-06-27 02:42:00'),
 Timestamp('2026-06-27 02:43:00'),
 Timestamp('2026-06-27 02:44:00'),
 Timestamp('2026-06-27 02:45:00'),
 Timestamp('2026-06-27 02:46:00'),
 Timestamp('2026-06-27 02:47:00'),
 Timestamp('2026-06-27 02:48:00'),
 Timestamp('2026-06-27 02:49:00'),
 Timestamp('2026-06-27 02:50:00'),
 Timestamp('2026-06-27 02:51:00'),
 Timestamp('2026-06-27 02:52:00'),
 Timestamp('2026-06-27 02:53:00'),
 Timestamp('2026-06-27 02:54:00'),
 Timestamp('2026-06-27 02:55:00'),
 Timestamp('2026-06-27 02:56:00'),
 Timestamp('2026-06-27 02:57:00'),
 Timestamp('2026-06-27 02:58:00'),
 Timestamp('2026-06-27 02:59:00'),
 Timestamp('2026-06-27 03:00:00'),
 Timestamp('2026-06-27 03:01:00'),
 Timestamp('2026-06-27 03:02:00'),
 Timestamp('2026-06-27 03:03:00'),
 Timestamp('2026-06-27 03:04:00'),
 Timestamp('2026-06-27 03:05:00'),
 Timestamp('2026-06-27 03:06:00'),
 Timestamp('2026-06-27 03:07:00'),
 Timestamp('2026-06-27 03:08:00'),
 Timestamp('2026-06-27 03:09:00'),
 Timestamp('2026-06-27 03:10:00'),
 Timestamp('2026-06-27 03:11:00'),
 Timestamp('2026-06-27 03:12:00'),
 Timestamp('2026-06-27 03:13:00'),
 Timestamp('2026-06-27 03:14:00'),
 Timestamp('2026-06-27 03:15:00'),
 Timestamp('2026-06-27 03:16:00'),
 Timestamp('2026-06-27 03:17:00'),
 Timestamp('2026-06-27 03:18:00'),
 Timestamp('2026-06-27 03:19:00'),
 Timestamp('2026-06-27 03:20:00'),
 Timestamp('2026-06-27 03:21:00'),
 Timestamp('2026-06-27 03:22:00'),
 Timestamp('2026-06-27 03:23:00'),
 Timestamp('2026-06-27 03:24:00'),
 Timestamp('2026-06-27 03:25:00'),
 Timestamp('2026-06-27 03:26:00'),
 Timestamp('2026-06-27 03:27:00'),
 Timestamp('2026-06-27 03:28:00'),
 Timestamp('2026-06-27 03:29:00'),
 Timestamp('2026-06-27 03:30:00'),
 Timestamp('2026-06-27 03:31:00'),
 Timestamp('2026-06-27 03:32:00'),
 Timestamp('2026-06-27 03:33:00'),
 Timestamp('2026-06-27 03:34:00'),
 Timestamp('2026-06-27 03:35:00'),
 Timestamp('2026-06-27 03:36:00'),
 Timestamp('2026-06-27 03:37:00'),
 Timestamp('2026-06-27 03:38:00'),
 Timestamp('2026-06-27 03:39:00'),
 Timestamp('2026-06-27 03:40:00'),
 Timestamp('2026-06-27 03:41:00'),
 Timestamp('2026-06-27 03:42:00'),
 Timestamp('2026-06-27 03:43:00'),
 Timestamp('2026-06-27 03:44:00'),
 Timestamp('2026-06-27 03:45:00'),
 Timestamp('2026-06-27 03:47:00'),
 Timestamp('2026-06-27 03:48:00'),
 Timestamp('2026-06-27 03:49:00'),
 Timestamp('2026-06-27 03:50:00'),
 Timestamp('2026-06-27 03:51:00'),
 Timestamp('2026-06-27 03:52:00'),
 Timestamp('2026-06-27 03:53:00'),
 Timestamp('2026-06-27 03:55:00'),
 Timestamp('2026-06-27 03:56:00'),
 Timestamp('2026-06-27 03:57:00'),
 Timestamp('2026-06-27 04:00:00'),
 Timestamp('2026-06-27 04:01:00'),
 Timestamp('2026-06-27 04:02:00'),
 Timestamp('2026-06-27 04:04:00'),
 Timestamp('2026-06-27 04:05:00'),
 Timestamp('2026-06-27 04:06:00'),
 Timestamp('2026-06-27 04:08:00'),
 Timestamp('2026-06-27 04:11:00'),
 Timestamp('2026-06-27 04:13:00'),
 Timestamp('2026-06-27 04:14:00'),
 Timestamp('2026-06-27 04:15:00'),
 Timestamp('2026-06-27 04:16:00'),
 Timestamp('2026-06-27 04:17:00'),
 Timestamp('2026-06-27 04:18:00'),
 Timestamp('2026-06-27 04:19:00'),
 Timestamp('2026-06-27 04:21:00'),
 Timestamp('2026-06-27 04:23:00'),
 Timestamp('2026-06-27 04:24:00'),
 Timestamp('2026-06-27 04:25:00'),
 Timestamp('2026-06-27 04:27:00'),
 Timestamp('2026-06-27 04:28:00'),
 Timestamp('2026-06-27 04:29:00'),
 Timestamp('2026-06-27 04:31:00'),
 Timestamp('2026-06-27 04:33:00'),
 Timestamp('2026-06-27 04:35:00'),
 Timestamp('2026-06-27 04:38:00'),
 Timestamp('2026-06-27 04:39:00'),
 Timestamp('2026-06-27 04:42:00'),
 Timestamp('2026-06-27 04:45:00'),
 Timestamp('2026-06-27 04:47:00'),
 Timestamp('2026-06-27 04:57:00'),
 Timestamp('2026-06-27 04:59:00'),
 Timestamp('2026-06-27 05:02:00'),
 Timestamp('2026-06-27 05:03:00'),
 Timestamp('2026-06-27 05:08:00'),
 Timestamp('2026-06-27 05:18:00'),
 Timestamp('2026-06-27 05:22:00'),
 Timestamp('2026-06-27 05:23:00'),
 Timestamp('2026-06-27 05:25:00'),
 Timestamp('2026-06-27 05:30:00'),
 Timestamp('2026-06-27 05:31:00'),
 Timestamp('2026-06-27 05:43:00'),
 Timestamp('2026-06-27 05:47:00'),
 Timestamp('2026-06-27 05:51:00'),
 Timestamp('2026-06-27 06:28:00'),
 Timestamp('2026-06-27 18:00:00'),
 Timestamp('2026-06-27 18:12:00'),
 Timestamp('2026-06-27 18:19:00'),
 Timestamp('2026-06-27 18:25:00'),
 Timestamp('2026-06-27 18:27:00'),
 Timestamp('2026-06-27 18:30:00'),
 Timestamp('2026-06-27 18:35:00'),
 Timestamp('2026-06-27 18:36:00'),
 Timestamp('2026-06-27 18:41:00'),
 Timestamp('2026-06-27 18:42:00'),
 Timestamp('2026-06-27 18:44:00'),
 Timestamp('2026-06-27 18:46:00'),
 Timestamp('2026-06-27 18:48:00'),
 Timestamp('2026-06-27 18:49:00'),
 Timestamp('2026-06-27 18:50:00'),
 Timestamp('2026-06-27 18:53:00'),
 Timestamp('2026-06-27 18:54:00'),
 Timestamp('2026-06-27 18:56:00'),
 Timestamp('2026-06-27 18:57:00'),
 Timestamp('2026-06-27 18:59:00'),
 Timestamp('2026-06-27 19:03:00'),
 Timestamp('2026-06-27 19:04:00'),
 Timestamp('2026-06-27 19:07:00'),
 Timestamp('2026-06-27 19:08:00'),
 Timestamp('2026-06-27 19:09:00'),
 Timestamp('2026-06-27 19:10:00'),
 Timestamp('2026-06-27 19:11:00'),
 Timestamp('2026-06-27 19:12:00'),
 Timestamp('2026-06-27 19:13:00'),
 Timestamp('2026-06-27 19:14:00'),
 Timestamp('2026-06-27 19:15:00'),
 Timestamp('2026-06-27 19:16:00'),
 Timestamp('2026-06-27 19:17:00'),
 Timestamp('2026-06-27 19:18:00'),
 Timestamp('2026-06-27 19:20:00'),
 Timestamp('2026-06-27 19:21:00'),
 Timestamp('2026-06-27 19:22:00'),
 Timestamp('2026-06-27 19:23:00'),
 Timestamp('2026-06-27 19:24:00'),
 Timestamp('2026-06-27 19:25:00'),
 Timestamp('2026-06-27 19:26:00'),
 Timestamp('2026-06-27 19:27:00'),
 Timestamp('2026-06-27 19:28:00'),
 Timestamp('2026-06-27 19:29:00'),
 Timestamp('2026-06-27 19:30:00'),
 Timestamp('2026-06-27 19:31:00'),
 Timestamp('2026-06-27 19:32:00'),
 Timestamp('2026-06-27 19:33:00'),
 Timestamp('2026-06-27 19:34:00'),
 Timestamp('2026-06-27 19:36:00'),
 Timestamp('2026-06-27 19:37:00'),
 Timestamp('2026-06-27 19:38:00'),
 Timestamp('2026-06-27 19:39:00'),
 Timestamp('2026-06-27 19:40:00'),
 Timestamp('2026-06-27 19:41:00'),
 Timestamp('2026-06-27 19:43:00'),
 Timestamp('2026-06-27 19:44:00'),
 Timestamp('2026-06-27 19:45:00'),
 Timestamp('2026-06-27 19:46:00'),
 Timestamp('2026-06-27 19:47:00'),
 Timestamp('2026-06-27 19:48:00'),
 Timestamp('2026-06-27 19:49:00'),
 Timestamp('2026-06-27 19:50:00'),
 Timestamp('2026-06-27 19:51:00'),
 Timestamp('2026-06-27 19:52:00'),
 Timestamp('2026-06-27 19:53:00'),
 Timestamp('2026-06-27 19:54:00'),
 Timestamp('2026-06-27 19:55:00'),
 Timestamp('2026-06-27 19:56:00'),
 Timestamp('2026-06-27 19:57:00'),
 Timestamp('2026-06-27 19:58:00'),
 Timestamp('2026-06-27 19:59:00'),
 Timestamp('2026-06-27 20:00:00'),
 Timestamp('2026-06-27 20:01:00'),
 Timestamp('2026-06-27 20:02:00'),
 Timestamp('2026-06-27 20:03:00'),
 Timestamp('2026-06-27 20:04:00'),
 Timestamp('2026-06-27 20:05:00'),
 Timestamp('2026-06-27 20:06:00'),
 Timestamp('2026-06-27 20:07:00'),
 Timestamp('2026-06-27 20:08:00'),
 Timestamp('2026-06-27 20:09:00'),
 Timestamp('2026-06-27 20:10:00'),
 Timestamp('2026-06-27 20:11:00'),
 Timestamp('2026-06-27 20:12:00'),
 Timestamp('2026-06-27 20:13:00'),
 Timestamp('2026-06-27 20:14:00'),
 Timestamp('2026-06-27 20:15:00'),
 Timestamp('2026-06-27 20:16:00'),
 Timestamp('2026-06-27 20:17:00'),
 Timestamp('2026-06-27 20:18:00'),
 Timestamp('2026-06-27 20:19:00'),
 Timestamp('2026-06-27 20:20:00'),
 Timestamp('2026-06-27 20:21:00'),
 Timestamp('2026-06-27 20:22:00'),
 Timestamp('2026-06-27 20:23:00'),
 Timestamp('2026-06-27 20:24:00'),
 Timestamp('2026-06-27 20:25:00'),
 Timestamp('2026-06-27 20:26:00'),
 Timestamp('2026-06-27 20:27:00'),
 Timestamp('2026-06-27 20:28:00'),
 Timestamp('2026-06-27 20:29:00'),
 Timestamp('2026-06-27 20:30:00'),
 Timestamp('2026-06-27 20:31:00'),
 Timestamp('2026-06-27 20:32:00'),
 Timestamp('2026-06-27 20:33:00'),
 Timestamp('2026-06-27 20:34:00'),
 Timestamp('2026-06-27 20:35:00'),
 Timestamp('2026-06-27 20:36:00'),
 Timestamp('2026-06-27 20:37:00'),
 Timestamp('2026-06-27 20:38:00'),
 Timestamp('2026-06-27 20:39:00'),
 Timestamp('2026-06-27 20:40:00'),
 Timestamp('2026-06-27 20:41:00'),
 Timestamp('2026-06-27 20:42:00'),
 Timestamp('2026-06-27 20:43:00'),
 Timestamp('2026-06-27 20:44:00'),
 Timestamp('2026-06-27 20:45:00'),
 Timestamp('2026-06-27 20:46:00'),
 Timestamp('2026-06-27 20:47:00'),
 Timestamp('2026-06-27 20:48:00'),
 Timestamp('2026-06-27 20:49:00'),
 Timestamp('2026-06-27 20:50:00'),
 Timestamp('2026-06-27 20:51:00'),
 Timestamp('2026-06-27 20:52:00'),
 Timestamp('2026-06-27 20:53:00'),
 Timestamp('2026-06-27 20:54:00'),
 Timestamp('2026-06-27 20:55:00'),
 Timestamp('2026-06-27 20:56:00'),
 Timestamp('2026-06-27 20:57:00'),
 Timestamp('2026-06-27 20:58:00'),
 Timestamp('2026-06-27 20:59:00'),
 Timestamp('2026-06-27 21:00:00'),
 Timestamp('2026-06-27 21:01:00'),
 Timestamp('2026-06-27 21:02:00'),
 Timestamp('2026-06-27 21:03:00'),
 Timestamp('2026-06-27 21:04:00'),
 Timestamp('2026-06-27 21:05:00'),
 Timestamp('2026-06-27 21:06:00'),
 Timestamp('2026-06-27 21:07:00'),
 Timestamp('2026-06-27 21:08:00'),
 Timestamp('2026-06-27 21:09:00'),
 Timestamp('2026-06-27 21:10:00'),
 Timestamp('2026-06-27 21:11:00'),
 Timestamp('2026-06-27 21:12:00'),
 Timestamp('2026-06-27 21:13:00'),
 Timestamp('2026-06-27 21:14:00'),
 Timestamp('2026-06-27 21:15:00'),
 Timestamp('2026-06-27 21:16:00'),
 Timestamp('2026-06-27 21:17:00'),
 Timestamp('2026-06-27 21:18:00'),
 Timestamp('2026-06-27 21:19:00'),
 Timestamp('2026-06-27 21:20:00'),
 Timestamp('2026-06-27 21:21:00'),
 Timestamp('2026-06-27 21:22:00'),
 Timestamp('2026-06-27 21:23:00'),
 Timestamp('2026-06-27 21:24:00'),
 Timestamp('2026-06-27 21:25:00'),
 Timestamp('2026-06-27 21:26:00'),
 Timestamp('2026-06-27 21:27:00'),
 Timestamp('2026-06-27 21:28:00'),
 Timestamp('2026-06-27 21:29:00'),
 Timestamp('2026-06-27 21:30:00'),
 Timestamp('2026-06-27 21:31:00'),
 Timestamp('2026-06-27 21:32:00'),
 Timestamp('2026-06-27 21:33:00'),
 Timestamp('2026-06-27 21:34:00'),
 Timestamp('2026-06-27 21:35:00'),
 Timestamp('2026-06-27 21:36:00'),
 Timestamp('2026-06-27 21:37:00'),
 Timestamp('2026-06-27 21:38:00'),
 Timestamp('2026-06-27 21:39:00'),
 Timestamp('2026-06-27 21:40:00'),
 Timestamp('2026-06-27 21:41:00'),
 Timestamp('2026-06-27 21:42:00'),
 Timestamp('2026-06-27 21:43:00'),
 Timestamp('2026-06-27 21:44:00'),
 Timestamp('2026-06-27 21:45:00'),
 Timestamp('2026-06-27 21:46:00'),
 Timestamp('2026-06-27 21:47:00'),
 Timestamp('2026-06-27 21:48:00'),
 Timestamp('2026-06-27 21:49:00'),
 Timestamp('2026-06-27 21:50:00'),
 Timestamp('2026-06-27 21:51:00'),
 Timestamp('2026-06-27 21:52:00'),
 Timestamp('2026-06-27 21:53:00'),
 Timestamp('2026-06-27 21:54:00'),
 Timestamp('2026-06-27 21:55:00'),
 Timestamp('2026-06-27 21:56:00'),
 Timestamp('2026-06-27 21:57:00'),
 Timestamp('2026-06-27 21:58:00'),
 Timestamp('2026-06-27 21:59:00'),
 Timestamp('2026-06-27 22:00:00'),
 Timestamp('2026-06-27 22:01:00'),
 Timestamp('2026-06-27 22:02:00'),
 Timestamp('2026-06-27 22:03:00'),
 Timestamp('2026-06-27 22:04:00'),
 Timestamp('2026-06-27 22:05:00'),
 Timestamp('2026-06-27 22:06:00'),
 Timestamp('2026-06-27 22:07:00'),
 Timestamp('2026-06-27 22:08:00'),
 Timestamp('2026-06-27 22:09:00'),
 Timestamp('2026-06-27 22:10:00'),
 Timestamp('2026-06-27 22:11:00'),
 Timestamp('2026-06-27 22:12:00'),
 Timestamp('2026-06-27 22:13:00'),
 Timestamp('2026-06-27 22:14:00'),
 Timestamp('2026-06-27 22:15:00'),
 Timestamp('2026-06-27 22:16:00'),
 Timestamp('2026-06-27 22:17:00'),
 Timestamp('2026-06-27 22:18:00'),
 Timestamp('2026-06-27 22:19:00'),
 Timestamp('2026-06-27 22:20:00'),
 Timestamp('2026-06-27 22:21:00'),
 Timestamp('2026-06-27 22:22:00'),
 Timestamp('2026-06-27 22:23:00'),
 Timestamp('2026-06-27 22:24:00'),
 Timestamp('2026-06-27 22:25:00'),
 Timestamp('2026-06-27 22:26:00'),
 Timestamp('2026-06-27 22:27:00'),
 Timestamp('2026-06-27 22:28:00'),
 Timestamp('2026-06-27 22:29:00'),
 Timestamp('2026-06-27 22:30:00'),
 Timestamp('2026-06-27 22:31:00'),
 Timestamp('2026-06-27 22:32:00'),
 Timestamp('2026-06-27 22:33:00'),
 Timestamp('2026-06-27 22:34:00'),
 Timestamp('2026-06-27 22:35:00'),
 Timestamp('2026-06-27 22:36:00'),
 Timestamp('2026-06-27 22:37:00'),
 Timestamp('2026-06-27 22:38:00'),
 Timestamp('2026-06-27 22:39:00'),
 Timestamp('2026-06-27 22:40:00'),
 Timestamp('2026-06-27 22:41:00'),
 Timestamp('2026-06-27 22:42:00'),
 Timestamp('2026-06-27 22:43:00'),
 Timestamp('2026-06-27 22:44:00'),
 Timestamp('2026-06-27 22:45:00'),
 Timestamp('2026-06-27 22:46:00'),
 Timestamp('2026-06-27 22:47:00'),
 Timestamp('2026-06-27 22:48:00'),
 Timestamp('2026-06-27 22:49:00'),
 Timestamp('2026-06-27 22:50:00'),
 Timestamp('2026-06-27 22:51:00'),
 Timestamp('2026-06-27 22:52:00'),
 Timestamp('2026-06-27 22:53:00'),
 Timestamp('2026-06-27 22:54:00'),
 Timestamp('2026-06-27 22:55:00'),
 Timestamp('2026-06-27 22:56:00'),
 Timestamp('2026-06-27 22:57:00'),
 Timestamp('2026-06-27 22:58:00'),
 Timestamp('2026-06-27 22:59:00'),
 Timestamp('2026-06-27 23:00:00'),
 Timestamp('2026-06-27 23:01:00'),
 Timestamp('2026-06-27 23:02:00'),
 Timestamp('2026-06-27 23:03:00'),
 Timestamp('2026-06-27 23:04:00'),
 Timestamp('2026-06-27 23:05:00'),
 Timestamp('2026-06-27 23:06:00'),
 Timestamp('2026-06-27 23:07:00'),
 Timestamp('2026-06-27 23:08:00'),
 Timestamp('2026-06-27 23:09:00'),
 Timestamp('2026-06-27 23:10:00'),
 Timestamp('2026-06-27 23:11:00'),
 Timestamp('2026-06-27 23:12:00'),
 Timestamp('2026-06-27 23:13:00'),
 Timestamp('2026-06-27 23:14:00'),
 Timestamp('2026-06-27 23:15:00'),
 Timestamp('2026-06-27 23:16:00'),
 Timestamp('2026-06-27 23:17:00'),
 Timestamp('2026-06-27 23:18:00'),
 Timestamp('2026-06-27 23:19:00'),
 Timestamp('2026-06-27 23:20:00'),
 Timestamp('2026-06-27 23:21:00'),
 Timestamp('2026-06-27 23:22:00'),
 Timestamp('2026-06-27 23:23:00'),
 Timestamp('2026-06-27 23:24:00'),
 Timestamp('2026-06-27 23:25:00'),
 Timestamp('2026-06-27 23:26:00'),
 Timestamp('2026-06-27 23:27:00'),
 Timestamp('2026-06-27 23:28:00'),
 Timestamp('2026-06-27 23:29:00'),
 Timestamp('2026-06-27 23:30:00'),
 Timestamp('2026-06-27 23:31:00'),
 Timestamp('2026-06-27 23:32:00'),
 Timestamp('2026-06-27 23:33:00'),
 Timestamp('2026-06-27 23:34:00'),
 Timestamp('2026-06-27 23:35:00'),
 Timestamp('2026-06-27 23:36:00'),
 Timestamp('2026-06-27 23:37:00'),

In [64]:
df['WT_cat'] = 0

In [65]:
df.loc[(df['Wake_Up_Time'] >= "2026-06-27 04:00:00") &
       (df['Wake_Up_Time'] < "2026-06-27 06:00:00"), "WT_cat"]=0
df.loc[(df['Wake_Up_Time'] >= "2026-06-27 06:00:00") &
       (df['Wake_Up_Time'] < "2026-06-27 08:00:00"), "WT_cat"]=1
df.loc[(df['Wake_Up_Time'] >= "2026-06-27 08:00:00") &
       (df['Wake_Up_Time'] < "2026-06-27 10:00:00"), "WT_cat"]=2
df.loc[(df['Wake_Up_Time'] >= "2026-06-27 10:00:00") &
       (df['Wake_Up_Time'] <= "2026-06-27 11:00:00"), "WT_cat"]=3

In [66]:
df['WT_cat'].unique()

array([2, 1, 0, 3])

In [67]:
df['ST_cat'] = 0

In [68]:
df.loc[(df['Sleep_Time'] >= "2026-06-27 20:00:00") &
       (df['Sleep_Time'] < "2026-06-27 22:00:00"), "ST_cat"]=0
df.loc[(df['Sleep_Time'] >= "2026-06-27 22:00:00") &
       (df['Sleep_Time'] <= "2026-06-27 23:59:00"), "ST_cat"]=1
df.loc[(df['Sleep_Time'] >= "2026-06-27 00:00:00") &
       (df['Sleep_Time'] < "2026-06-27 03:00:00"), "ST_cat"]=2
df.loc[(df['Sleep_Time'] >= "2026-06-27 03:00:00") &
       (df['Sleep_Time'] < "2026-06-27 07:00:00"), "ST_cat"]=3
df.loc[(df['Sleep_Time'] >= "2026-06-27 18:00:00") &
       (df['Sleep_Time'] < "2026-06-27 20:00:00"), "ST_cat"]=4

In [69]:
df['ST_cat'].unique()

array([2, 1, 0, 4, 3])

In [70]:
df.drop(columns=['Wake_Up_Time',
                 'Sleep_Time'],inplace=True)

In [71]:
df.shape

(10000, 50)

In [72]:
df.columns

Index(['Age', 'Gender', 'BMI', 'Country', 'Occupation', 'Marital_Status',
       'Sleep_Duration_Hours', 'Sleep_Quality_Score',
       'Number_of_Night_Awakenings', 'Weekend_Sleep_Difference_Hours',
       'Nap_Frequency_Per_Week', 'Screen_Time_Before_Bed_Hours',
       'Exercise_Frequency_Per_Week', 'Exercise_Duration_Minutes',
       'Exercise_Type', 'Daily_Steps', 'Morning_Workout', 'Workout_Intensity',
       'Daily_Calorie_Intake', 'Water_Intake_Liters', 'Fruit_Intake_Per_Day',
       'Vegetable_Intake_Per_Day', 'Protein_Intake_Grams',
       'Sugary_Drinks_Per_Week', 'Fast_Food_Meals_Per_Week',
       'Breakfast_Regularity_Score', 'Smoking_Status', 'Alcohol_Consumption',
       'Stress_Level', 'Working_Hours_Per_Day', 'Sitting_Hours_Per_Day',
       'Outdoor_Time_Hours', 'Social_Interaction_Score', 'Meditation_Practice',
       'Resting_Heart_Rate', 'Systolic_BP', 'Diastolic_BP',
       'Cholesterol_Level', 'Blood_Sugar_Level', 'Energy_Level_Score',
       'Fatigue_Level_Score', 'Immune_Health_Score', 'Mood_Score',
       'Anxiety_Score', 'Productivity_Score', 'Focus_Concentration_Score',
       'Life_Satisfaction_Score', 'Fitness_Level', 'WT_cat', 'ST_cat'],
      dtype='object')

# Fill missing values

In [73]:
df.isnull().sum()#

Age                                  0
Gender                               0
BMI                                  0
Country                              0
Occupation                           0
Marital_Status                       0
Sleep_Duration_Hours                 0
Sleep_Quality_Score                  0
Number_of_Night_Awakenings           0
Weekend_Sleep_Difference_Hours       0
Nap_Frequency_Per_Week               0
Screen_Time_Before_Bed_Hours         0
Exercise_Frequency_Per_Week          0
Exercise_Duration_Minutes            0
Exercise_Type                      824
Daily_Steps                          0
Morning_Workout                      0
Workout_Intensity                  824
Daily_Calorie_Intake                 0
Water_Intake_Liters                  0
Fruit_Intake_Per_Day                 0
Vegetable_Intake_Per_Day             0
Protein_Intake_Grams                 0
Sugary_Drinks_Per_Week               0
Fast_Food_Meals_Per_Week             0
Breakfast_Regularity_Score           0
Smoking_Status                       0
Alcohol_Consumption               3014
Stress_Level                         0
Working_Hours_Per_Day                0
Sitting_Hours_Per_Day                0
Outdoor_Time_Hours                   0
Social_Interaction_Score             0
Meditation_Practice                  0
Resting_Heart_Rate                   0
Systolic_BP                          0
Diastolic_BP                         0
Cholesterol_Level                    0
Blood_Sugar_Level                    0
Energy_Level_Score                   0
Fatigue_Level_Score                  0
Immune_Health_Score                  0
Mood_Score                           0
Anxiety_Score                        0
Productivity_Score                   0
Focus_Concentration_Score            0
Life_Satisfaction_Score              0
Fitness_Level                        0
WT_cat                               0
ST_cat                               0
dtype: int64

In [74]:
df.loc[df['Alcohol_Consumption'].isna() == True,
       'Alcohol_Consumption'] = 0

In [75]:
df[['Exercise_Type','Workout_Intensity']].mode().iloc[0]

Exercise_Type        Weight Training
Workout_Intensity           Moderate
Name: 0, dtype: object

In [76]:
fill_value = df.mode().iloc[0]
df.fillna(fill_value,inplace=True)

In [77]:
df.isnull().sum().sum()

np.int64(0)

# Handle ordinal columns

label encoding

In [78]:
df['Workout_Intensity'].unique()

array(['Low', 'Moderate', 'High'], dtype=object)

In [79]:
df['Smoking_Status'].unique()

array(['Former', 'Current', 'Never'], dtype=object)

In [80]:
df['Alcohol_Consumption'].unique()

array(['Moderate', 0, 'Light', 'Heavy'], dtype=object)

In [81]:
label_map={'Workout_Intensity':{'Low':0, 'Moderate':1, 'High':2},
  'Smoking_Status':{'Former':1, 'Current':2, 'Never':0},
  'Alcohol_Consumption':{'Moderate':2, 'Light':1, 'Heavy':3}
}

In [82]:
df.replace(label_map,inplace=True)

/tmp/ipykernel_3928/1715271054.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(label_map,inplace=True)

In [83]:
df['Alcohol_Consumption'].unique()

array([2, 0, 1, 3])

In [84]:
df['Smoking_Status'].unique()

array([1, 2, 0])

In [85]:
df['Workout_Intensity'].unique()

array([0, 1, 2])

# Check

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 50 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Age                             10000 non-null  int64
 1   Gender                          10000 non-null  object
 2   BMI                             10000 non-null  float64
 3   Country                         10000 non-null  object
 4   Occupation                      10000 non-null  object
 5   Marital_Status                  10000 non-null  object
 6   Sleep_Duration_Hours            10000 non-null  float64
 7   Sleep_Quality_Score             10000 non-null  float64
 8   Number_of_Night_Awakenings      10000 non-null  int64
 9   Weekend_Sleep_Difference_Hours  10000 non-null  float64
 10  Nap_Frequency_Per_Week          10000 non-null  int64
 11  Screen_Time_Before_Bed_Hours    10000 non-null  float64
 12  Exercise_Frequency_Per_Week     10000 non-null  int64
 13  Exercise_Duration_Minutes       10000 non-null  int64
 14  Exercise_Type                   10000 non-null  object
 15  Daily_Steps                     10000 non-null  int64
 16  Morning_Workout                 10000 non-null  object
 17  Workout_Intensity               10000 non-null  int64
 18  Daily_Calorie_Intake            10000 non-null  int64
 19  Water_Intake_Liters             10000 non-null  float64
 20  Fruit_Intake_Per_Day            10000 non-null  int64
 21  Vegetable_Intake_Per_Day        10000 non-null  int64
 22  Protein_Intake_Grams            10000 non-null  float64
 23  Sugary_Drinks_Per_Week          10000 non-null  int64
 24  Fast_Food_Meals_Per_Week        10000 non-null  int64
 25  Breakfast_Regularity_Score      10000 non-null  float64
 26  Smoking_Status                  10000 non-null  int64
 27  Alcohol_Consumption             10000 non-null  int64
 28  Stress_Level                    10000 non-null  float64
 29  Working_Hours_Per_Day           10000 non-null  float64
 30  Sitting_Hours_Per_Day           10000 non-null  float64
 31  Outdoor_Time_Hours              10000 non-null  float64
 32  Social_Interaction_Score        10000 non-null  float64
 33  Meditation_Practice             10000 non-null  object
 34  Resting_Heart_Rate              10000 non-null  int64
 35  Systolic_BP                     10000 non-null  int64
 36  Diastolic_BP                    10000 non-null  int64
 37  Cholesterol_Level               10000 non-null  float64
 38  Blood_Sugar_Level               10000 non-null  float64
 39  Energy_Level_Score              10000 non-null  float64
 40  Fatigue_Level_Score             10000 non-null  float64
 41  Immune_Health_Score             10000 non-null  float64
 42  Mood_Score                      10000 non-null  float64
 43  Anxiety_Score                   10000 non-null  float64
 44  Productivity_Score              10000 non-null  float64
 45  Focus_Concentration_Score       10000 non-null  float64
 46  Life_Satisfaction_Score         10000 non-null  float64
 47  Fitness_Level                   10000 non-null  object
 48  WT_cat                          10000 non-null  int64
 49  ST_cat                          10000 non-null  int64
dtypes: float64(23), int64(19), object(8)
memory usage: 3.8+ MB

# X & Y split

target : fitness level

In [87]:
X = df.drop(columns=['Fitness_Level'])
Y = df['Fitness_Level']
X.shape,Y.shape

((10000, 49), (10000,))

In [88]:
Y.unique()

array(['Excellent', 'Good', 'Average', 'Poor'], dtype=object)

In [89]:
label_map = {'Excellent':3, 'Good':2, 'Average':1, 'Poor':0}
Y.replace(label_map,inplace=True)

/tmp/ipykernel_3928/1394058508.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  Y.replace(label_map,inplace=True)

In [90]:
Y.unique()

array([3, 2, 1, 0])

In [91]:
X_ohe = pd.get_dummies(X)
X_ohe.shape

(10000, 91)

In [92]:
X_ohe.columns

Index(['Age', 'BMI', 'Sleep_Duration_Hours', 'Sleep_Quality_Score',
       'Number_of_Night_Awakenings', 'Weekend_Sleep_Difference_Hours',
       'Nap_Frequency_Per_Week', 'Screen_Time_Before_Bed_Hours',
       'Exercise_Frequency_Per_Week', 'Exercise_Duration_Minutes',
       'Daily_Steps', 'Workout_Intensity', 'Daily_Calorie_Intake',
       'Water_Intake_Liters', 'Fruit_Intake_Per_Day',
       'Vegetable_Intake_Per_Day', 'Protein_Intake_Grams',
       'Sugary_Drinks_Per_Week', 'Fast_Food_Meals_Per_Week',
       'Breakfast_Regularity_Score', 'Smoking_Status', 'Alcohol_Consumption',
       'Stress_Level', 'Working_Hours_Per_Day', 'Sitting_Hours_Per_Day',
       'Outdoor_Time_Hours', 'Social_Interaction_Score', 'Resting_Heart_Rate',
       'Systolic_BP', 'Diastolic_BP', 'Cholesterol_Level', 'Blood_Sugar_Level',
       'Energy_Level_Score', 'Fatigue_Level_Score', 'Immune_Health_Score',
       'Mood_Score', 'Anxiety_Score', 'Productivity_Score',
       'Focus_Concentration_Score', 'Life_Satisfaction_Score', 'WT_cat',
       'ST_cat', 'Gender_Female', 'Gender_Male', 'Gender_Non-binary',
       'Country_Australia', 'Country_Brazil', 'Country_Canada',
       'Country_France', 'Country_Germany', 'Country_India', 'Country_Italy',
       'Country_Japan', 'Country_Mexico', 'Country_Nigeria',
       'Country_Pakistan', 'Country_South Korea', 'Country_Spain',
       'Country_UK', 'Country_USA', 'Occupation_Accountant',
       'Occupation_Artist', 'Occupation_Athlete', 'Occupation_Chef',
       'Occupation_Doctor', 'Occupation_Entrepreneur', 'Occupation_Freelancer',
       'Occupation_Laborer', 'Occupation_Lawyer', 'Occupation_Manager',
       'Occupation_Nurse', 'Occupation_Retired',
       'Occupation_Software Engineer', 'Occupation_Student',
       'Occupation_Teacher', 'Marital_Status_Divorced',
       'Marital_Status_Married', 'Marital_Status_Single',
       'Marital_Status_Widowed', 'Exercise_Type_Cycling', 'Exercise_Type_HIIT',
       'Exercise_Type_Running', 'Exercise_Type_Sports',
       'Exercise_Type_Swimming', 'Exercise_Type_Walking',
       'Exercise_Type_Weight Training', 'Exercise_Type_Yoga',
       'Morning_Workout_No', 'Morning_Workout_Yes', 'Meditation_Practice_No',
       'Meditation_Practice_Yes'],
      dtype='object')

In [93]:
cat_col = X_ohe.columns[X_ohe.nunique() <= 15]
cat_col.shape

(61,)

In [94]:
cont_col = X_ohe.columns[X_ohe.nunique() > 15]
cont_col.shape

(30,)

# Train test split

In [95]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X_ohe,Y,
                                                 test_size=0.3,
                                                 random_state=7,
                                                 stratify=Y)
X_train.shape,X_test.shape,Y_train.shape,Y_test.shape

((7000, 91), (3000, 91), (7000,), (3000,))

In [96]:
from sklearn.preprocessing import RobustScaler
rc= RobustScaler()
X_train[cont_col] = rc.fit_transform(X_train[cont_col])
X_test[cont_col] = rc.transform(X_test[cont_col])

# Outlier imputation using IQR method

In [97]:
def outlier_imputation_iqr(df,col):
  df1 = df.copy()
  q1,q3 = df1[col].quantile([0.25,0.75])
  iqr = q3-q1
  LB = q1 - 1.5*iqr
  UB = q3 + 1.5*iqr
  print("Column -->",col)
  df1.loc[(df1[col]<LB),col] = LB
  df1.loc[(df1[col]>UB),col] = UB
  print(LB,UB, df1[col].min(),df1[col].max())
  return df1

In [98]:
X_train_io = X_train.copy()
for col in cont_col:
  X_train_io = outlier_imputation_iqr(X_train_io,col)

Column --> Age
-1.9642857142857144 2.0357142857142856 -0.8928571428571429 1.3214285714285714
Column --> BMI
-2.0089153046062407 1.9910846953937595 -1.4257057949479945 1.9910846953937595
Column --> Sleep_Duration_Hours
-2.0033557046979866 1.9966442953020134 -2.0033557046979866 1.8523489932885902
Column --> Sleep_Quality_Score
-2.0 2.0 -2.0 1.7272727272727282
Column --> Weekend_Sleep_Difference_Hours
-2.0092592592592595 1.9907407407407407 -1.8888888888888888 1.9907407407407407
Column --> Screen_Time_Before_Bed_Hours
-1.8664122137404582 2.133587786259542 -0.618320610687023 2.133587786259542
Column --> Exercise_Duration_Minutes
-2.0 2.0 -1.6071428571428572 2.0
Column --> Daily_Steps
-2.025921583952065 1.9740784160479354 -1.9954409274456169 1.9740784160479354
Column --> Daily_Calorie_Intake
-1.9973230220107079 2.0026769779892923 -1.9973230220107079 2.0026769779892923
Column --> Water_Intake_Liters
-1.9999999999999996 2.0000000000000004 -1.9999999999999996 2.0000000000000004
Column --> Protein_Intake_Grams
-2.0116959064327484 1.9883040935672516 -1.97953216374269 1.9883040935672516
Column --> Breakfast_Regularity_Score
-2.0000000000000004 1.9999999999999996 -2.0000000000000004 1.0
Column --> Stress_Level
-2.0 2.0 -1.2499999999999998 1.9642857142857142
Column --> Working_Hours_Per_Day
-2.0 2.0 -2.0 2.0
Column --> Sitting_Hours_Per_Day
-1.9999999999999998 2.0 -1.9999999999999998 2.0
Column --> Outdoor_Time_Hours
-1.939153439153439 2.060846560846561 -1.3544973544973544 2.060846560846561
Column --> Social_Interaction_Score
-2.0 2.0 -1.7083333333333333 2.0
Column --> Resting_Heart_Rate
-2.0 2.0 -2.0 2.0
Column --> Systolic_BP
-2.0 2.0 -2.0 2.0
Column --> Diastolic_BP
-2.0 2.0 -2.0 2.0
Column --> Cholesterol_Level
-1.9952076677316297 2.0047923322683703 -1.9952076677316297 2.0047923322683703
Column --> Blood_Sugar_Level
-1.9976452119309256 2.0023547880690726 -1.9976452119309256 2.0023547880690726
Column --> Energy_Level_Score
-2.0 1.9999999999999998 -2.0 1.277777777777778
Column --> Fatigue_Level_Score
-1.9615384615384617 2.0384615384615383 -0.7307692307692308 2.0384615384615383
Column --> Immune_Health_Score
-1.9999999999999996 2.0000000000000004 -1.9999999999999996 2.0000000000000004
Column --> Mood_Score
-2.0294117647058822 1.9705882352941178 -2.0294117647058822 1.8823529411764715
Column --> Anxiety_Score
-2.0238095238095237 1.976190476190476 -1.9999999999999996 1.976190476190476
Column --> Productivity_Score
-1.9666666666666668 2.033333333333333 -1.9666666666666668 2.0
Column --> Focus_Concentration_Score
-2.0384615384615388 1.9615384615384612 -2.0384615384615388 1.9615384615384612
Column --> Life_Satisfaction_Score
-1.966666666666667 2.033333333333333 -1.966666666666667 1.733333333333334

# Feature Selection

## PCA

In [99]:
from sklearn.decomposition import PCA
pca = PCA(n_components=0.95,random_state=7)
X_train_pca = pca.fit_transform(X_train)
X_test_pca = pca.transform(X_test)
X_train_pca.shape, X_test_pca.shape

((7000, 44), (3000, 44))

In [100]:
pca = PCA(n_components=0.95,random_state=7)
X_train_io_pca = pca.fit_transform(X_train_io)
X_test_io_pca = pca.transform(X_test)
X_train_io_pca.shape, X_test_io_pca.shape

((7000, 44), (3000, 44))

## KERNEL PCA

In [101]:
from sklearn.decomposition import KernelPCA
kpca = KernelPCA(kernel='rbf',random_state=7)
X_train_kpca = kpca.fit_transform(X_train)
X_test_kpca = kpca.transform(X_test)
X_train_kpca.shape, X_test_kpca.shape

((7000, 6999), (3000, 6999))

In [102]:
kpca = KernelPCA(kernel='rbf',random_state=7)
X_train_io_kpca = kpca.fit_transform(X_train_io)
X_test_io_kpca = kpca.transform(X_test)
X_train_io_kpca.shape, X_test_io_kpca.shape

((7000, 6999), (3000, 6999))

## RFE

In [103]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
rfe = RFE(LogisticRegression(random_state=7,
                             class_weight="balanced"),
          verbose=2)
rfe.fit(X_train,Y_train)
rfe.ranking_

Fitting estimator with 91 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 90 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 89 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 88 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 87 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 86 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 85 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 84 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 83 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 82 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 81 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 80 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 79 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 78 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 77 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 76 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 75 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 74 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 73 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 72 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 71 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 70 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 69 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 68 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 67 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 66 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 65 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 64 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 63 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 62 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 61 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 60 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 59 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 58 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 57 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 56 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 55 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 54 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 53 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 52 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 51 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 50 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 49 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 48 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 47 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 46 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

array([ 1,  1,  5,  1, 42, 36, 37, 46,  1, 22,  1, 45,  1,  1, 25,  1,  9,
       47,  1, 31,  1, 14,  1, 21, 43, 44,  1, 35, 27, 32, 30, 19, 28, 39,
        1,  1, 10, 29, 40, 13,  3,  4,  1,  1,  1,  1, 20, 18, 16,  1,  1,
        8, 17, 34,  7,  1,  1, 23,  1,  1, 11, 12, 26,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1, 41, 24,  1,  6,  1, 15,  1,  1,  2, 33, 38,  1,
        1,  1,  1,  1,  1,  1])

In [104]:
selected_col = X_train.columns[rfe.ranking_ == 1]
selected_col.shape

(45,)

In [105]:
X_train_rfe = X_train.loc[:,selected_col]
X_test_rfe = X_test.loc[:,selected_col]

In [106]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
rfe = RFE(LogisticRegression(random_state=7,
                             class_weight="balanced"),
          verbose=2)
rfe.fit(X_train_io,Y_train)
rfe.ranking_

Fitting estimator with 91 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 90 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 89 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 88 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 87 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 86 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 85 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 84 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 83 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 82 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 81 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 80 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 79 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 78 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 77 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 76 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 75 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 74 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 73 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 72 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 71 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 70 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 69 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 68 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 67 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 66 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 65 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 64 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 63 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 62 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 61 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 60 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 59 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 58 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 57 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 56 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 55 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 54 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 53 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 52 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 51 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 50 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 49 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 48 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 47 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Fitting estimator with 46 features.

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

array([ 1,  1,  4,  1, 44, 36, 40, 46,  1, 28,  1, 43,  1,  1, 30,  1,  9,
       47,  1, 33,  1, 10,  1, 17, 42, 41,  1, 38, 25, 29, 24, 13, 23, 37,
        1,  1, 12, 26, 39,  6,  2,  3,  1,  1,  1,  1, 32, 22, 21,  1,  1,
        7, 19, 34,  5,  1,  1, 27,  1, 18,  1,  8, 16,  1,  1,  1, 14,  1,
        1,  1,  1,  1,  1, 45, 31,  1, 11,  1, 15,  1,  1,  1, 20, 35,  1,
        1,  1,  1,  1,  1,  1])

In [107]:
selected_col = X_train_io.columns[rfe.ranking_ == 1]
selected_col.shape

(45,)

In [108]:
X_train_io_rfe = X_train_io.loc[:,selected_col]
X_test_io_rfe = X_test.loc[:,selected_col]

## Decision Tree

In [109]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(class_weight="balanced",
                            random_state=7)
dt.fit(X_train,Y_train)

DecisionTreeClassifier(class_weight='balanced', random_state=7)

In [110]:
selected_col = X_train.columns[dt.feature_importances_ >
                               dt.feature_importances_.mean()]
selected_col.shape

(21,)

In [111]:
X_train_dt = X_train.loc[:,selected_col]
X_test_dt = X_test.loc[:,selected_col]

In [112]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(class_weight="balanced",
                            random_state=7)
dt.fit(X_train_io,Y_train)

DecisionTreeClassifier(class_weight='balanced', random_state=7)

In [113]:
selected_col = X_train_io.columns[dt.feature_importances_ >
                               dt.feature_importances_.mean()]
selected_col.shape

(20,)

In [114]:
X_train_io_dt = X_train_io.loc[:,selected_col]
X_test_io_dt = X_test.loc[:,selected_col]

# Apply Models for Multi - Class Classification

 --> TO get the best model for your data and get the best prediction =
 models to select:
atleast 3
1) basic learning -- Like Logistic
--> Random Forest
1 out of XGBoost, CatBoost, Or LGBoost

best performing of the three is selected

# Apply models for multi class classification

Logistic Regression

---

CatBoost

---

RandomForest

---

LightGBM

--
apply on all datasets -- generate 40 different classification report fo each

# # Steps to be done:
1. take the model
2. train the model
3. get the predictions Y_predict and Y_pred_prob
4. Classification Report
5. log loss

# automation:
create a function that will take model,Xtrain,Ytrain,Ytest as a parameter and in turn return precision,recall,f1score log loss, average precision score.

run this function on diff datasets and models and store the list of lists

convert it to a dataframe

compare the results in the dataframe

PLot the results if possible!

In [123]:
data_list = [(X_train,X_test),(X_train_io,X_test),(X_train_pca,X_test_pca),(X_train_io_pca,X_test_io_pca),(X_train_kpca,X_test_kpca),
             (X_train_io_kpca,X_test_io_kpca),(X_train_rfe,X_test_rfe),(X_train_io_rfe,X_test_io_rfe),(X_train_dt,X_test_dt),(X_train_io_dt,X_test_io_dt)]
# All required training datasets for different feature selections

In [124]:
from sklearn.metrics import classification_report
c = 0
for XTrain,XTest in data_list:
  c += 1
  lr = LogisticRegression(random_state=7,class_weight='balanced')
  lr.fit(XTrain,Y_train)
  y_pred = lr.predict(XTest)
  print(f'Classification Report : {c} - {classification_report(Y_test,y_pred)}')

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Classification Report : 1 -               precision    recall  f1-score   support

           0       0.49      0.79      0.61        34
           1       0.80      0.83      0.81       641
           2       0.84      0.79      0.81      1329
           3       0.85      0.88      0.87       996

    accuracy                           0.83      3000
   macro avg       0.75      0.82      0.78      3000
weighted avg       0.83      0.83      0.83      3000

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Classification Report : 2 -               precision    recall  f1-score   support

           0       0.46      0.82      0.59        34
           1       0.80      0.82      0.81       641
           2       0.84      0.79      0.82      1329
           3       0.85      0.89      0.87       996

    accuracy                           0.83      3000
   macro avg       0.74      0.83      0.77      3000
weighted avg       0.83      0.83      0.83      3000

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Classification Report : 3 -               precision    recall  f1-score   support

           0       0.43      0.85      0.57        34
           1       0.78      0.80      0.79       641
           2       0.83      0.77      0.80      1329
           3       0.84      0.88      0.86       996

    accuracy                           0.81      3000
   macro avg       0.72      0.83      0.75      3000
weighted avg       0.82      0.81      0.81      3000

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Classification Report : 4 -               precision    recall  f1-score   support

           0       0.42      0.82      0.55        34
           1       0.78      0.80      0.79       641
           2       0.83      0.77      0.80      1329
           3       0.84      0.88      0.86       996

    accuracy                           0.81      3000
   macro avg       0.72      0.82      0.75      3000
weighted avg       0.82      0.81      0.81      3000

Classification Report : 5 -               precision    recall  f1-score   support

           0       0.51      0.76      0.61        34
           1       0.73      0.77      0.75       641
           2       0.79      0.71      0.75      1329
           3       0.81      0.86      0.84       996

    accuracy                           0.78      3000
   macro avg       0.71      0.78      0.74      3000
weighted avg       0.78      0.78      0.78      3000

Classification Report : 6 -               precision    recall  f1-score   support

           0       0.48      0.74      0.58        34
           1       0.73      0.77      0.75       641
           2       0.79      0.72      0.75      1329
           3       0.81      0.87      0.84       996

    accuracy                           0.78      3000
   macro avg       0.70      0.77      0.73      3000
weighted avg       0.78      0.78      0.78      3000

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Classification Report : 7 -               precision    recall  f1-score   support

           0       0.46      0.85      0.60        34
           1       0.80      0.83      0.81       641
           2       0.84      0.78      0.81      1329
           3       0.85      0.88      0.86       996

    accuracy                           0.83      3000
   macro avg       0.74      0.84      0.77      3000
weighted avg       0.83      0.83      0.83      3000

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Classification Report : 8 -               precision    recall  f1-score   support

           0       0.48      0.85      0.61        34
           1       0.80      0.83      0.81       641
           2       0.85      0.79      0.82      1329
           3       0.85      0.89      0.87       996

    accuracy                           0.83      3000
   macro avg       0.74      0.84      0.78      3000
weighted avg       0.83      0.83      0.83      3000

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Classification Report : 9 -               precision    recall  f1-score   support

           0       0.41      0.85      0.55        34
           1       0.75      0.80      0.77       641
           2       0.82      0.75      0.79      1329
           3       0.84      0.87      0.85       996

    accuracy                           0.80      3000
   macro avg       0.71      0.82      0.74      3000
weighted avg       0.81      0.80      0.80      3000

Classification Report : 10 -               precision    recall  f1-score   support

           0       0.41      0.82      0.54        34
           1       0.75      0.80      0.77       641
           2       0.82      0.74      0.78      1329
           3       0.83      0.87      0.85       996

    accuracy                           0.80      3000
   macro avg       0.70      0.81      0.74      3000
weighted avg       0.80      0.80      0.80      3000

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

For Random Forest Classifier

In [126]:
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestClassifier
c = 0
for XTrain,XTest in data_list:
  c += 1
  rf = RandomForestClassifier(class_weight='balanced',random_state=7,n_estimators=100)
  rf.fit(XTrain,Y_train)
  y_pred = rf.predict(XTest)
  print(f'Classification Report : {c} - {classification_report(Y_test,y_pred)}')

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Classification Report : 1 -               precision    recall  f1-score   support

           0       0.00      0.00      0.00        34
           1       0.80      0.54      0.65       641
           2       0.69      0.87      0.77      1329
           3       0.86      0.77      0.81       996

    accuracy                           0.75      3000
   macro avg       0.59      0.54      0.56      3000
weighted avg       0.76      0.75      0.75      3000

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Classification Report : 2 -               precision    recall  f1-score   support

           0       0.00      0.00      0.00        34
           1       0.81      0.56      0.66       641
           2       0.69      0.86      0.77      1329
           3       0.86      0.77      0.81       996

    accuracy                           0.76      3000
   macro avg       0.59      0.55      0.56      3000
weighted avg       0.76      0.76      0.75      3000

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Classification Report : 3 -               precision    recall  f1-score   support

           0       0.00      0.00      0.00        34
           1       0.81      0.43      0.56       641
           2       0.65      0.89      0.75      1329
           3       0.86      0.73      0.79       996

    accuracy                           0.73      3000
   macro avg       0.58      0.51      0.53      3000
weighted avg       0.75      0.73      0.72      3000

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Classification Report : 4 -               precision    recall  f1-score   support

           0       0.00      0.00      0.00        34
           1       0.78      0.39      0.52       641
           2       0.64      0.88      0.74      1329
           3       0.86      0.73      0.79       996

    accuracy                           0.72      3000
   macro avg       0.57      0.50      0.51      3000
weighted avg       0.73      0.72      0.70      3000

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Classification Report : 5 -               precision    recall  f1-score   support

           0       0.00      0.00      0.00        34
           1       0.75      0.02      0.05       641
           2       0.49      0.88      0.63      1329
           3       0.73      0.44      0.55       996

    accuracy                           0.54      3000
   macro avg       0.49      0.34      0.31      3000
weighted avg       0.62      0.54      0.47      3000

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Classification Report : 6 -               precision    recall  f1-score   support

           0       0.00      0.00      0.00        34
           1       0.86      0.02      0.04       641
           2       0.49      0.87      0.63      1329
           3       0.69      0.44      0.54       996

    accuracy                           0.54      3000
   macro avg       0.51      0.33      0.30      3000
weighted avg       0.63      0.54      0.47      3000

Classification Report : 7 -               precision    recall  f1-score   support

           0       1.00      0.03      0.06        34
           1       0.83      0.61      0.70       641
           2       0.71      0.87      0.78      1329
           3       0.86      0.79      0.82       996

    accuracy                           0.78      3000
   macro avg       0.85      0.57      0.59      3000
weighted avg       0.79      0.78      0.77      3000

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

Classification Report : 8 -               precision    recall  f1-score   support

           0       0.00      0.00      0.00        34
           1       0.83      0.59      0.69       641
           2       0.71      0.88      0.78      1329
           3       0.87      0.78      0.82       996

    accuracy                           0.78      3000
   macro avg       0.60      0.56      0.57      3000
weighted avg       0.78      0.78      0.77      3000

Classification Report : 9 -               precision    recall  f1-score   support

           0       0.67      0.12      0.20        34
           1       0.82      0.60      0.69       641
           2       0.71      0.85      0.78      1329
           3       0.85      0.80      0.82       996

    accuracy                           0.77      3000
   macro avg       0.76      0.59      0.62      3000
weighted avg       0.78      0.77      0.77      3000

Classification Report : 10 -               precision    recall  f1-score   support

           0       0.80      0.12      0.21        34
           1       0.81      0.63      0.71       641
           2       0.72      0.84      0.77      1329
           3       0.85      0.79      0.82       996

    accuracy                           0.77      3000
   macro avg       0.79      0.60      0.63      3000
weighted avg       0.78      0.77      0.77      3000